// Code generated by Thrift Compiler (0.23.0). DO NOT EDIT.

package main

import (
	"context"
	"flag"
	"fmt"
	"math"
	"net"
	"net/url"
	"os"
	"strconv"
	"strings"
	thrift "github.com/apache/thrift/lib/go/thrift"
	"github.com/heavyai/webserver/internal/db_thrift_client/common"
	"github.com/heavyai/webserver/internal/db_thrift_client/completion_hints"
	"github.com/heavyai/webserver/internal/db_thrift_client/serialized_result_set"
	"github.com/heavyai/webserver/internal/db_thrift_client/extension_functions"
	"github.com/heavyai/webserver/internal/db_thrift_client/heavy"
)

var _ = common.GoUnusedProtection__
var _ = completion_hints.GoUnusedProtection__
var _ = serialized_result_set.GoUnusedProtection__
var _ = extension_functions.GoUnusedProtection__
var _ = heavy.GoUnusedProtection__

func Usage() {
	fmt.Fprintln(os.Stderr, "Usage of ", os.Args[0], " [-h host:port] [-u url] [-f[ramed]] function [arg1 [arg2...]]:")
	flag.PrintDefaults()
	fmt.Fprintln(os.Stderr, "\nFunctions:")
	fmt.Fprintln(os.Stderr, "  TSessionId connect(string user, string passwd, string dbname)")
	fmt.Fprintln(os.Stderr, "  void disconnect(TSessionId session)")
	fmt.Fprintln(os.Stderr, "  void switch_database(TSessionId session, string dbname)")
	fmt.Fprintln(os.Stderr, "  TSessionId clone_session(TSessionId session)")
	fmt.Fprintln(os.Stderr, "  TServerStatus get_server_status(TSessionId session)")
	fmt.Fprintln(os.Stderr, "   get_status(TSessionId session)")
	fmt.Fprintln(os.Stderr, "  TClusterHardwareInfo get_hardware_info(TSessionId session)")
	fmt.Fprintln(os.Stderr, "   get_tables(TSessionId session)")
	fmt.Fprintln(os.Stderr, "   get_tables_for_database(TSessionId session, string database_name)")
	fmt.Fprintln(os.Stderr, "   get_physical_tables(TSessionId session)")
	fmt.Fprintln(os.Stderr, "   get_views(TSessionId session)")
	fmt.Fprintln(os.Stderr, "   get_tables_meta(TSessionId session)")
	fmt.Fprintln(os.Stderr, "  TTableDetails get_table_details(TSessionId session, string table_name)")
	fmt.Fprintln(os.Stderr, "  TTableDetails get_table_details_for_database(TSessionId session, string table_name, string database_name)")
	fmt.Fprintln(os.Stderr, "  TTableDetails get_internal_table_details(TSessionId session, string table_name, bool include_system_columns)")
	fmt.Fprintln(os.Stderr, "  TTableDetails get_internal_table_details_for_database(TSessionId session, string table_name, string database_name)")
	fmt.Fprintln(os.Stderr, "   get_users(TSessionId session)")
	fmt.Fprintln(os.Stderr, "  string get_version()")
	fmt.Fprintln(os.Stderr, "  void start_heap_profile(TSessionId session)")
	fmt.Fprintln(os.Stderr, "  void stop_heap_profile(TSessionId session)")
	fmt.Fprintln(os.Stderr, "  string get_heap_profile(TSessionId session)")
	fmt.Fprintln(os.Stderr, "   get_memory(TSessionId session, string memory_level)")
	fmt.Fprintln(os.Stderr, "  void clear_cpu_memory(TSessionId session)")
	fmt.Fprintln(os.Stderr, "  void clear_gpu_memory(TSessionId session)")
	fmt.Fprintln(os.Stderr, "  void set_table_epoch(TSessionId session, i32 db_id, i32 table_id, i32 new_epoch)")
	fmt.Fprintln(os.Stderr, "  void set_table_epoch_by_name(TSessionId session, string table_name, i32 new_epoch)")
	fmt.Fprintln(os.Stderr, "  i32 get_table_epoch(TSessionId session, i32 db_id, i32 table_id)")
	fmt.Fprintln(os.Stderr, "  i32 get_table_epoch_by_name(TSessionId session, string table_name)")
	fmt.Fprintln(os.Stderr, "   get_table_epochs(TSessionId session, i32 db_id, i32 table_id)")
	fmt.Fprintln(os.Stderr, "  void set_table_epochs(TSessionId session, i32 db_id,  table_epochs)")
	fmt.Fprintln(os.Stderr, "  TSessionInfo get_session_info(TSessionId session)")
	fmt.Fprintln(os.Stderr, "   get_queries_info(TSessionId session)")
	fmt.Fprintln(os.Stderr, "  TQueryResult sql_execute(TSessionId session, string query, bool column_format, string nonce, i32 first_n, i32 at_most_n)")
	fmt.Fprintln(os.Stderr, "  TDataFrame sql_execute_df(TSessionId session, string query, TDeviceType device_type, i32 device_id, i32 first_n, TArrowTransport transport_method)")
	fmt.Fprintln(os.Stderr, "  TDataFrame sql_execute_gdf(TSessionId session, string query, i32 device_id, i32 first_n)")
	fmt.Fprintln(os.Stderr, "  void deallocate_df(TSessionId session, TDataFrame df, TDeviceType device_type, i32 device_id)")
	fmt.Fprintln(os.Stderr, "  void interrupt(TSessionId query_session, TSessionId interrupt_session)")
	fmt.Fprintln(os.Stderr, "  TRowDescriptor sql_validate(TSessionId session, string query)")
	fmt.Fprintln(os.Stderr, "   get_completion_hints(TSessionId session, string sql, i32 cursor)")
	fmt.Fprintln(os.Stderr, "  void set_execution_mode(TSessionId session, TExecuteMode mode)")
	fmt.Fprintln(os.Stderr, "  TRenderResult render_vega(TSessionId session, i64 widget_id, string vega_json, i32 compression_level, string nonce)")
	fmt.Fprintln(os.Stderr, "  TPixelTableRowResult get_result_row_for_pixel(TSessionId session, i64 widget_id, TPixel pixel,  table_col_names, bool column_format, i32 pixelRadius, string nonce)")
	fmt.Fprintln(os.Stderr, "  i32 create_custom_expression(TSessionId session, TCustomExpression custom_expression)")
	fmt.Fprintln(os.Stderr, "   get_custom_expressions(TSessionId session)")
	fmt.Fprintln(os.Stderr, "  void update_custom_expression(TSessionId session, i32 id, string expression_json)")
	fmt.Fprintln(os.Stderr, "  void delete_custom_expressions(TSessionId session,  custom_expression_ids, bool do_soft_delete)")
	fmt.Fprintln(os.Stderr, "  TDashboard get_dashboard(TSessionId session, i32 dashboard_id)")
	fmt.Fprintln(os.Stderr, "   get_dashboards(TSessionId session)")
	fmt.Fprintln(os.Stderr, "  i32 create_dashboard(TSessionId session, string dashboard_name, string dashboard_state, string image_hash, string dashboard_metadata)")
	fmt.Fprintln(os.Stderr, "  void replace_dashboard(TSessionId session, i32 dashboard_id, string dashboard_name, string dashboard_owner, string dashboard_state, string image_hash, string dashboard_metadata)")
	fmt.Fprintln(os.Stderr, "  void delete_dashboard(TSessionId session, i32 dashboard_id)")
	fmt.Fprintln(os.Stderr, "  void share_dashboards(TSessionId session,  dashboard_ids,  groups, TDashboardPermissions permissions)")
	fmt.Fprintln(os.Stderr, "  void delete_dashboards(TSessionId session,  dashboard_ids)")
	fmt.Fprintln(os.Stderr, "  void share_dashboard(TSessionId session, i32 dashboard_id,  groups,  objects, TDashboardPermissions permissions, bool grant_role)")
	fmt.Fprintln(os.Stderr, "  void unshare_dashboard(TSessionId session, i32 dashboard_id,  groups,  objects, TDashboardPermissions permissions)")
	fmt.Fprintln(os.Stderr, "  void unshare_dashboards(TSessionId session,  dashboard_ids,  groups, TDashboardPermissions permissions)")
	fmt.Fprintln(os.Stderr, "   get_dashboard_grantees(TSessionId session, i32 dashboard_id)")
	fmt.Fprintln(os.Stderr, "  TFrontendView get_link_view(TSessionId session, string link)")
	fmt.Fprintln(os.Stderr, "  string create_link(TSessionId session, string view_state, string view_metadata)")
	fmt.Fprintln(os.Stderr, "  void load_table_binary(TSessionId session, string table_name,  rows,  column_names)")
	fmt.Fprintln(os.Stderr, "  void load_table_binary_columnar(TSessionId session, string table_name,  cols,  column_names)")
	fmt.Fprintln(os.Stderr, "  void load_table_binary_arrow(TSessionId session, string table_name, string arrow_stream, bool use_column_names)")
	fmt.Fprintln(os.Stderr, "  void load_table(TSessionId session, string table_name,  rows,  column_names)")
	fmt.Fprintln(os.Stderr, "  TDetectResult detect_column_types(TSessionId session, string file_name, TCopyParams copy_params)")
	fmt.Fprintln(os.Stderr, "  void create_table(TSessionId session, string table_name, TRowDescriptor row_desc)")
	fmt.Fprintln(os.Stderr, "  void import_table(TSessionId session, string table_name, string file_name, TCopyParams copy_params)")
	fmt.Fprintln(os.Stderr, "  void import_geo_table(TSessionId session, string table_name, string file_name, TCopyParams copy_params, TRowDescriptor row_desc)")
	fmt.Fprintln(os.Stderr, "  TImportStatus import_table_status(TSessionId session, string import_id)")
	fmt.Fprintln(os.Stderr, "  string get_first_geo_file_in_archive(TSessionId session, string archive_path, TCopyParams copy_params)")
	fmt.Fprintln(os.Stderr, "   get_all_files_in_archive(TSessionId session, string archive_path, TCopyParams copy_params)")
	fmt.Fprintln(os.Stderr, "   get_layers_in_geo_file(TSessionId session, string file_name, TCopyParams copy_params)")
	fmt.Fprintln(os.Stderr, "   get_roles(TSessionId session)")
	fmt.Fprintln(os.Stderr, "   get_db_objects_for_grantee(TSessionId session, string roleName)")
	fmt.Fprintln(os.Stderr, "   get_db_object_privs(TSessionId session, string objectName, TDBObjectType type)")
	fmt.Fprintln(os.Stderr, "   get_all_roles_for_user(TSessionId session, string userName)")
	fmt.Fprintln(os.Stderr, "   get_all_effective_roles_for_user(TSessionId session, string userName)")
	fmt.Fprintln(os.Stderr, "  bool has_role(TSessionId session, string granteeName, string roleName)")
	fmt.Fprintln(os.Stderr, "  bool has_object_privilege(TSessionId session, string granteeName, string ObjectName, TDBObjectType objectType, TDBObjectPermissions permissions)")
	fmt.Fprintln(os.Stderr, "   get_device_parameters(TSessionId session)")
	fmt.Fprintln(os.Stderr, "  void register_runtime_extension_functions(TSessionId session,  udfs,  udtfs,  device_ir_map)")
	fmt.Fprintln(os.Stderr, "   get_table_function_names(TSessionId session)")
	fmt.Fprintln(os.Stderr, "   get_runtime_table_function_names(TSessionId session)")
	fmt.Fprintln(os.Stderr, "   get_table_function_details(TSessionId session,  udtf_names)")
	fmt.Fprintln(os.Stderr, "   get_function_names(TSessionId session)")
	fmt.Fprintln(os.Stderr, "   get_runtime_function_names(TSessionId session)")
	fmt.Fprintln(os.Stderr, "   get_function_details(TSessionId session,  udf_names)")
	fmt.Fprintln(os.Stderr, "  void put_immerse_users_metadata(TSessionId session,  immerse_user_metadata_list)")
	fmt.Fprintln(os.Stderr, "  void put_immerse_database_metadata(TSessionId session, string immerse_metadata_json, string database_name)")
	fmt.Fprintln(os.Stderr, "   get_users_info(TSessionId session)")
	fmt.Fprintln(os.Stderr, "   get_databases(TSessionId session)")
	fmt.Fprintln(os.Stderr)
	os.Exit(0)
}

type httpHeaders map[string]string

func (h httpHeaders) String() string {
	var m map[string]string = h
	return fmt.Sprintf("%s", m)
}

func (h httpHeaders) Set(value string) error {
	parts := strings.Split(value, ": ")
	if len(parts) != 2 {
		return fmt.Errorf("header should be of format 'Key: Value'")
	}
	h[parts[0]] = parts[1]
	return nil
}

func main() {
	flag.Usage = Usage
	var host string
	var port int
	var protocol string
	var urlString string
	var framed bool
	var useHttp bool
	headers := make(httpHeaders)
	var parsedUrl *url.URL
	var trans thrift.TTransport
	_ = strconv.Atoi
	_ = math.Abs
	flag.Usage = Usage
	flag.StringVar(&host, "h", "localhost", "Specify host and port")
	flag.IntVar(&port, "p", 9090, "Specify port")
	flag.StringVar(&protocol, "P", "binary", "Specify the protocol (binary, compact, simplejson, json)")
	flag.StringVar(&urlString, "u", "", "Specify the url")
	flag.BoolVar(&framed, "framed", false, "Use framed transport")
	flag.BoolVar(&useHttp, "http", false, "Use http")
	flag.Var(headers, "H", "Headers to set on the http(s) request (e.g. -H \"Key: Value\")")
	flag.Parse()
	
	if len(urlString) > 0 {
		var err error
		parsedUrl, err = url.Parse(urlString)
		if err != nil {
			fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
			flag.Usage()
		}
		host = parsedUrl.Host
		useHttp = len(parsedUrl.Scheme) <= 0 || parsedUrl.Scheme == "http" || parsedUrl.Scheme == "https"
	} else if useHttp {
		_, err := url.Parse(fmt.Sprint("http://", host, ":", port))
		if err != nil {
			fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
			flag.Usage()
		}
	}
	
	cmd := flag.Arg(0)
	var err error
	var cfg *thrift.TConfiguration = nil
	if useHttp {
		trans, err = thrift.NewTHttpClient(parsedUrl.String())
		if len(headers) > 0 {
			httptrans := trans.(*thrift.THttpClient)
			for key, value := range headers {
				httptrans.SetHeader(key, value)
			}
		}
	} else {
		portStr := fmt.Sprint(port)
		if strings.Contains(host, ":") {
			host, portStr, err = net.SplitHostPort(host)
			if err != nil {
				fmt.Fprintln(os.Stderr, "error with host:", err)
				os.Exit(1)
			}
		}
		trans = thrift.NewTSocketConf(net.JoinHostPort(host, portStr), cfg)
		if err != nil {
			fmt.Fprintln(os.Stderr, "error resolving address:", err)
			os.Exit(1)
		}
		if framed {
			trans = thrift.NewTFramedTransportConf(trans, cfg)
		}
	}
	if err != nil {
		fmt.Fprintln(os.Stderr, "Error creating transport", err)
		os.Exit(1)
	}
	defer trans.Close()
	var protocolFactory thrift.TProtocolFactory
	switch protocol {
	case "compact":
		protocolFactory = thrift.NewTCompactProtocolFactoryConf(cfg)
	case "simplejson":
		protocolFactory = thrift.NewTSimpleJSONProtocolFactoryConf(cfg)
	case "json":
		protocolFactory = thrift.NewTJSONProtocolFactory()
	case "binary", "":
		protocolFactory = thrift.NewTBinaryProtocolFactoryConf(cfg)
	default:
		fmt.Fprintln(os.Stderr, "Invalid protocol specified: ", protocol)
		Usage()
		os.Exit(1)
	}
	iprot := protocolFactory.GetProtocol(trans)
	oprot := protocolFactory.GetProtocol(trans)
	client := heavy.NewHeavyClient(thrift.NewTStandardClient(iprot, oprot))
	if err := trans.Open(); err != nil {
		fmt.Fprintln(os.Stderr, "Error opening socket to ", host, ":", port, " ", err)
		os.Exit(1)
	}
	
	switch cmd {
	case "connect":
		if flag.NArg() - 1 != 3 {
			fmt.Fprintln(os.Stderr, "Connect requires 3 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		argvalue2 := flag.Arg(3)
		value2 := argvalue2
		fmt.Print(client.Connect(context.Background(), value0, value1, value2))
		fmt.Print("\n")
		break
	case "disconnect":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "Disconnect requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		fmt.Print(client.Disconnect(context.Background(), value0))
		fmt.Print("\n")
		break
	case "switch_database":
		if flag.NArg() - 1 != 2 {
			fmt.Fprintln(os.Stderr, "SwitchDatabase requires 2 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		fmt.Print(client.SwitchDatabase(context.Background(), value0, value1))
		fmt.Print("\n")
		break
	case "clone_session":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "CloneSession requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		fmt.Print(client.CloneSession(context.Background(), value0))
		fmt.Print("\n")
		break
	case "get_server_status":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "GetServerStatus requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		fmt.Print(client.GetServerStatus(context.Background(), value0))
		fmt.Print("\n")
		break
	case "get_status":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "GetStatus requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		fmt.Print(client.GetStatus(context.Background(), value0))
		fmt.Print("\n")
		break
	case "get_hardware_info":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "GetHardwareInfo requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		fmt.Print(client.GetHardwareInfo(context.Background(), value0))
		fmt.Print("\n")
		break
	case "get_tables":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "GetTables requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		fmt.Print(client.GetTables(context.Background(), value0))
		fmt.Print("\n")
		break
	case "get_tables_for_database":
		if flag.NArg() - 1 != 2 {
			fmt.Fprintln(os.Stderr, "GetTablesForDatabase requires 2 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		fmt.Print(client.GetTablesForDatabase(context.Background(), value0, value1))
		fmt.Print("\n")
		break
	case "get_physical_tables":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "GetPhysicalTables requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		fmt.Print(client.GetPhysicalTables(context.Background(), value0))
		fmt.Print("\n")
		break
	case "get_views":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "GetViews requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		fmt.Print(client.GetViews(context.Background(), value0))
		fmt.Print("\n")
		break
	case "get_tables_meta":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "GetTablesMeta requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		fmt.Print(client.GetTablesMeta(context.Background(), value0))
		fmt.Print("\n")
		break
	case "get_table_details":
		if flag.NArg() - 1 != 2 {
			fmt.Fprintln(os.Stderr, "GetTableDetails requires 2 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		fmt.Print(client.GetTableDetails(context.Background(), value0, value1))
		fmt.Print("\n")
		break
	case "get_table_details_for_database":
		if flag.NArg() - 1 != 3 {
			fmt.Fprintln(os.Stderr, "GetTableDetailsForDatabase requires 3 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		argvalue2 := flag.Arg(3)
		value2 := argvalue2
		fmt.Print(client.GetTableDetailsForDatabase(context.Background(), value0, value1, value2))
		fmt.Print("\n")
		break
	case "get_internal_table_details":
		if flag.NArg() - 1 != 3 {
			fmt.Fprintln(os.Stderr, "GetInternalTableDetails requires 3 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		argvalue2 := flag.Arg(3) == "true"
		value2 := argvalue2
		fmt.Print(client.GetInternalTableDetails(context.Background(), value0, value1, value2))
		fmt.Print("\n")
		break
	case "get_internal_table_details_for_database":
		if flag.NArg() - 1 != 3 {
			fmt.Fprintln(os.Stderr, "GetInternalTableDetailsForDatabase requires 3 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		argvalue2 := flag.Arg(3)
		value2 := argvalue2
		fmt.Print(client.GetInternalTableDetailsForDatabase(context.Background(), value0, value1, value2))
		fmt.Print("\n")
		break
	case "get_users":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "GetUsers requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		fmt.Print(client.GetUsers(context.Background(), value0))
		fmt.Print("\n")
		break
	case "get_version":
		if flag.NArg() - 1 != 0 {
			fmt.Fprintln(os.Stderr, "GetVersion requires 0 args")
			flag.Usage()
		}
		fmt.Print(client.GetVersion(context.Background()))
		fmt.Print("\n")
		break
	case "start_heap_profile":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "StartHeapProfile requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		fmt.Print(client.StartHeapProfile(context.Background(), value0))
		fmt.Print("\n")
		break
	case "stop_heap_profile":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "StopHeapProfile requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		fmt.Print(client.StopHeapProfile(context.Background(), value0))
		fmt.Print("\n")
		break
	case "get_heap_profile":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "GetHeapProfile requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		fmt.Print(client.GetHeapProfile(context.Background(), value0))
		fmt.Print("\n")
		break
	case "get_memory":
		if flag.NArg() - 1 != 2 {
			fmt.Fprintln(os.Stderr, "GetMemory requires 2 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		fmt.Print(client.GetMemory(context.Background(), value0, value1))
		fmt.Print("\n")
		break
	case "clear_cpu_memory":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "ClearCPUMemory requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		fmt.Print(client.ClearCPUMemory(context.Background(), value0))
		fmt.Print("\n")
		break
	case "clear_gpu_memory":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "ClearGpuMemory requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		fmt.Print(client.ClearGpuMemory(context.Background(), value0))
		fmt.Print("\n")
		break
	case "set_table_epoch":
		if flag.NArg() - 1 != 4 {
			fmt.Fprintln(os.Stderr, "SetTableEpoch requires 4 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		tmp1, err609 := (strconv.Atoi(flag.Arg(2)))
		if err609 != nil {
			Usage()
			return
		}
		argvalue1 := int32(tmp1)
		value1 := argvalue1
		tmp2, err610 := (strconv.Atoi(flag.Arg(3)))
		if err610 != nil {
			Usage()
			return
		}
		argvalue2 := int32(tmp2)
		value2 := argvalue2
		tmp3, err611 := (strconv.Atoi(flag.Arg(4)))
		if err611 != nil {
			Usage()
			return
		}
		argvalue3 := int32(tmp3)
		value3 := argvalue3
		fmt.Print(client.SetTableEpoch(context.Background(), value0, value1, value2, value3))
		fmt.Print("\n")
		break
	case "set_table_epoch_by_name":
		if flag.NArg() - 1 != 3 {
			fmt.Fprintln(os.Stderr, "SetTableEpochByName requires 3 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		tmp2, err614 := (strconv.Atoi(flag.Arg(3)))
		if err614 != nil {
			Usage()
			return
		}
		argvalue2 := int32(tmp2)
		value2 := argvalue2
		fmt.Print(client.SetTableEpochByName(context.Background(), value0, value1, value2))
		fmt.Print("\n")
		break
	case "get_table_epoch":
		if flag.NArg() - 1 != 3 {
			fmt.Fprintln(os.Stderr, "GetTableEpoch requires 3 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		tmp1, err616 := (strconv.Atoi(flag.Arg(2)))
		if err616 != nil {
			Usage()
			return
		}
		argvalue1 := int32(tmp1)
		value1 := argvalue1
		tmp2, err617 := (strconv.Atoi(flag.Arg(3)))
		if err617 != nil {
			Usage()
			return
		}
		argvalue2 := int32(tmp2)
		value2 := argvalue2
		fmt.Print(client.GetTableEpoch(context.Background(), value0, value1, value2))
		fmt.Print("\n")
		break
	case "get_table_epoch_by_name":
		if flag.NArg() - 1 != 2 {
			fmt.Fprintln(os.Stderr, "GetTableEpochByName requires 2 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		fmt.Print(client.GetTableEpochByName(context.Background(), value0, value1))
		fmt.Print("\n")
		break
	case "get_table_epochs":
		if flag.NArg() - 1 != 3 {
			fmt.Fprintln(os.Stderr, "GetTableEpochs requires 3 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		tmp1, err621 := (strconv.Atoi(flag.Arg(2)))
		if err621 != nil {
			Usage()
			return
		}
		argvalue1 := int32(tmp1)
		value1 := argvalue1
		tmp2, err622 := (strconv.Atoi(flag.Arg(3)))
		if err622 != nil {
			Usage()
			return
		}
		argvalue2 := int32(tmp2)
		value2 := argvalue2
		fmt.Print(client.GetTableEpochs(context.Background(), value0, value1, value2))
		fmt.Print("\n")
		break
	case "set_table_epochs":
		if flag.NArg() - 1 != 3 {
			fmt.Fprintln(os.Stderr, "SetTableEpochs requires 3 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		tmp1, err624 := (strconv.Atoi(flag.Arg(2)))
		if err624 != nil {
			Usage()
			return
		}
		argvalue1 := int32(tmp1)
		value1 := argvalue1
		arg625 := flag.Arg(3)
		mbTrans626 := thrift.NewTMemoryBufferLen(len(arg625))
		defer mbTrans626.Close()
		_, err627 := mbTrans626.WriteString(arg625)
		if err627 != nil {
			Usage()
			return
		}
		factory628 := thrift.NewTJSONProtocolFactory()
		jsProt629 := factory628.GetProtocol(mbTrans626)
		containerStruct2 := heavy.NewHeavySetTableEpochsArgs()
		err630 := containerStruct2.ReadField3(context.Background(), jsProt629)
		if err630 != nil {
			Usage()
			return
		}
		argvalue2 := containerStruct2.TableEpochs
		value2 := argvalue2
		fmt.Print(client.SetTableEpochs(context.Background(), value0, value1, value2))
		fmt.Print("\n")
		break
	case "get_session_info":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "GetSessionInfo requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		fmt.Print(client.GetSessionInfo(context.Background(), value0))
		fmt.Print("\n")
		break
	case "get_queries_info":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "GetQueriesInfo requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		fmt.Print(client.GetQueriesInfo(context.Background(), value0))
		fmt.Print("\n")
		break
	case "sql_execute":
		if flag.NArg() - 1 != 6 {
			fmt.Fprintln(os.Stderr, "SqlExecute requires 6 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		argvalue2 := flag.Arg(3) == "true"
		value2 := argvalue2
		argvalue3 := flag.Arg(4)
		value3 := argvalue3
		tmp4, err637 := (strconv.Atoi(flag.Arg(5)))
		if err637 != nil {
			Usage()
			return
		}
		argvalue4 := int32(tmp4)
		value4 := argvalue4
		tmp5, err638 := (strconv.Atoi(flag.Arg(6)))
		if err638 != nil {
			Usage()
			return
		}
		argvalue5 := int32(tmp5)
		value5 := argvalue5
		fmt.Print(client.SqlExecute(context.Background(), value0, value1, value2, value3, value4, value5))
		fmt.Print("\n")
		break
	case "sql_execute_df":
		if flag.NArg() - 1 != 6 {
			fmt.Fprintln(os.Stderr, "SqlExecuteDf requires 6 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		tmp2, err := (strconv.Atoi(flag.Arg(3)))
		if err != nil {
			Usage()
			return
		}
		argvalue2 := heavy.TDeviceType(tmp2)
		value2 := argvalue2
		tmp3, err641 := (strconv.Atoi(flag.Arg(4)))
		if err641 != nil {
			Usage()
			return
		}
		argvalue3 := int32(tmp3)
		value3 := argvalue3
		tmp4, err642 := (strconv.Atoi(flag.Arg(5)))
		if err642 != nil {
			Usage()
			return
		}
		argvalue4 := int32(tmp4)
		value4 := argvalue4
		tmp5, err := (strconv.Atoi(flag.Arg(6)))
		if err != nil {
			Usage()
			return
		}
		argvalue5 := heavy.TArrowTransport(tmp5)
		value5 := argvalue5
		fmt.Print(client.SqlExecuteDf(context.Background(), value0, value1, value2, value3, value4, value5))
		fmt.Print("\n")
		break
	case "sql_execute_gdf":
		if flag.NArg() - 1 != 4 {
			fmt.Fprintln(os.Stderr, "SqlExecuteGdf requires 4 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		tmp2, err645 := (strconv.Atoi(flag.Arg(3)))
		if err645 != nil {
			Usage()
			return
		}
		argvalue2 := int32(tmp2)
		value2 := argvalue2
		tmp3, err646 := (strconv.Atoi(flag.Arg(4)))
		if err646 != nil {
			Usage()
			return
		}
		argvalue3 := int32(tmp3)
		value3 := argvalue3
		fmt.Print(client.SqlExecuteGdf(context.Background(), value0, value1, value2, value3))
		fmt.Print("\n")
		break
	case "deallocate_df":
		if flag.NArg() - 1 != 4 {
			fmt.Fprintln(os.Stderr, "DeallocateDf requires 4 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		arg648 := flag.Arg(2)
		mbTrans649 := thrift.NewTMemoryBufferLen(len(arg648))
		defer mbTrans649.Close()
		_, err650 := mbTrans649.WriteString(arg648)
		if err650 != nil {
			Usage()
			return
		}
		factory651 := thrift.NewTJSONProtocolFactory()
		jsProt652 := factory651.GetProtocol(mbTrans649)
		argvalue1 := heavy.NewTDataFrame()
		err653 := argvalue1.Read(context.Background(), jsProt652)
		if err653 != nil {
			Usage()
			return
		}
		value1 := argvalue1
		tmp2, err := (strconv.Atoi(flag.Arg(3)))
		if err != nil {
			Usage()
			return
		}
		argvalue2 := heavy.TDeviceType(tmp2)
		value2 := argvalue2
		tmp3, err654 := (strconv.Atoi(flag.Arg(4)))
		if err654 != nil {
			Usage()
			return
		}
		argvalue3 := int32(tmp3)
		value3 := argvalue3
		fmt.Print(client.DeallocateDf(context.Background(), value0, value1, value2, value3))
		fmt.Print("\n")
		break
	case "interrupt":
		if flag.NArg() - 1 != 2 {
			fmt.Fprintln(os.Stderr, "Interrupt requires 2 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		argvalue1 := flag.Arg(2)
		value1 := heavy.TSessionId(argvalue1)
		fmt.Print(client.Interrupt(context.Background(), value0, value1))
		fmt.Print("\n")
		break
	case "sql_validate":
		if flag.NArg() - 1 != 2 {
			fmt.Fprintln(os.Stderr, "SqlValidate requires 2 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		fmt.Print(client.SqlValidate(context.Background(), value0, value1))
		fmt.Print("\n")
		break
	case "get_completion_hints":
		if flag.NArg() - 1 != 3 {
			fmt.Fprintln(os.Stderr, "GetCompletionHints requires 3 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		tmp2, err661 := (strconv.Atoi(flag.Arg(3)))
		if err661 != nil {
			Usage()
			return
		}
		argvalue2 := int32(tmp2)
		value2 := argvalue2
		fmt.Print(client.GetCompletionHints(context.Background(), value0, value1, value2))
		fmt.Print("\n")
		break
	case "set_execution_mode":
		if flag.NArg() - 1 != 2 {
			fmt.Fprintln(os.Stderr, "SetExecutionMode requires 2 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		tmp1, err := (strconv.Atoi(flag.Arg(2)))
		if err != nil {
			Usage()
			return
		}
		argvalue1 := heavy.TExecuteMode(tmp1)
		value1 := argvalue1
		fmt.Print(client.SetExecutionMode(context.Background(), value0, value1))
		fmt.Print("\n")
		break
	case "render_vega":
		if flag.NArg() - 1 != 5 {
			fmt.Fprintln(os.Stderr, "RenderVega requires 5 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		argvalue1, err664 := (strconv.ParseInt(flag.Arg(2), 10, 64))
		if err664 != nil {
			Usage()
			return
		}
		value1 := argvalue1
		argvalue2 := flag.Arg(3)
		value2 := argvalue2
		tmp3, err666 := (strconv.Atoi(flag.Arg(4)))
		if err666 != nil {
			Usage()
			return
		}
		argvalue3 := int32(tmp3)
		value3 := argvalue3
		argvalue4 := flag.Arg(5)
		value4 := argvalue4
		fmt.Print(client.RenderVega(context.Background(), value0, value1, value2, value3, value4))
		fmt.Print("\n")
		break
	case "get_result_row_for_pixel":
		if flag.NArg() - 1 != 7 {
			fmt.Fprintln(os.Stderr, "GetResultRowForPixel requires 7 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		argvalue1, err669 := (strconv.ParseInt(flag.Arg(2), 10, 64))
		if err669 != nil {
			Usage()
			return
		}
		value1 := argvalue1
		arg670 := flag.Arg(3)
		mbTrans671 := thrift.NewTMemoryBufferLen(len(arg670))
		defer mbTrans671.Close()
		_, err672 := mbTrans671.WriteString(arg670)
		if err672 != nil {
			Usage()
			return
		}
		factory673 := thrift.NewTJSONProtocolFactory()
		jsProt674 := factory673.GetProtocol(mbTrans671)
		argvalue2 := heavy.NewTPixel()
		err675 := argvalue2.Read(context.Background(), jsProt674)
		if err675 != nil {
			Usage()
			return
		}
		value2 := argvalue2
		arg676 := flag.Arg(4)
		mbTrans677 := thrift.NewTMemoryBufferLen(len(arg676))
		defer mbTrans677.Close()
		_, err678 := mbTrans677.WriteString(arg676)
		if err678 != nil {
			Usage()
			return
		}
		factory679 := thrift.NewTJSONProtocolFactory()
		jsProt680 := factory679.GetProtocol(mbTrans677)
		containerStruct3 := heavy.NewHeavyGetResultRowForPixelArgs()
		err681 := containerStruct3.ReadField4(context.Background(), jsProt680)
		if err681 != nil {
			Usage()
			return
		}
		argvalue3 := containerStruct3.TableColNames
		value3 := argvalue3
		argvalue4 := flag.Arg(5) == "true"
		value4 := argvalue4
		tmp5, err683 := (strconv.Atoi(flag.Arg(6)))
		if err683 != nil {
			Usage()
			return
		}
		argvalue5 := int32(tmp5)
		value5 := argvalue5
		argvalue6 := flag.Arg(7)
		value6 := argvalue6
		fmt.Print(client.GetResultRowForPixel(context.Background(), value0, value1, value2, value3, value4, value5, value6))
		fmt.Print("\n")
		break
	case "create_custom_expression":
		if flag.NArg() - 1 != 2 {
			fmt.Fprintln(os.Stderr, "CreateCustomExpression requires 2 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		arg686 := flag.Arg(2)
		mbTrans687 := thrift.NewTMemoryBufferLen(len(arg686))
		defer mbTrans687.Close()
		_, err688 := mbTrans687.WriteString(arg686)
		if err688 != nil {
			Usage()
			return
		}
		factory689 := thrift.NewTJSONProtocolFactory()
		jsProt690 := factory689.GetProtocol(mbTrans687)
		argvalue1 := heavy.NewTCustomExpression()
		err691 := argvalue1.Read(context.Background(), jsProt690)
		if err691 != nil {
			Usage()
			return
		}
		value1 := argvalue1
		fmt.Print(client.CreateCustomExpression(context.Background(), value0, value1))
		fmt.Print("\n")
		break
	case "get_custom_expressions":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "GetCustomExpressions requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		fmt.Print(client.GetCustomExpressions(context.Background(), value0))
		fmt.Print("\n")
		break
	case "update_custom_expression":
		if flag.NArg() - 1 != 3 {
			fmt.Fprintln(os.Stderr, "UpdateCustomExpression requires 3 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		tmp1, err694 := (strconv.Atoi(flag.Arg(2)))
		if err694 != nil {
			Usage()
			return
		}
		argvalue1 := int32(tmp1)
		value1 := argvalue1
		argvalue2 := flag.Arg(3)
		value2 := argvalue2
		fmt.Print(client.UpdateCustomExpression(context.Background(), value0, value1, value2))
		fmt.Print("\n")
		break
	case "delete_custom_expressions":
		if flag.NArg() - 1 != 3 {
			fmt.Fprintln(os.Stderr, "DeleteCustomExpressions requires 3 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		arg697 := flag.Arg(2)
		mbTrans698 := thrift.NewTMemoryBufferLen(len(arg697))
		defer mbTrans698.Close()
		_, err699 := mbTrans698.WriteString(arg697)
		if err699 != nil {
			Usage()
			return
		}
		factory700 := thrift.NewTJSONProtocolFactory()
		jsProt701 := factory700.GetProtocol(mbTrans698)
		containerStruct1 := heavy.NewHeavyDeleteCustomExpressionsArgs()
		err702 := containerStruct1.ReadField2(context.Background(), jsProt701)
		if err702 != nil {
			Usage()
			return
		}
		argvalue1 := containerStruct1.CustomExpressionIds
		value1 := argvalue1
		argvalue2 := flag.Arg(3) == "true"
		value2 := argvalue2
		fmt.Print(client.DeleteCustomExpressions(context.Background(), value0, value1, value2))
		fmt.Print("\n")
		break
	case "get_dashboard":
		if flag.NArg() - 1 != 2 {
			fmt.Fprintln(os.Stderr, "GetDashboard requires 2 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		tmp1, err705 := (strconv.Atoi(flag.Arg(2)))
		if err705 != nil {
			Usage()
			return
		}
		argvalue1 := int32(tmp1)
		value1 := argvalue1
		fmt.Print(client.GetDashboard(context.Background(), value0, value1))
		fmt.Print("\n")
		break
	case "get_dashboards":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "GetDashboards requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		fmt.Print(client.GetDashboards(context.Background(), value0))
		fmt.Print("\n")
		break
	case "create_dashboard":
		if flag.NArg() - 1 != 5 {
			fmt.Fprintln(os.Stderr, "CreateDashboard requires 5 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		argvalue2 := flag.Arg(3)
		value2 := argvalue2
		argvalue3 := flag.Arg(4)
		value3 := argvalue3
		argvalue4 := flag.Arg(5)
		value4 := argvalue4
		fmt.Print(client.CreateDashboard(context.Background(), value0, value1, value2, value3, value4))
		fmt.Print("\n")
		break
	case "replace_dashboard":
		if flag.NArg() - 1 != 7 {
			fmt.Fprintln(os.Stderr, "ReplaceDashboard requires 7 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		tmp1, err713 := (strconv.Atoi(flag.Arg(2)))
		if err713 != nil {
			Usage()
			return
		}
		argvalue1 := int32(tmp1)
		value1 := argvalue1
		argvalue2 := flag.Arg(3)
		value2 := argvalue2
		argvalue3 := flag.Arg(4)
		value3 := argvalue3
		argvalue4 := flag.Arg(5)
		value4 := argvalue4
		argvalue5 := flag.Arg(6)
		value5 := argvalue5
		argvalue6 := flag.Arg(7)
		value6 := argvalue6
		fmt.Print(client.ReplaceDashboard(context.Background(), value0, value1, value2, value3, value4, value5, value6))
		fmt.Print("\n")
		break
	case "delete_dashboard":
		if flag.NArg() - 1 != 2 {
			fmt.Fprintln(os.Stderr, "DeleteDashboard requires 2 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		tmp1, err720 := (strconv.Atoi(flag.Arg(2)))
		if err720 != nil {
			Usage()
			return
		}
		argvalue1 := int32(tmp1)
		value1 := argvalue1
		fmt.Print(client.DeleteDashboard(context.Background(), value0, value1))
		fmt.Print("\n")
		break
	case "share_dashboards":
		if flag.NArg() - 1 != 4 {
			fmt.Fprintln(os.Stderr, "ShareDashboards requires 4 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		arg722 := flag.Arg(2)
		mbTrans723 := thrift.NewTMemoryBufferLen(len(arg722))
		defer mbTrans723.Close()
		_, err724 := mbTrans723.WriteString(arg722)
		if err724 != nil {
			Usage()
			return
		}
		factory725 := thrift.NewTJSONProtocolFactory()
		jsProt726 := factory725.GetProtocol(mbTrans723)
		containerStruct1 := heavy.NewHeavyShareDashboardsArgs()
		err727 := containerStruct1.ReadField2(context.Background(), jsProt726)
		if err727 != nil {
			Usage()
			return
		}
		argvalue1 := containerStruct1.DashboardIds
		value1 := argvalue1
		arg728 := flag.Arg(3)
		mbTrans729 := thrift.NewTMemoryBufferLen(len(arg728))
		defer mbTrans729.Close()
		_, err730 := mbTrans729.WriteString(arg728)
		if err730 != nil {
			Usage()
			return
		}
		factory731 := thrift.NewTJSONProtocolFactory()
		jsProt732 := factory731.GetProtocol(mbTrans729)
		containerStruct2 := heavy.NewHeavyShareDashboardsArgs()
		err733 := containerStruct2.ReadField3(context.Background(), jsProt732)
		if err733 != nil {
			Usage()
			return
		}
		argvalue2 := containerStruct2.Groups
		value2 := argvalue2
		arg734 := flag.Arg(4)
		mbTrans735 := thrift.NewTMemoryBufferLen(len(arg734))
		defer mbTrans735.Close()
		_, err736 := mbTrans735.WriteString(arg734)
		if err736 != nil {
			Usage()
			return
		}
		factory737 := thrift.NewTJSONProtocolFactory()
		jsProt738 := factory737.GetProtocol(mbTrans735)
		argvalue3 := heavy.NewTDashboardPermissions()
		err739 := argvalue3.Read(context.Background(), jsProt738)
		if err739 != nil {
			Usage()
			return
		}
		value3 := argvalue3
		fmt.Print(client.ShareDashboards(context.Background(), value0, value1, value2, value3))
		fmt.Print("\n")
		break
	case "delete_dashboards":
		if flag.NArg() - 1 != 2 {
			fmt.Fprintln(os.Stderr, "DeleteDashboards requires 2 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		arg741 := flag.Arg(2)
		mbTrans742 := thrift.NewTMemoryBufferLen(len(arg741))
		defer mbTrans742.Close()
		_, err743 := mbTrans742.WriteString(arg741)
		if err743 != nil {
			Usage()
			return
		}
		factory744 := thrift.NewTJSONProtocolFactory()
		jsProt745 := factory744.GetProtocol(mbTrans742)
		containerStruct1 := heavy.NewHeavyDeleteDashboardsArgs()
		err746 := containerStruct1.ReadField2(context.Background(), jsProt745)
		if err746 != nil {
			Usage()
			return
		}
		argvalue1 := containerStruct1.DashboardIds
		value1 := argvalue1
		fmt.Print(client.DeleteDashboards(context.Background(), value0, value1))
		fmt.Print("\n")
		break
	case "share_dashboard":
		if flag.NArg() - 1 != 6 {
			fmt.Fprintln(os.Stderr, "ShareDashboard requires 6 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		tmp1, err748 := (strconv.Atoi(flag.Arg(2)))
		if err748 != nil {
			Usage()
			return
		}
		argvalue1 := int32(tmp1)
		value1 := argvalue1
		arg749 := flag.Arg(3)
		mbTrans750 := thrift.NewTMemoryBufferLen(len(arg749))
		defer mbTrans750.Close()
		_, err751 := mbTrans750.WriteString(arg749)
		if err751 != nil {
			Usage()
			return
		}
		factory752 := thrift.NewTJSONProtocolFactory()
		jsProt753 := factory752.GetProtocol(mbTrans750)
		containerStruct2 := heavy.NewHeavyShareDashboardArgs()
		err754 := containerStruct2.ReadField3(context.Background(), jsProt753)
		if err754 != nil {
			Usage()
			return
		}
		argvalue2 := containerStruct2.Groups
		value2 := argvalue2
		arg755 := flag.Arg(4)
		mbTrans756 := thrift.NewTMemoryBufferLen(len(arg755))
		defer mbTrans756.Close()
		_, err757 := mbTrans756.WriteString(arg755)
		if err757 != nil {
			Usage()
			return
		}
		factory758 := thrift.NewTJSONProtocolFactory()
		jsProt759 := factory758.GetProtocol(mbTrans756)
		containerStruct3 := heavy.NewHeavyShareDashboardArgs()
		err760 := containerStruct3.ReadField4(context.Background(), jsProt759)
		if err760 != nil {
			Usage()
			return
		}
		argvalue3 := containerStruct3.Objects
		value3 := argvalue3
		arg761 := flag.Arg(5)
		mbTrans762 := thrift.NewTMemoryBufferLen(len(arg761))
		defer mbTrans762.Close()
		_, err763 := mbTrans762.WriteString(arg761)
		if err763 != nil {
			Usage()
			return
		}
		factory764 := thrift.NewTJSONProtocolFactory()
		jsProt765 := factory764.GetProtocol(mbTrans762)
		argvalue4 := heavy.NewTDashboardPermissions()
		err766 := argvalue4.Read(context.Background(), jsProt765)
		if err766 != nil {
			Usage()
			return
		}
		value4 := argvalue4
		argvalue5 := flag.Arg(6) == "true"
		value5 := argvalue5
		fmt.Print(client.ShareDashboard(context.Background(), value0, value1, value2, value3, value4, value5))
		fmt.Print("\n")
		break
	case "unshare_dashboard":
		if flag.NArg() - 1 != 5 {
			fmt.Fprintln(os.Stderr, "UnshareDashboard requires 5 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		tmp1, err769 := (strconv.Atoi(flag.Arg(2)))
		if err769 != nil {
			Usage()
			return
		}
		argvalue1 := int32(tmp1)
		value1 := argvalue1
		arg770 := flag.Arg(3)
		mbTrans771 := thrift.NewTMemoryBufferLen(len(arg770))
		defer mbTrans771.Close()
		_, err772 := mbTrans771.WriteString(arg770)
		if err772 != nil {
			Usage()
			return
		}
		factory773 := thrift.NewTJSONProtocolFactory()
		jsProt774 := factory773.GetProtocol(mbTrans771)
		containerStruct2 := heavy.NewHeavyUnshareDashboardArgs()
		err775 := containerStruct2.ReadField3(context.Background(), jsProt774)
		if err775 != nil {
			Usage()
			return
		}
		argvalue2 := containerStruct2.Groups
		value2 := argvalue2
		arg776 := flag.Arg(4)
		mbTrans777 := thrift.NewTMemoryBufferLen(len(arg776))
		defer mbTrans777.Close()
		_, err778 := mbTrans777.WriteString(arg776)
		if err778 != nil {
			Usage()
			return
		}
		factory779 := thrift.NewTJSONProtocolFactory()
		jsProt780 := factory779.GetProtocol(mbTrans777)
		containerStruct3 := heavy.NewHeavyUnshareDashboardArgs()
		err781 := containerStruct3.ReadField4(context.Background(), jsProt780)
		if err781 != nil {
			Usage()
			return
		}
		argvalue3 := containerStruct3.Objects
		value3 := argvalue3
		arg782 := flag.Arg(5)
		mbTrans783 := thrift.NewTMemoryBufferLen(len(arg782))
		defer mbTrans783.Close()
		_, err784 := mbTrans783.WriteString(arg782)
		if err784 != nil {
			Usage()
			return
		}
		factory785 := thrift.NewTJSONProtocolFactory()
		jsProt786 := factory785.GetProtocol(mbTrans783)
		argvalue4 := heavy.NewTDashboardPermissions()
		err787 := argvalue4.Read(context.Background(), jsProt786)
		if err787 != nil {
			Usage()
			return
		}
		value4 := argvalue4
		fmt.Print(client.UnshareDashboard(context.Background(), value0, value1, value2, value3, value4))
		fmt.Print("\n")
		break
	case "unshare_dashboards":
		if flag.NArg() - 1 != 4 {
			fmt.Fprintln(os.Stderr, "UnshareDashboards requires 4 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		arg789 := flag.Arg(2)
		mbTrans790 := thrift.NewTMemoryBufferLen(len(arg789))
		defer mbTrans790.Close()
		_, err791 := mbTrans790.WriteString(arg789)
		if err791 != nil {
			Usage()
			return
		}
		factory792 := thrift.NewTJSONProtocolFactory()
		jsProt793 := factory792.GetProtocol(mbTrans790)
		containerStruct1 := heavy.NewHeavyUnshareDashboardsArgs()
		err794 := containerStruct1.ReadField2(context.Background(), jsProt793)
		if err794 != nil {
			Usage()
			return
		}
		argvalue1 := containerStruct1.DashboardIds
		value1 := argvalue1
		arg795 := flag.Arg(3)
		mbTrans796 := thrift.NewTMemoryBufferLen(len(arg795))
		defer mbTrans796.Close()
		_, err797 := mbTrans796.WriteString(arg795)
		if err797 != nil {
			Usage()
			return
		}
		factory798 := thrift.NewTJSONProtocolFactory()
		jsProt799 := factory798.GetProtocol(mbTrans796)
		containerStruct2 := heavy.NewHeavyUnshareDashboardsArgs()
		err800 := containerStruct2.ReadField3(context.Background(), jsProt799)
		if err800 != nil {
			Usage()
			return
		}
		argvalue2 := containerStruct2.Groups
		value2 := argvalue2
		arg801 := flag.Arg(4)
		mbTrans802 := thrift.NewTMemoryBufferLen(len(arg801))
		defer mbTrans802.Close()
		_, err803 := mbTrans802.WriteString(arg801)
		if err803 != nil {
			Usage()
			return
		}
		factory804 := thrift.NewTJSONProtocolFactory()
		jsProt805 := factory804.GetProtocol(mbTrans802)
		argvalue3 := heavy.NewTDashboardPermissions()
		err806 := argvalue3.Read(context.Background(), jsProt805)
		if err806 != nil {
			Usage()
			return
		}
		value3 := argvalue3
		fmt.Print(client.UnshareDashboards(context.Background(), value0, value1, value2, value3))
		fmt.Print("\n")
		break
	case "get_dashboard_grantees":
		if flag.NArg() - 1 != 2 {
			fmt.Fprintln(os.Stderr, "GetDashboardGrantees requires 2 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		tmp1, err808 := (strconv.Atoi(flag.Arg(2)))
		if err808 != nil {
			Usage()
			return
		}
		argvalue1 := int32(tmp1)
		value1 := argvalue1
		fmt.Print(client.GetDashboardGrantees(context.Background(), value0, value1))
		fmt.Print("\n")
		break
	case "get_link_view":
		if flag.NArg() - 1 != 2 {
			fmt.Fprintln(os.Stderr, "GetLinkView requires 2 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		fmt.Print(client.GetLinkView(context.Background(), value0, value1))
		fmt.Print("\n")
		break
	case "create_link":
		if flag.NArg() - 1 != 3 {
			fmt.Fprintln(os.Stderr, "CreateLink requires 3 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		argvalue2 := flag.Arg(3)
		value2 := argvalue2
		fmt.Print(client.CreateLink(context.Background(), value0, value1, value2))
		fmt.Print("\n")
		break
	case "load_table_binary":
		if flag.NArg() - 1 != 4 {
			fmt.Fprintln(os.Stderr, "LoadTableBinary requires 4 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		arg816 := flag.Arg(3)
		mbTrans817 := thrift.NewTMemoryBufferLen(len(arg816))
		defer mbTrans817.Close()
		_, err818 := mbTrans817.WriteString(arg816)
		if err818 != nil {
			Usage()
			return
		}
		factory819 := thrift.NewTJSONProtocolFactory()
		jsProt820 := factory819.GetProtocol(mbTrans817)
		containerStruct2 := heavy.NewHeavyLoadTableBinaryArgs()
		err821 := containerStruct2.ReadField3(context.Background(), jsProt820)
		if err821 != nil {
			Usage()
			return
		}
		argvalue2 := containerStruct2.Rows
		value2 := argvalue2
		arg822 := flag.Arg(4)
		mbTrans823 := thrift.NewTMemoryBufferLen(len(arg822))
		defer mbTrans823.Close()
		_, err824 := mbTrans823.WriteString(arg822)
		if err824 != nil {
			Usage()
			return
		}
		factory825 := thrift.NewTJSONProtocolFactory()
		jsProt826 := factory825.GetProtocol(mbTrans823)
		containerStruct3 := heavy.NewHeavyLoadTableBinaryArgs()
		err827 := containerStruct3.ReadField4(context.Background(), jsProt826)
		if err827 != nil {
			Usage()
			return
		}
		argvalue3 := containerStruct3.ColumnNames
		value3 := argvalue3
		fmt.Print(client.LoadTableBinary(context.Background(), value0, value1, value2, value3))
		fmt.Print("\n")
		break
	case "load_table_binary_columnar":
		if flag.NArg() - 1 != 4 {
			fmt.Fprintln(os.Stderr, "LoadTableBinaryColumnar requires 4 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		arg830 := flag.Arg(3)
		mbTrans831 := thrift.NewTMemoryBufferLen(len(arg830))
		defer mbTrans831.Close()
		_, err832 := mbTrans831.WriteString(arg830)
		if err832 != nil {
			Usage()
			return
		}
		factory833 := thrift.NewTJSONProtocolFactory()
		jsProt834 := factory833.GetProtocol(mbTrans831)
		containerStruct2 := heavy.NewHeavyLoadTableBinaryColumnarArgs()
		err835 := containerStruct2.ReadField3(context.Background(), jsProt834)
		if err835 != nil {
			Usage()
			return
		}
		argvalue2 := containerStruct2.Cols
		value2 := argvalue2
		arg836 := flag.Arg(4)
		mbTrans837 := thrift.NewTMemoryBufferLen(len(arg836))
		defer mbTrans837.Close()
		_, err838 := mbTrans837.WriteString(arg836)
		if err838 != nil {
			Usage()
			return
		}
		factory839 := thrift.NewTJSONProtocolFactory()
		jsProt840 := factory839.GetProtocol(mbTrans837)
		containerStruct3 := heavy.NewHeavyLoadTableBinaryColumnarArgs()
		err841 := containerStruct3.ReadField4(context.Background(), jsProt840)
		if err841 != nil {
			Usage()
			return
		}
		argvalue3 := containerStruct3.ColumnNames
		value3 := argvalue3
		fmt.Print(client.LoadTableBinaryColumnar(context.Background(), value0, value1, value2, value3))
		fmt.Print("\n")
		break
	case "load_table_binary_arrow":
		if flag.NArg() - 1 != 4 {
			fmt.Fprintln(os.Stderr, "LoadTableBinaryArrow requires 4 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		argvalue2 := []byte(flag.Arg(3))
		value2 := argvalue2
		argvalue3 := flag.Arg(4) == "true"
		value3 := argvalue3
		fmt.Print(client.LoadTableBinaryArrow(context.Background(), value0, value1, value2, value3))
		fmt.Print("\n")
		break
	case "load_table":
		if flag.NArg() - 1 != 4 {
			fmt.Fprintln(os.Stderr, "LoadTable requires 4 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		arg848 := flag.Arg(3)
		mbTrans849 := thrift.NewTMemoryBufferLen(len(arg848))
		defer mbTrans849.Close()
		_, err850 := mbTrans849.WriteString(arg848)
		if err850 != nil {
			Usage()
			return
		}
		factory851 := thrift.NewTJSONProtocolFactory()
		jsProt852 := factory851.GetProtocol(mbTrans849)
		containerStruct2 := heavy.NewHeavyLoadTableArgs()
		err853 := containerStruct2.ReadField3(context.Background(), jsProt852)
		if err853 != nil {
			Usage()
			return
		}
		argvalue2 := containerStruct2.Rows
		value2 := argvalue2
		arg854 := flag.Arg(4)
		mbTrans855 := thrift.NewTMemoryBufferLen(len(arg854))
		defer mbTrans855.Close()
		_, err856 := mbTrans855.WriteString(arg854)
		if err856 != nil {
			Usage()
			return
		}
		factory857 := thrift.NewTJSONProtocolFactory()
		jsProt858 := factory857.GetProtocol(mbTrans855)
		containerStruct3 := heavy.NewHeavyLoadTableArgs()
		err859 := containerStruct3.ReadField4(context.Background(), jsProt858)
		if err859 != nil {
			Usage()
			return
		}
		argvalue3 := containerStruct3.ColumnNames
		value3 := argvalue3
		fmt.Print(client.LoadTable(context.Background(), value0, value1, value2, value3))
		fmt.Print("\n")
		break
	case "detect_column_types":
		if flag.NArg() - 1 != 3 {
			fmt.Fprintln(os.Stderr, "DetectColumnTypes requires 3 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		arg862 := flag.Arg(3)
		mbTrans863 := thrift.NewTMemoryBufferLen(len(arg862))
		defer mbTrans863.Close()
		_, err864 := mbTrans863.WriteString(arg862)
		if err864 != nil {
			Usage()
			return
		}
		factory865 := thrift.NewTJSONProtocolFactory()
		jsProt866 := factory865.GetProtocol(mbTrans863)
		argvalue2 := heavy.NewTCopyParams()
		err867 := argvalue2.Read(context.Background(), jsProt866)
		if err867 != nil {
			Usage()
			return
		}
		value2 := argvalue2
		fmt.Print(client.DetectColumnTypes(context.Background(), value0, value1, value2))
		fmt.Print("\n")
		break
	case "create_table":
		if flag.NArg() - 1 != 3 {
			fmt.Fprintln(os.Stderr, "CreateTable requires 3 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		arg870 := flag.Arg(3)
		mbTrans871 := thrift.NewTMemoryBufferLen(len(arg870))
		defer mbTrans871.Close()
		_, err872 := mbTrans871.WriteString(arg870)
		if err872 != nil {
			Usage()
			return
		}
		factory873 := thrift.NewTJSONProtocolFactory()
		jsProt874 := factory873.GetProtocol(mbTrans871)
		containerStruct2 := heavy.NewHeavyCreateTableArgs()
		err875 := containerStruct2.ReadField3(context.Background(), jsProt874)
		if err875 != nil {
			Usage()
			return
		}
		argvalue2 := containerStruct2.RowDesc
		value2 := heavy.TRowDescriptor(argvalue2)
		fmt.Print(client.CreateTable(context.Background(), value0, value1, value2))
		fmt.Print("\n")
		break
	case "import_table":
		if flag.NArg() - 1 != 4 {
			fmt.Fprintln(os.Stderr, "ImportTable requires 4 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		argvalue2 := flag.Arg(3)
		value2 := argvalue2
		arg879 := flag.Arg(4)
		mbTrans880 := thrift.NewTMemoryBufferLen(len(arg879))
		defer mbTrans880.Close()
		_, err881 := mbTrans880.WriteString(arg879)
		if err881 != nil {
			Usage()
			return
		}
		factory882 := thrift.NewTJSONProtocolFactory()
		jsProt883 := factory882.GetProtocol(mbTrans880)
		argvalue3 := heavy.NewTCopyParams()
		err884 := argvalue3.Read(context.Background(), jsProt883)
		if err884 != nil {
			Usage()
			return
		}
		value3 := argvalue3
		fmt.Print(client.ImportTable(context.Background(), value0, value1, value2, value3))
		fmt.Print("\n")
		break
	case "import_geo_table":
		if flag.NArg() - 1 != 5 {
			fmt.Fprintln(os.Stderr, "ImportGeoTable requires 5 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		argvalue2 := flag.Arg(3)
		value2 := argvalue2
		arg888 := flag.Arg(4)
		mbTrans889 := thrift.NewTMemoryBufferLen(len(arg888))
		defer mbTrans889.Close()
		_, err890 := mbTrans889.WriteString(arg888)
		if err890 != nil {
			Usage()
			return
		}
		factory891 := thrift.NewTJSONProtocolFactory()
		jsProt892 := factory891.GetProtocol(mbTrans889)
		argvalue3 := heavy.NewTCopyParams()
		err893 := argvalue3.Read(context.Background(), jsProt892)
		if err893 != nil {
			Usage()
			return
		}
		value3 := argvalue3
		arg894 := flag.Arg(5)
		mbTrans895 := thrift.NewTMemoryBufferLen(len(arg894))
		defer mbTrans895.Close()
		_, err896 := mbTrans895.WriteString(arg894)
		if err896 != nil {
			Usage()
			return
		}
		factory897 := thrift.NewTJSONProtocolFactory()
		jsProt898 := factory897.GetProtocol(mbTrans895)
		containerStruct4 := heavy.NewHeavyImportGeoTableArgs()
		err899 := containerStruct4.ReadField5(context.Background(), jsProt898)
		if err899 != nil {
			Usage()
			return
		}
		argvalue4 := containerStruct4.RowDesc
		value4 := heavy.TRowDescriptor(argvalue4)
		fmt.Print(client.ImportGeoTable(context.Background(), value0, value1, value2, value3, value4))
		fmt.Print("\n")
		break
	case "import_table_status":
		if flag.NArg() - 1 != 2 {
			fmt.Fprintln(os.Stderr, "ImportTableStatus requires 2 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		fmt.Print(client.ImportTableStatus(context.Background(), value0, value1))
		fmt.Print("\n")
		break
	case "get_first_geo_file_in_archive":
		if flag.NArg() - 1 != 3 {
			fmt.Fprintln(os.Stderr, "GetFirstGeoFileInArchive requires 3 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		arg904 := flag.Arg(3)
		mbTrans905 := thrift.NewTMemoryBufferLen(len(arg904))
		defer mbTrans905.Close()
		_, err906 := mbTrans905.WriteString(arg904)
		if err906 != nil {
			Usage()
			return
		}
		factory907 := thrift.NewTJSONProtocolFactory()
		jsProt908 := factory907.GetProtocol(mbTrans905)
		argvalue2 := heavy.NewTCopyParams()
		err909 := argvalue2.Read(context.Background(), jsProt908)
		if err909 != nil {
			Usage()
			return
		}
		value2 := argvalue2
		fmt.Print(client.GetFirstGeoFileInArchive(context.Background(), value0, value1, value2))
		fmt.Print("\n")
		break
	case "get_all_files_in_archive":
		if flag.NArg() - 1 != 3 {
			fmt.Fprintln(os.Stderr, "GetAllFilesInArchive requires 3 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		arg912 := flag.Arg(3)
		mbTrans913 := thrift.NewTMemoryBufferLen(len(arg912))
		defer mbTrans913.Close()
		_, err914 := mbTrans913.WriteString(arg912)
		if err914 != nil {
			Usage()
			return
		}
		factory915 := thrift.NewTJSONProtocolFactory()
		jsProt916 := factory915.GetProtocol(mbTrans913)
		argvalue2 := heavy.NewTCopyParams()
		err917 := argvalue2.Read(context.Background(), jsProt916)
		if err917 != nil {
			Usage()
			return
		}
		value2 := argvalue2
		fmt.Print(client.GetAllFilesInArchive(context.Background(), value0, value1, value2))
		fmt.Print("\n")
		break
	case "get_layers_in_geo_file":
		if flag.NArg() - 1 != 3 {
			fmt.Fprintln(os.Stderr, "GetLayersInGeoFile requires 3 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		arg920 := flag.Arg(3)
		mbTrans921 := thrift.NewTMemoryBufferLen(len(arg920))
		defer mbTrans921.Close()
		_, err922 := mbTrans921.WriteString(arg920)
		if err922 != nil {
			Usage()
			return
		}
		factory923 := thrift.NewTJSONProtocolFactory()
		jsProt924 := factory923.GetProtocol(mbTrans921)
		argvalue2 := heavy.NewTCopyParams()
		err925 := argvalue2.Read(context.Background(), jsProt924)
		if err925 != nil {
			Usage()
			return
		}
		value2 := argvalue2
		fmt.Print(client.GetLayersInGeoFile(context.Background(), value0, value1, value2))
		fmt.Print("\n")
		break
	case "get_roles":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "GetRoles requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		fmt.Print(client.GetRoles(context.Background(), value0))
		fmt.Print("\n")
		break
	case "get_db_objects_for_grantee":
		if flag.NArg() - 1 != 2 {
			fmt.Fprintln(os.Stderr, "GetDbObjectsForGrantee requires 2 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		fmt.Print(client.GetDbObjectsForGrantee(context.Background(), value0, value1))
		fmt.Print("\n")
		break
	case "get_db_object_privs":
		if flag.NArg() - 1 != 3 {
			fmt.Fprintln(os.Stderr, "GetDbObjectPrivs requires 3 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		tmp2, err := (strconv.Atoi(flag.Arg(3)))
		if err != nil {
			Usage()
			return
		}
		argvalue2 := heavy.TDBObjectType(tmp2)
		value2 := argvalue2
		fmt.Print(client.GetDbObjectPrivs(context.Background(), value0, value1, value2))
		fmt.Print("\n")
		break
	case "get_all_roles_for_user":
		if flag.NArg() - 1 != 2 {
			fmt.Fprintln(os.Stderr, "GetAllRolesForUser requires 2 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		fmt.Print(client.GetAllRolesForUser(context.Background(), value0, value1))
		fmt.Print("\n")
		break
	case "get_all_effective_roles_for_user":
		if flag.NArg() - 1 != 2 {
			fmt.Fprintln(os.Stderr, "GetAllEffectiveRolesForUser requires 2 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		fmt.Print(client.GetAllEffectiveRolesForUser(context.Background(), value0, value1))
		fmt.Print("\n")
		break
	case "has_role":
		if flag.NArg() - 1 != 3 {
			fmt.Fprintln(os.Stderr, "HasRole requires 3 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		argvalue2 := flag.Arg(3)
		value2 := argvalue2
		fmt.Print(client.HasRole(context.Background(), value0, value1, value2))
		fmt.Print("\n")
		break
	case "has_object_privilege":
		if flag.NArg() - 1 != 5 {
			fmt.Fprintln(os.Stderr, "HasObjectPrivilege requires 5 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		argvalue2 := flag.Arg(3)
		value2 := argvalue2
		tmp3, err := (strconv.Atoi(flag.Arg(4)))
		if err != nil {
			Usage()
			return
		}
		argvalue3 := heavy.TDBObjectType(tmp3)
		value3 := argvalue3
		arg941 := flag.Arg(5)
		mbTrans942 := thrift.NewTMemoryBufferLen(len(arg941))
		defer mbTrans942.Close()
		_, err943 := mbTrans942.WriteString(arg941)
		if err943 != nil {
			Usage()
			return
		}
		factory944 := thrift.NewTJSONProtocolFactory()
		jsProt945 := factory944.GetProtocol(mbTrans942)
		argvalue4 := heavy.NewTDBObjectPermissions()
		err946 := argvalue4.Read(context.Background(), jsProt945)
		if err946 != nil {
			Usage()
			return
		}
		value4 := argvalue4
		fmt.Print(client.HasObjectPrivilege(context.Background(), value0, value1, value2, value3, value4))
		fmt.Print("\n")
		break
	case "get_device_parameters":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "GetDeviceParameters requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		fmt.Print(client.GetDeviceParameters(context.Background(), value0))
		fmt.Print("\n")
		break
	case "register_runtime_extension_functions":
		if flag.NArg() - 1 != 4 {
			fmt.Fprintln(os.Stderr, "RegisterRuntimeExtensionFunctions requires 4 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		arg949 := flag.Arg(2)
		mbTrans950 := thrift.NewTMemoryBufferLen(len(arg949))
		defer mbTrans950.Close()
		_, err951 := mbTrans950.WriteString(arg949)
		if err951 != nil {
			Usage()
			return
		}
		factory952 := thrift.NewTJSONProtocolFactory()
		jsProt953 := factory952.GetProtocol(mbTrans950)
		containerStruct1 := heavy.NewHeavyRegisterRuntimeExtensionFunctionsArgs()
		err954 := containerStruct1.ReadField2(context.Background(), jsProt953)
		if err954 != nil {
			Usage()
			return
		}
		argvalue1 := containerStruct1.Udfs
		value1 := argvalue1
		arg955 := flag.Arg(3)
		mbTrans956 := thrift.NewTMemoryBufferLen(len(arg955))
		defer mbTrans956.Close()
		_, err957 := mbTrans956.WriteString(arg955)
		if err957 != nil {
			Usage()
			return
		}
		factory958 := thrift.NewTJSONProtocolFactory()
		jsProt959 := factory958.GetProtocol(mbTrans956)
		containerStruct2 := heavy.NewHeavyRegisterRuntimeExtensionFunctionsArgs()
		err960 := containerStruct2.ReadField3(context.Background(), jsProt959)
		if err960 != nil {
			Usage()
			return
		}
		argvalue2 := containerStruct2.Udtfs
		value2 := argvalue2
		arg961 := flag.Arg(4)
		mbTrans962 := thrift.NewTMemoryBufferLen(len(arg961))
		defer mbTrans962.Close()
		_, err963 := mbTrans962.WriteString(arg961)
		if err963 != nil {
			Usage()
			return
		}
		factory964 := thrift.NewTJSONProtocolFactory()
		jsProt965 := factory964.GetProtocol(mbTrans962)
		containerStruct3 := heavy.NewHeavyRegisterRuntimeExtensionFunctionsArgs()
		err966 := containerStruct3.ReadField4(context.Background(), jsProt965)
		if err966 != nil {
			Usage()
			return
		}
		argvalue3 := containerStruct3.DeviceIrMap
		value3 := argvalue3
		fmt.Print(client.RegisterRuntimeExtensionFunctions(context.Background(), value0, value1, value2, value3))
		fmt.Print("\n")
		break
	case "get_table_function_names":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "GetTableFunctionNames requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		fmt.Print(client.GetTableFunctionNames(context.Background(), value0))
		fmt.Print("\n")
		break
	case "get_runtime_table_function_names":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "GetRuntimeTableFunctionNames requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		fmt.Print(client.GetRuntimeTableFunctionNames(context.Background(), value0))
		fmt.Print("\n")
		break
	case "get_table_function_details":
		if flag.NArg() - 1 != 2 {
			fmt.Fprintln(os.Stderr, "GetTableFunctionDetails requires 2 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		arg970 := flag.Arg(2)
		mbTrans971 := thrift.NewTMemoryBufferLen(len(arg970))
		defer mbTrans971.Close()
		_, err972 := mbTrans971.WriteString(arg970)
		if err972 != nil {
			Usage()
			return
		}
		factory973 := thrift.NewTJSONProtocolFactory()
		jsProt974 := factory973.GetProtocol(mbTrans971)
		containerStruct1 := heavy.NewHeavyGetTableFunctionDetailsArgs()
		err975 := containerStruct1.ReadField2(context.Background(), jsProt974)
		if err975 != nil {
			Usage()
			return
		}
		argvalue1 := containerStruct1.UdtfNames
		value1 := argvalue1
		fmt.Print(client.GetTableFunctionDetails(context.Background(), value0, value1))
		fmt.Print("\n")
		break
	case "get_function_names":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "GetFunctionNames requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		fmt.Print(client.GetFunctionNames(context.Background(), value0))
		fmt.Print("\n")
		break
	case "get_runtime_function_names":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "GetRuntimeFunctionNames requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		fmt.Print(client.GetRuntimeFunctionNames(context.Background(), value0))
		fmt.Print("\n")
		break
	case "get_function_details":
		if flag.NArg() - 1 != 2 {
			fmt.Fprintln(os.Stderr, "GetFunctionDetails requires 2 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		arg979 := flag.Arg(2)
		mbTrans980 := thrift.NewTMemoryBufferLen(len(arg979))
		defer mbTrans980.Close()
		_, err981 := mbTrans980.WriteString(arg979)
		if err981 != nil {
			Usage()
			return
		}
		factory982 := thrift.NewTJSONProtocolFactory()
		jsProt983 := factory982.GetProtocol(mbTrans980)
		containerStruct1 := heavy.NewHeavyGetFunctionDetailsArgs()
		err984 := containerStruct1.ReadField2(context.Background(), jsProt983)
		if err984 != nil {
			Usage()
			return
		}
		argvalue1 := containerStruct1.UdfNames
		value1 := argvalue1
		fmt.Print(client.GetFunctionDetails(context.Background(), value0, value1))
		fmt.Print("\n")
		break
	case "put_immerse_users_metadata":
		if flag.NArg() - 1 != 2 {
			fmt.Fprintln(os.Stderr, "PutImmerseUsersMetadata requires 2 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		arg986 := flag.Arg(2)
		mbTrans987 := thrift.NewTMemoryBufferLen(len(arg986))
		defer mbTrans987.Close()
		_, err988 := mbTrans987.WriteString(arg986)
		if err988 != nil {
			Usage()
			return
		}
		factory989 := thrift.NewTJSONProtocolFactory()
		jsProt990 := factory989.GetProtocol(mbTrans987)
		containerStruct1 := heavy.NewHeavyPutImmerseUsersMetadataArgs()
		err991 := containerStruct1.ReadField2(context.Background(), jsProt990)
		if err991 != nil {
			Usage()
			return
		}
		argvalue1 := containerStruct1.ImmerseUserMetadataList
		value1 := argvalue1
		fmt.Print(client.PutImmerseUsersMetadata(context.Background(), value0, value1))
		fmt.Print("\n")
		break
	case "put_immerse_database_metadata":
		if flag.NArg() - 1 != 3 {
			fmt.Fprintln(os.Stderr, "PutImmerseDatabaseMetadata requires 3 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		argvalue2 := flag.Arg(3)
		value2 := argvalue2
		fmt.Print(client.PutImmerseDatabaseMetadata(context.Background(), value0, value1, value2))
		fmt.Print("\n")
		break
	case "get_users_info":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "GetUsersInfo requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		fmt.Print(client.GetUsersInfo(context.Background(), value0))
		fmt.Print("\n")
		break
	case "get_databases":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "GetDatabases requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		fmt.Print(client.GetDatabases(context.Background(), value0))
		fmt.Print("\n")
		break
	case "":
		Usage()
	default:
		fmt.Fprintln(os.Stderr, "Invalid function ", cmd)
	}
}
