// Code generated by Thrift Compiler (0.23.0). DO NOT EDIT.

package main

import (
	"context"
	"flag"
	"fmt"
	"math"
	"net"
	"net/url"
	"os"
	"strconv"
	"strings"
	thrift "github.com/apache/thrift/lib/go/thrift"
	"github.com/heavyai/webserver/internal/db_thrift_client/common"
	"github.com/heavyai/webserver/internal/db_thrift_client/completion_hints"
	"github.com/heavyai/webserver/internal/db_thrift_client/serialized_result_set"
	"github.com/heavyai/webserver/internal/db_thrift_client/extension_functions"
	"github.com/heavyai/webserver/internal/db_thrift_client/heavy"
)

var _ = common.GoUnusedProtection__
var _ = completion_hints.GoUnusedProtection__
var _ = serialized_result_set.GoUnusedProtection__
var _ = extension_functions.GoUnusedProtection__
var _ = heavy.GoUnusedProtection__

func Usage() {
	fmt.Fprintln(os.Stderr, "Usage of ", os.Args[0], " [-h host:port] [-u url] [-f[ramed]] function [arg1 [arg2...]]:")
	flag.PrintDefaults()
	fmt.Fprintln(os.Stderr, "\nFunctions:")
	fmt.Fprintln(os.Stderr, "  TSessionId connect(string user, string passwd, string dbname)")
	fmt.Fprintln(os.Stderr, "  void disconnect(TSessionId session)")
	fmt.Fprintln(os.Stderr, "  void switch_database(TSessionId session, string dbname)")
	fmt.Fprintln(os.Stderr, "  TSessionId clone_session(TSessionId session)")
	fmt.Fprintln(os.Stderr, "  TServerStatus get_server_status(TSessionId session)")
	fmt.Fprintln(os.Stderr, "   get_status(TSessionId session)")
	fmt.Fprintln(os.Stderr, "  TClusterHardwareInfo get_hardware_info(TSessionId session)")
	fmt.Fprintln(os.Stderr, "   get_tables(TSessionId session)")
	fmt.Fprintln(os.Stderr, "   get_tables_for_database(TSessionId session, string database_name)")
	fmt.Fprintln(os.Stderr, "   get_physical_tables(TSessionId session)")
	fmt.Fprintln(os.Stderr, "   get_views(TSessionId session)")
	fmt.Fprintln(os.Stderr, "   get_tables_meta(TSessionId session)")
	fmt.Fprintln(os.Stderr, "  TTableDetails get_table_details(TSessionId session, string table_name)")
	fmt.Fprintln(os.Stderr, "  TTableDetails get_table_details_for_database(TSessionId session, string table_name, string database_name)")
	fmt.Fprintln(os.Stderr, "  TTableDetails get_internal_table_details(TSessionId session, string table_name, bool include_system_columns)")
	fmt.Fprintln(os.Stderr, "  TTableDetails get_internal_table_details_for_database(TSessionId session, string table_name, string database_name)")
	fmt.Fprintln(os.Stderr, "   get_users(TSessionId session)")
	fmt.Fprintln(os.Stderr, "  string get_version()")
	fmt.Fprintln(os.Stderr, "  void start_heap_profile(TSessionId session)")
	fmt.Fprintln(os.Stderr, "  void stop_heap_profile(TSessionId session)")
	fmt.Fprintln(os.Stderr, "  string get_heap_profile(TSessionId session)")
	fmt.Fprintln(os.Stderr, "   get_memory(TSessionId session, string memory_level)")
	fmt.Fprintln(os.Stderr, "  void clear_cpu_memory(TSessionId session)")
	fmt.Fprintln(os.Stderr, "  void clear_gpu_memory(TSessionId session)")
	fmt.Fprintln(os.Stderr, "  void set_cur_session(TSessionId parent_session, TSessionId leaf_session, string start_time_str, string label, bool for_running_query_kernel)")
	fmt.Fprintln(os.Stderr, "  void invalidate_cur_session(TSessionId parent_session, TSessionId leaf_session, string start_time_str, string label, bool for_running_query_kernel)")
	fmt.Fprintln(os.Stderr, "  void set_table_epoch(TSessionId session, i32 db_id, i32 table_id, i32 new_epoch)")
	fmt.Fprintln(os.Stderr, "  void set_table_epoch_by_name(TSessionId session, string table_name, i32 new_epoch)")
	fmt.Fprintln(os.Stderr, "  i32 get_table_epoch(TSessionId session, i32 db_id, i32 table_id)")
	fmt.Fprintln(os.Stderr, "  i32 get_table_epoch_by_name(TSessionId session, string table_name)")
	fmt.Fprintln(os.Stderr, "   get_table_epochs(TSessionId session, i32 db_id, i32 table_id)")
	fmt.Fprintln(os.Stderr, "  void set_table_epochs(TSessionId session, i32 db_id,  table_epochs)")
	fmt.Fprintln(os.Stderr, "  TSessionInfo get_session_info(TSessionId session)")
	fmt.Fprintln(os.Stderr, "   get_queries_info(TSessionId session)")
	fmt.Fprintln(os.Stderr, "  void set_leaf_info(TSessionId session, TLeafInfo leaf_info)")
	fmt.Fprintln(os.Stderr, "  TQueryResult sql_execute(TSessionId session, string query, bool column_format, string nonce, i32 first_n, i32 at_most_n)")
	fmt.Fprintln(os.Stderr, "  TDataFrame sql_execute_df(TSessionId session, string query, TDeviceType device_type, i32 device_id, i32 first_n, TArrowTransport transport_method)")
	fmt.Fprintln(os.Stderr, "  TDataFrame sql_execute_gdf(TSessionId session, string query, i32 device_id, i32 first_n)")
	fmt.Fprintln(os.Stderr, "  void deallocate_df(TSessionId session, TDataFrame df, TDeviceType device_type, i32 device_id)")
	fmt.Fprintln(os.Stderr, "  void interrupt(TSessionId query_session, TSessionId interrupt_session)")
	fmt.Fprintln(os.Stderr, "  TRowDescriptor sql_validate(TSessionId session, string query)")
	fmt.Fprintln(os.Stderr, "   get_completion_hints(TSessionId session, string sql, i32 cursor)")
	fmt.Fprintln(os.Stderr, "  void set_execution_mode(TSessionId session, TExecuteMode mode)")
	fmt.Fprintln(os.Stderr, "  TRenderResult render_vega(TSessionId session, i64 widget_id, string vega_json, i32 compression_level, string nonce)")
	fmt.Fprintln(os.Stderr, "  TPixelTableRowResult get_result_row_for_pixel(TSessionId session, i64 widget_id, TPixel pixel,  table_col_names, bool column_format, i32 pixelRadius, string nonce)")
	fmt.Fprintln(os.Stderr, "  i32 create_custom_expression(TSessionId session, TCustomExpression custom_expression)")
	fmt.Fprintln(os.Stderr, "   get_custom_expressions(TSessionId session)")
	fmt.Fprintln(os.Stderr, "  void update_custom_expression(TSessionId session, i32 id, string expression_json)")
	fmt.Fprintln(os.Stderr, "  void delete_custom_expressions(TSessionId session,  custom_expression_ids, bool do_soft_delete)")
	fmt.Fprintln(os.Stderr, "  TDashboard get_dashboard(TSessionId session, i32 dashboard_id)")
	fmt.Fprintln(os.Stderr, "   get_dashboards(TSessionId session)")
	fmt.Fprintln(os.Stderr, "  i32 create_dashboard(TSessionId session, string dashboard_name, string dashboard_state, string image_hash, string dashboard_metadata)")
	fmt.Fprintln(os.Stderr, "  void replace_dashboard(TSessionId session, i32 dashboard_id, string dashboard_name, string dashboard_owner, string dashboard_state, string image_hash, string dashboard_metadata)")
	fmt.Fprintln(os.Stderr, "  void delete_dashboard(TSessionId session, i32 dashboard_id)")
	fmt.Fprintln(os.Stderr, "  void share_dashboards(TSessionId session,  dashboard_ids,  groups, TDashboardPermissions permissions)")
	fmt.Fprintln(os.Stderr, "  void delete_dashboards(TSessionId session,  dashboard_ids)")
	fmt.Fprintln(os.Stderr, "  void share_dashboard(TSessionId session, i32 dashboard_id,  groups,  objects, TDashboardPermissions permissions, bool grant_role)")
	fmt.Fprintln(os.Stderr, "  void unshare_dashboard(TSessionId session, i32 dashboard_id,  groups,  objects, TDashboardPermissions permissions)")
	fmt.Fprintln(os.Stderr, "  void unshare_dashboards(TSessionId session,  dashboard_ids,  groups, TDashboardPermissions permissions)")
	fmt.Fprintln(os.Stderr, "   get_dashboard_grantees(TSessionId session, i32 dashboard_id)")
	fmt.Fprintln(os.Stderr, "  TFrontendView get_link_view(TSessionId session, string link)")
	fmt.Fprintln(os.Stderr, "  string create_link(TSessionId session, string view_state, string view_metadata)")
	fmt.Fprintln(os.Stderr, "  void load_table_binary(TSessionId session, string table_name,  rows,  column_names)")
	fmt.Fprintln(os.Stderr, "  void load_table_binary_columnar(TSessionId session, string table_name,  cols,  column_names)")
	fmt.Fprintln(os.Stderr, "  void load_table_binary_arrow(TSessionId session, string table_name, string arrow_stream, bool use_column_names)")
	fmt.Fprintln(os.Stderr, "  void load_table(TSessionId session, string table_name,  rows,  column_names)")
	fmt.Fprintln(os.Stderr, "  TDetectResult detect_column_types(TSessionId session, string file_name, TCopyParams copy_params)")
	fmt.Fprintln(os.Stderr, "  void create_table(TSessionId session, string table_name, TRowDescriptor row_desc, TCreateParams create_params)")
	fmt.Fprintln(os.Stderr, "  void import_table(TSessionId session, string table_name, string file_name, TCopyParams copy_params)")
	fmt.Fprintln(os.Stderr, "  void import_geo_table(TSessionId session, string table_name, string file_name, TCopyParams copy_params, TRowDescriptor row_desc, TCreateParams create_params)")
	fmt.Fprintln(os.Stderr, "  TImportStatus import_table_status(TSessionId session, string import_id)")
	fmt.Fprintln(os.Stderr, "  string get_first_geo_file_in_archive(TSessionId session, string archive_path, TCopyParams copy_params)")
	fmt.Fprintln(os.Stderr, "   get_all_files_in_archive(TSessionId session, string archive_path, TCopyParams copy_params)")
	fmt.Fprintln(os.Stderr, "   get_layers_in_geo_file(TSessionId session, string file_name, TCopyParams copy_params)")
	fmt.Fprintln(os.Stderr, "  i64 query_get_outer_fragment_count(TSessionId session, string query)")
	fmt.Fprintln(os.Stderr, "  TTableMeta check_table_consistency(TSessionId session, i32 table_id)")
	fmt.Fprintln(os.Stderr, "  TPendingQuery start_query(TSessionId leaf_session, TSessionId parent_session, string query_ra, string start_time_str, bool just_explain,  outer_fragment_indices)")
	fmt.Fprintln(os.Stderr, "  TStepResult execute_query_step(TPendingQuery pending_query, TSubqueryId subquery_id, string start_time_str)")
	fmt.Fprintln(os.Stderr, "  void broadcast_serialized_rows(TSerializedRows serialized_rows, TRowDescriptor row_desc, TQueryId query_id, TSubqueryId subquery_id, bool is_final_subquery_result)")
	fmt.Fprintln(os.Stderr, "  TPendingRenderQuery start_render_query(TSessionId session, i64 widget_id, i16 node_idx, string vega_json)")
	fmt.Fprintln(os.Stderr, "  TRenderStepResult execute_next_render_step(TPendingRenderQuery pending_render, TRenderAggDataMap merged_data)")
	fmt.Fprintln(os.Stderr, "  void insert_data(TSessionId session, TInsertData insert_data)")
	fmt.Fprintln(os.Stderr, "  void insert_chunks(TSessionId session, TInsertChunks insert_chunks)")
	fmt.Fprintln(os.Stderr, "  void checkpoint(TSessionId session, i32 table_id)")
	fmt.Fprintln(os.Stderr, "   get_roles(TSessionId session)")
	fmt.Fprintln(os.Stderr, "   get_db_objects_for_grantee(TSessionId session, string roleName)")
	fmt.Fprintln(os.Stderr, "   get_db_object_privs(TSessionId session, string objectName, TDBObjectType type)")
	fmt.Fprintln(os.Stderr, "   get_all_roles_for_user(TSessionId session, string userName)")
	fmt.Fprintln(os.Stderr, "   get_all_effective_roles_for_user(TSessionId session, string userName)")
	fmt.Fprintln(os.Stderr, "  bool has_role(TSessionId session, string granteeName, string roleName)")
	fmt.Fprintln(os.Stderr, "  bool has_object_privilege(TSessionId session, string granteeName, string ObjectName, TDBObjectType objectType, TDBObjectPermissions permissions)")
	fmt.Fprintln(os.Stderr, "   get_device_parameters(TSessionId session)")
	fmt.Fprintln(os.Stderr, "  void register_runtime_extension_functions(TSessionId session,  udfs,  udtfs,  device_ir_map)")
	fmt.Fprintln(os.Stderr, "   get_table_function_names(TSessionId session)")
	fmt.Fprintln(os.Stderr, "   get_runtime_table_function_names(TSessionId session)")
	fmt.Fprintln(os.Stderr, "   get_table_function_details(TSessionId session,  udtf_names)")
	fmt.Fprintln(os.Stderr, "   get_function_names(TSessionId session)")
	fmt.Fprintln(os.Stderr, "   get_runtime_function_names(TSessionId session)")
	fmt.Fprintln(os.Stderr, "   get_function_details(TSessionId session,  udf_names)")
	fmt.Fprintln(os.Stderr, "  void put_immerse_users_metadata(TSessionId session,  immerse_user_metadata_list)")
	fmt.Fprintln(os.Stderr, "  void put_immerse_database_metadata(TSessionId session, string immerse_metadata_json, string database_name)")
	fmt.Fprintln(os.Stderr, "   get_users_info(TSessionId session)")
	fmt.Fprintln(os.Stderr, "   get_databases(TSessionId session)")
	fmt.Fprintln(os.Stderr)
	os.Exit(0)
}

type httpHeaders map[string]string

func (h httpHeaders) String() string {
	var m map[string]string = h
	return fmt.Sprintf("%s", m)
}

func (h httpHeaders) Set(value string) error {
	parts := strings.Split(value, ": ")
	if len(parts) != 2 {
		return fmt.Errorf("header should be of format 'Key: Value'")
	}
	h[parts[0]] = parts[1]
	return nil
}

func main() {
	flag.Usage = Usage
	var host string
	var port int
	var protocol string
	var urlString string
	var framed bool
	var useHttp bool
	headers := make(httpHeaders)
	var parsedUrl *url.URL
	var trans thrift.TTransport
	_ = strconv.Atoi
	_ = math.Abs
	flag.Usage = Usage
	flag.StringVar(&host, "h", "localhost", "Specify host and port")
	flag.IntVar(&port, "p", 9090, "Specify port")
	flag.StringVar(&protocol, "P", "binary", "Specify the protocol (binary, compact, simplejson, json)")
	flag.StringVar(&urlString, "u", "", "Specify the url")
	flag.BoolVar(&framed, "framed", false, "Use framed transport")
	flag.BoolVar(&useHttp, "http", false, "Use http")
	flag.Var(headers, "H", "Headers to set on the http(s) request (e.g. -H \"Key: Value\")")
	flag.Parse()
	
	if len(urlString) > 0 {
		var err error
		parsedUrl, err = url.Parse(urlString)
		if err != nil {
			fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
			flag.Usage()
		}
		host = parsedUrl.Host
		useHttp = len(parsedUrl.Scheme) <= 0 || parsedUrl.Scheme == "http" || parsedUrl.Scheme == "https"
	} else if useHttp {
		_, err := url.Parse(fmt.Sprint("http://", host, ":", port))
		if err != nil {
			fmt.Fprintln(os.Stderr, "Error parsing URL: ", err)
			flag.Usage()
		}
	}
	
	cmd := flag.Arg(0)
	var err error
	var cfg *thrift.TConfiguration = nil
	if useHttp {
		trans, err = thrift.NewTHttpClient(parsedUrl.String())
		if len(headers) > 0 {
			httptrans := trans.(*thrift.THttpClient)
			for key, value := range headers {
				httptrans.SetHeader(key, value)
			}
		}
	} else {
		portStr := fmt.Sprint(port)
		if strings.Contains(host, ":") {
			host, portStr, err = net.SplitHostPort(host)
			if err != nil {
				fmt.Fprintln(os.Stderr, "error with host:", err)
				os.Exit(1)
			}
		}
		trans = thrift.NewTSocketConf(net.JoinHostPort(host, portStr), cfg)
		if err != nil {
			fmt.Fprintln(os.Stderr, "error resolving address:", err)
			os.Exit(1)
		}
		if framed {
			trans = thrift.NewTFramedTransportConf(trans, cfg)
		}
	}
	if err != nil {
		fmt.Fprintln(os.Stderr, "Error creating transport", err)
		os.Exit(1)
	}
	defer trans.Close()
	var protocolFactory thrift.TProtocolFactory
	switch protocol {
	case "compact":
		protocolFactory = thrift.NewTCompactProtocolFactoryConf(cfg)
	case "simplejson":
		protocolFactory = thrift.NewTSimpleJSONProtocolFactoryConf(cfg)
	case "json":
		protocolFactory = thrift.NewTJSONProtocolFactory()
	case "binary", "":
		protocolFactory = thrift.NewTBinaryProtocolFactoryConf(cfg)
	default:
		fmt.Fprintln(os.Stderr, "Invalid protocol specified: ", protocol)
		Usage()
		os.Exit(1)
	}
	iprot := protocolFactory.GetProtocol(trans)
	oprot := protocolFactory.GetProtocol(trans)
	client := heavy.NewHeavyClient(thrift.NewTStandardClient(iprot, oprot))
	if err := trans.Open(); err != nil {
		fmt.Fprintln(os.Stderr, "Error opening socket to ", host, ":", port, " ", err)
		os.Exit(1)
	}
	
	switch cmd {
	case "connect":
		if flag.NArg() - 1 != 3 {
			fmt.Fprintln(os.Stderr, "Connect requires 3 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := argvalue0
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		argvalue2 := flag.Arg(3)
		value2 := argvalue2
		fmt.Print(client.Connect(context.Background(), value0, value1, value2))
		fmt.Print("\n")
		break
	case "disconnect":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "Disconnect requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		fmt.Print(client.Disconnect(context.Background(), value0))
		fmt.Print("\n")
		break
	case "switch_database":
		if flag.NArg() - 1 != 2 {
			fmt.Fprintln(os.Stderr, "SwitchDatabase requires 2 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		fmt.Print(client.SwitchDatabase(context.Background(), value0, value1))
		fmt.Print("\n")
		break
	case "clone_session":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "CloneSession requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		fmt.Print(client.CloneSession(context.Background(), value0))
		fmt.Print("\n")
		break
	case "get_server_status":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "GetServerStatus requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		fmt.Print(client.GetServerStatus(context.Background(), value0))
		fmt.Print("\n")
		break
	case "get_status":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "GetStatus requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		fmt.Print(client.GetStatus(context.Background(), value0))
		fmt.Print("\n")
		break
	case "get_hardware_info":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "GetHardwareInfo requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		fmt.Print(client.GetHardwareInfo(context.Background(), value0))
		fmt.Print("\n")
		break
	case "get_tables":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "GetTables requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		fmt.Print(client.GetTables(context.Background(), value0))
		fmt.Print("\n")
		break
	case "get_tables_for_database":
		if flag.NArg() - 1 != 2 {
			fmt.Fprintln(os.Stderr, "GetTablesForDatabase requires 2 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		fmt.Print(client.GetTablesForDatabase(context.Background(), value0, value1))
		fmt.Print("\n")
		break
	case "get_physical_tables":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "GetPhysicalTables requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		fmt.Print(client.GetPhysicalTables(context.Background(), value0))
		fmt.Print("\n")
		break
	case "get_views":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "GetViews requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		fmt.Print(client.GetViews(context.Background(), value0))
		fmt.Print("\n")
		break
	case "get_tables_meta":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "GetTablesMeta requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		fmt.Print(client.GetTablesMeta(context.Background(), value0))
		fmt.Print("\n")
		break
	case "get_table_details":
		if flag.NArg() - 1 != 2 {
			fmt.Fprintln(os.Stderr, "GetTableDetails requires 2 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		fmt.Print(client.GetTableDetails(context.Background(), value0, value1))
		fmt.Print("\n")
		break
	case "get_table_details_for_database":
		if flag.NArg() - 1 != 3 {
			fmt.Fprintln(os.Stderr, "GetTableDetailsForDatabase requires 3 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		argvalue2 := flag.Arg(3)
		value2 := argvalue2
		fmt.Print(client.GetTableDetailsForDatabase(context.Background(), value0, value1, value2))
		fmt.Print("\n")
		break
	case "get_internal_table_details":
		if flag.NArg() - 1 != 3 {
			fmt.Fprintln(os.Stderr, "GetInternalTableDetails requires 3 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		argvalue2 := flag.Arg(3) == "true"
		value2 := argvalue2
		fmt.Print(client.GetInternalTableDetails(context.Background(), value0, value1, value2))
		fmt.Print("\n")
		break
	case "get_internal_table_details_for_database":
		if flag.NArg() - 1 != 3 {
			fmt.Fprintln(os.Stderr, "GetInternalTableDetailsForDatabase requires 3 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		argvalue2 := flag.Arg(3)
		value2 := argvalue2
		fmt.Print(client.GetInternalTableDetailsForDatabase(context.Background(), value0, value1, value2))
		fmt.Print("\n")
		break
	case "get_users":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "GetUsers requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		fmt.Print(client.GetUsers(context.Background(), value0))
		fmt.Print("\n")
		break
	case "get_version":
		if flag.NArg() - 1 != 0 {
			fmt.Fprintln(os.Stderr, "GetVersion requires 0 args")
			flag.Usage()
		}
		fmt.Print(client.GetVersion(context.Background()))
		fmt.Print("\n")
		break
	case "start_heap_profile":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "StartHeapProfile requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		fmt.Print(client.StartHeapProfile(context.Background(), value0))
		fmt.Print("\n")
		break
	case "stop_heap_profile":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "StopHeapProfile requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		fmt.Print(client.StopHeapProfile(context.Background(), value0))
		fmt.Print("\n")
		break
	case "get_heap_profile":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "GetHeapProfile requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		fmt.Print(client.GetHeapProfile(context.Background(), value0))
		fmt.Print("\n")
		break
	case "get_memory":
		if flag.NArg() - 1 != 2 {
			fmt.Fprintln(os.Stderr, "GetMemory requires 2 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		fmt.Print(client.GetMemory(context.Background(), value0, value1))
		fmt.Print("\n")
		break
	case "clear_cpu_memory":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "ClearCPUMemory requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		fmt.Print(client.ClearCPUMemory(context.Background(), value0))
		fmt.Print("\n")
		break
	case "clear_gpu_memory":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "ClearGpuMemory requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		fmt.Print(client.ClearGpuMemory(context.Background(), value0))
		fmt.Print("\n")
		break
	case "set_cur_session":
		if flag.NArg() - 1 != 5 {
			fmt.Fprintln(os.Stderr, "SetCurSession requires 5 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		argvalue1 := flag.Arg(2)
		value1 := heavy.TSessionId(argvalue1)
		argvalue2 := flag.Arg(3)
		value2 := argvalue2
		argvalue3 := flag.Arg(4)
		value3 := argvalue3
		argvalue4 := flag.Arg(5) == "true"
		value4 := argvalue4
		fmt.Print(client.SetCurSession(context.Background(), value0, value1, value2, value3, value4))
		fmt.Print("\n")
		break
	case "invalidate_cur_session":
		if flag.NArg() - 1 != 5 {
			fmt.Fprintln(os.Stderr, "InvalidateCurSession requires 5 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		argvalue1 := flag.Arg(2)
		value1 := heavy.TSessionId(argvalue1)
		argvalue2 := flag.Arg(3)
		value2 := argvalue2
		argvalue3 := flag.Arg(4)
		value3 := argvalue3
		argvalue4 := flag.Arg(5) == "true"
		value4 := argvalue4
		fmt.Print(client.InvalidateCurSession(context.Background(), value0, value1, value2, value3, value4))
		fmt.Print("\n")
		break
	case "set_table_epoch":
		if flag.NArg() - 1 != 4 {
			fmt.Fprintln(os.Stderr, "SetTableEpoch requires 4 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		tmp1, err739 := (strconv.Atoi(flag.Arg(2)))
		if err739 != nil {
			Usage()
			return
		}
		argvalue1 := int32(tmp1)
		value1 := argvalue1
		tmp2, err740 := (strconv.Atoi(flag.Arg(3)))
		if err740 != nil {
			Usage()
			return
		}
		argvalue2 := int32(tmp2)
		value2 := argvalue2
		tmp3, err741 := (strconv.Atoi(flag.Arg(4)))
		if err741 != nil {
			Usage()
			return
		}
		argvalue3 := int32(tmp3)
		value3 := argvalue3
		fmt.Print(client.SetTableEpoch(context.Background(), value0, value1, value2, value3))
		fmt.Print("\n")
		break
	case "set_table_epoch_by_name":
		if flag.NArg() - 1 != 3 {
			fmt.Fprintln(os.Stderr, "SetTableEpochByName requires 3 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		tmp2, err744 := (strconv.Atoi(flag.Arg(3)))
		if err744 != nil {
			Usage()
			return
		}
		argvalue2 := int32(tmp2)
		value2 := argvalue2
		fmt.Print(client.SetTableEpochByName(context.Background(), value0, value1, value2))
		fmt.Print("\n")
		break
	case "get_table_epoch":
		if flag.NArg() - 1 != 3 {
			fmt.Fprintln(os.Stderr, "GetTableEpoch requires 3 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		tmp1, err746 := (strconv.Atoi(flag.Arg(2)))
		if err746 != nil {
			Usage()
			return
		}
		argvalue1 := int32(tmp1)
		value1 := argvalue1
		tmp2, err747 := (strconv.Atoi(flag.Arg(3)))
		if err747 != nil {
			Usage()
			return
		}
		argvalue2 := int32(tmp2)
		value2 := argvalue2
		fmt.Print(client.GetTableEpoch(context.Background(), value0, value1, value2))
		fmt.Print("\n")
		break
	case "get_table_epoch_by_name":
		if flag.NArg() - 1 != 2 {
			fmt.Fprintln(os.Stderr, "GetTableEpochByName requires 2 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		fmt.Print(client.GetTableEpochByName(context.Background(), value0, value1))
		fmt.Print("\n")
		break
	case "get_table_epochs":
		if flag.NArg() - 1 != 3 {
			fmt.Fprintln(os.Stderr, "GetTableEpochs requires 3 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		tmp1, err751 := (strconv.Atoi(flag.Arg(2)))
		if err751 != nil {
			Usage()
			return
		}
		argvalue1 := int32(tmp1)
		value1 := argvalue1
		tmp2, err752 := (strconv.Atoi(flag.Arg(3)))
		if err752 != nil {
			Usage()
			return
		}
		argvalue2 := int32(tmp2)
		value2 := argvalue2
		fmt.Print(client.GetTableEpochs(context.Background(), value0, value1, value2))
		fmt.Print("\n")
		break
	case "set_table_epochs":
		if flag.NArg() - 1 != 3 {
			fmt.Fprintln(os.Stderr, "SetTableEpochs requires 3 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		tmp1, err754 := (strconv.Atoi(flag.Arg(2)))
		if err754 != nil {
			Usage()
			return
		}
		argvalue1 := int32(tmp1)
		value1 := argvalue1
		arg755 := flag.Arg(3)
		mbTrans756 := thrift.NewTMemoryBufferLen(len(arg755))
		defer mbTrans756.Close()
		_, err757 := mbTrans756.WriteString(arg755)
		if err757 != nil {
			Usage()
			return
		}
		factory758 := thrift.NewTJSONProtocolFactory()
		jsProt759 := factory758.GetProtocol(mbTrans756)
		containerStruct2 := heavy.NewHeavySetTableEpochsArgs()
		err760 := containerStruct2.ReadField3(context.Background(), jsProt759)
		if err760 != nil {
			Usage()
			return
		}
		argvalue2 := containerStruct2.TableEpochs
		value2 := argvalue2
		fmt.Print(client.SetTableEpochs(context.Background(), value0, value1, value2))
		fmt.Print("\n")
		break
	case "get_session_info":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "GetSessionInfo requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		fmt.Print(client.GetSessionInfo(context.Background(), value0))
		fmt.Print("\n")
		break
	case "get_queries_info":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "GetQueriesInfo requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		fmt.Print(client.GetQueriesInfo(context.Background(), value0))
		fmt.Print("\n")
		break
	case "set_leaf_info":
		if flag.NArg() - 1 != 2 {
			fmt.Fprintln(os.Stderr, "SetLeafInfo requires 2 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		arg764 := flag.Arg(2)
		mbTrans765 := thrift.NewTMemoryBufferLen(len(arg764))
		defer mbTrans765.Close()
		_, err766 := mbTrans765.WriteString(arg764)
		if err766 != nil {
			Usage()
			return
		}
		factory767 := thrift.NewTJSONProtocolFactory()
		jsProt768 := factory767.GetProtocol(mbTrans765)
		argvalue1 := heavy.NewTLeafInfo()
		err769 := argvalue1.Read(context.Background(), jsProt768)
		if err769 != nil {
			Usage()
			return
		}
		value1 := argvalue1
		fmt.Print(client.SetLeafInfo(context.Background(), value0, value1))
		fmt.Print("\n")
		break
	case "sql_execute":
		if flag.NArg() - 1 != 6 {
			fmt.Fprintln(os.Stderr, "SqlExecute requires 6 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		argvalue2 := flag.Arg(3) == "true"
		value2 := argvalue2
		argvalue3 := flag.Arg(4)
		value3 := argvalue3
		tmp4, err774 := (strconv.Atoi(flag.Arg(5)))
		if err774 != nil {
			Usage()
			return
		}
		argvalue4 := int32(tmp4)
		value4 := argvalue4
		tmp5, err775 := (strconv.Atoi(flag.Arg(6)))
		if err775 != nil {
			Usage()
			return
		}
		argvalue5 := int32(tmp5)
		value5 := argvalue5
		fmt.Print(client.SqlExecute(context.Background(), value0, value1, value2, value3, value4, value5))
		fmt.Print("\n")
		break
	case "sql_execute_df":
		if flag.NArg() - 1 != 6 {
			fmt.Fprintln(os.Stderr, "SqlExecuteDf requires 6 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		tmp2, err := (strconv.Atoi(flag.Arg(3)))
		if err != nil {
			Usage()
			return
		}
		argvalue2 := heavy.TDeviceType(tmp2)
		value2 := argvalue2
		tmp3, err778 := (strconv.Atoi(flag.Arg(4)))
		if err778 != nil {
			Usage()
			return
		}
		argvalue3 := int32(tmp3)
		value3 := argvalue3
		tmp4, err779 := (strconv.Atoi(flag.Arg(5)))
		if err779 != nil {
			Usage()
			return
		}
		argvalue4 := int32(tmp4)
		value4 := argvalue4
		tmp5, err := (strconv.Atoi(flag.Arg(6)))
		if err != nil {
			Usage()
			return
		}
		argvalue5 := heavy.TArrowTransport(tmp5)
		value5 := argvalue5
		fmt.Print(client.SqlExecuteDf(context.Background(), value0, value1, value2, value3, value4, value5))
		fmt.Print("\n")
		break
	case "sql_execute_gdf":
		if flag.NArg() - 1 != 4 {
			fmt.Fprintln(os.Stderr, "SqlExecuteGdf requires 4 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		tmp2, err782 := (strconv.Atoi(flag.Arg(3)))
		if err782 != nil {
			Usage()
			return
		}
		argvalue2 := int32(tmp2)
		value2 := argvalue2
		tmp3, err783 := (strconv.Atoi(flag.Arg(4)))
		if err783 != nil {
			Usage()
			return
		}
		argvalue3 := int32(tmp3)
		value3 := argvalue3
		fmt.Print(client.SqlExecuteGdf(context.Background(), value0, value1, value2, value3))
		fmt.Print("\n")
		break
	case "deallocate_df":
		if flag.NArg() - 1 != 4 {
			fmt.Fprintln(os.Stderr, "DeallocateDf requires 4 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		arg785 := flag.Arg(2)
		mbTrans786 := thrift.NewTMemoryBufferLen(len(arg785))
		defer mbTrans786.Close()
		_, err787 := mbTrans786.WriteString(arg785)
		if err787 != nil {
			Usage()
			return
		}
		factory788 := thrift.NewTJSONProtocolFactory()
		jsProt789 := factory788.GetProtocol(mbTrans786)
		argvalue1 := heavy.NewTDataFrame()
		err790 := argvalue1.Read(context.Background(), jsProt789)
		if err790 != nil {
			Usage()
			return
		}
		value1 := argvalue1
		tmp2, err := (strconv.Atoi(flag.Arg(3)))
		if err != nil {
			Usage()
			return
		}
		argvalue2 := heavy.TDeviceType(tmp2)
		value2 := argvalue2
		tmp3, err791 := (strconv.Atoi(flag.Arg(4)))
		if err791 != nil {
			Usage()
			return
		}
		argvalue3 := int32(tmp3)
		value3 := argvalue3
		fmt.Print(client.DeallocateDf(context.Background(), value0, value1, value2, value3))
		fmt.Print("\n")
		break
	case "interrupt":
		if flag.NArg() - 1 != 2 {
			fmt.Fprintln(os.Stderr, "Interrupt requires 2 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		argvalue1 := flag.Arg(2)
		value1 := heavy.TSessionId(argvalue1)
		fmt.Print(client.Interrupt(context.Background(), value0, value1))
		fmt.Print("\n")
		break
	case "sql_validate":
		if flag.NArg() - 1 != 2 {
			fmt.Fprintln(os.Stderr, "SqlValidate requires 2 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		fmt.Print(client.SqlValidate(context.Background(), value0, value1))
		fmt.Print("\n")
		break
	case "get_completion_hints":
		if flag.NArg() - 1 != 3 {
			fmt.Fprintln(os.Stderr, "GetCompletionHints requires 3 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		tmp2, err798 := (strconv.Atoi(flag.Arg(3)))
		if err798 != nil {
			Usage()
			return
		}
		argvalue2 := int32(tmp2)
		value2 := argvalue2
		fmt.Print(client.GetCompletionHints(context.Background(), value0, value1, value2))
		fmt.Print("\n")
		break
	case "set_execution_mode":
		if flag.NArg() - 1 != 2 {
			fmt.Fprintln(os.Stderr, "SetExecutionMode requires 2 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		tmp1, err := (strconv.Atoi(flag.Arg(2)))
		if err != nil {
			Usage()
			return
		}
		argvalue1 := heavy.TExecuteMode(tmp1)
		value1 := argvalue1
		fmt.Print(client.SetExecutionMode(context.Background(), value0, value1))
		fmt.Print("\n")
		break
	case "render_vega":
		if flag.NArg() - 1 != 5 {
			fmt.Fprintln(os.Stderr, "RenderVega requires 5 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		argvalue1, err801 := (strconv.ParseInt(flag.Arg(2), 10, 64))
		if err801 != nil {
			Usage()
			return
		}
		value1 := argvalue1
		argvalue2 := flag.Arg(3)
		value2 := argvalue2
		tmp3, err803 := (strconv.Atoi(flag.Arg(4)))
		if err803 != nil {
			Usage()
			return
		}
		argvalue3 := int32(tmp3)
		value3 := argvalue3
		argvalue4 := flag.Arg(5)
		value4 := argvalue4
		fmt.Print(client.RenderVega(context.Background(), value0, value1, value2, value3, value4))
		fmt.Print("\n")
		break
	case "get_result_row_for_pixel":
		if flag.NArg() - 1 != 7 {
			fmt.Fprintln(os.Stderr, "GetResultRowForPixel requires 7 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		argvalue1, err806 := (strconv.ParseInt(flag.Arg(2), 10, 64))
		if err806 != nil {
			Usage()
			return
		}
		value1 := argvalue1
		arg807 := flag.Arg(3)
		mbTrans808 := thrift.NewTMemoryBufferLen(len(arg807))
		defer mbTrans808.Close()
		_, err809 := mbTrans808.WriteString(arg807)
		if err809 != nil {
			Usage()
			return
		}
		factory810 := thrift.NewTJSONProtocolFactory()
		jsProt811 := factory810.GetProtocol(mbTrans808)
		argvalue2 := heavy.NewTPixel()
		err812 := argvalue2.Read(context.Background(), jsProt811)
		if err812 != nil {
			Usage()
			return
		}
		value2 := argvalue2
		arg813 := flag.Arg(4)
		mbTrans814 := thrift.NewTMemoryBufferLen(len(arg813))
		defer mbTrans814.Close()
		_, err815 := mbTrans814.WriteString(arg813)
		if err815 != nil {
			Usage()
			return
		}
		factory816 := thrift.NewTJSONProtocolFactory()
		jsProt817 := factory816.GetProtocol(mbTrans814)
		containerStruct3 := heavy.NewHeavyGetResultRowForPixelArgs()
		err818 := containerStruct3.ReadField4(context.Background(), jsProt817)
		if err818 != nil {
			Usage()
			return
		}
		argvalue3 := containerStruct3.TableColNames
		value3 := argvalue3
		argvalue4 := flag.Arg(5) == "true"
		value4 := argvalue4
		tmp5, err820 := (strconv.Atoi(flag.Arg(6)))
		if err820 != nil {
			Usage()
			return
		}
		argvalue5 := int32(tmp5)
		value5 := argvalue5
		argvalue6 := flag.Arg(7)
		value6 := argvalue6
		fmt.Print(client.GetResultRowForPixel(context.Background(), value0, value1, value2, value3, value4, value5, value6))
		fmt.Print("\n")
		break
	case "create_custom_expression":
		if flag.NArg() - 1 != 2 {
			fmt.Fprintln(os.Stderr, "CreateCustomExpression requires 2 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		arg823 := flag.Arg(2)
		mbTrans824 := thrift.NewTMemoryBufferLen(len(arg823))
		defer mbTrans824.Close()
		_, err825 := mbTrans824.WriteString(arg823)
		if err825 != nil {
			Usage()
			return
		}
		factory826 := thrift.NewTJSONProtocolFactory()
		jsProt827 := factory826.GetProtocol(mbTrans824)
		argvalue1 := heavy.NewTCustomExpression()
		err828 := argvalue1.Read(context.Background(), jsProt827)
		if err828 != nil {
			Usage()
			return
		}
		value1 := argvalue1
		fmt.Print(client.CreateCustomExpression(context.Background(), value0, value1))
		fmt.Print("\n")
		break
	case "get_custom_expressions":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "GetCustomExpressions requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		fmt.Print(client.GetCustomExpressions(context.Background(), value0))
		fmt.Print("\n")
		break
	case "update_custom_expression":
		if flag.NArg() - 1 != 3 {
			fmt.Fprintln(os.Stderr, "UpdateCustomExpression requires 3 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		tmp1, err831 := (strconv.Atoi(flag.Arg(2)))
		if err831 != nil {
			Usage()
			return
		}
		argvalue1 := int32(tmp1)
		value1 := argvalue1
		argvalue2 := flag.Arg(3)
		value2 := argvalue2
		fmt.Print(client.UpdateCustomExpression(context.Background(), value0, value1, value2))
		fmt.Print("\n")
		break
	case "delete_custom_expressions":
		if flag.NArg() - 1 != 3 {
			fmt.Fprintln(os.Stderr, "DeleteCustomExpressions requires 3 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		arg834 := flag.Arg(2)
		mbTrans835 := thrift.NewTMemoryBufferLen(len(arg834))
		defer mbTrans835.Close()
		_, err836 := mbTrans835.WriteString(arg834)
		if err836 != nil {
			Usage()
			return
		}
		factory837 := thrift.NewTJSONProtocolFactory()
		jsProt838 := factory837.GetProtocol(mbTrans835)
		containerStruct1 := heavy.NewHeavyDeleteCustomExpressionsArgs()
		err839 := containerStruct1.ReadField2(context.Background(), jsProt838)
		if err839 != nil {
			Usage()
			return
		}
		argvalue1 := containerStruct1.CustomExpressionIds
		value1 := argvalue1
		argvalue2 := flag.Arg(3) == "true"
		value2 := argvalue2
		fmt.Print(client.DeleteCustomExpressions(context.Background(), value0, value1, value2))
		fmt.Print("\n")
		break
	case "get_dashboard":
		if flag.NArg() - 1 != 2 {
			fmt.Fprintln(os.Stderr, "GetDashboard requires 2 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		tmp1, err842 := (strconv.Atoi(flag.Arg(2)))
		if err842 != nil {
			Usage()
			return
		}
		argvalue1 := int32(tmp1)
		value1 := argvalue1
		fmt.Print(client.GetDashboard(context.Background(), value0, value1))
		fmt.Print("\n")
		break
	case "get_dashboards":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "GetDashboards requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		fmt.Print(client.GetDashboards(context.Background(), value0))
		fmt.Print("\n")
		break
	case "create_dashboard":
		if flag.NArg() - 1 != 5 {
			fmt.Fprintln(os.Stderr, "CreateDashboard requires 5 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		argvalue2 := flag.Arg(3)
		value2 := argvalue2
		argvalue3 := flag.Arg(4)
		value3 := argvalue3
		argvalue4 := flag.Arg(5)
		value4 := argvalue4
		fmt.Print(client.CreateDashboard(context.Background(), value0, value1, value2, value3, value4))
		fmt.Print("\n")
		break
	case "replace_dashboard":
		if flag.NArg() - 1 != 7 {
			fmt.Fprintln(os.Stderr, "ReplaceDashboard requires 7 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		tmp1, err850 := (strconv.Atoi(flag.Arg(2)))
		if err850 != nil {
			Usage()
			return
		}
		argvalue1 := int32(tmp1)
		value1 := argvalue1
		argvalue2 := flag.Arg(3)
		value2 := argvalue2
		argvalue3 := flag.Arg(4)
		value3 := argvalue3
		argvalue4 := flag.Arg(5)
		value4 := argvalue4
		argvalue5 := flag.Arg(6)
		value5 := argvalue5
		argvalue6 := flag.Arg(7)
		value6 := argvalue6
		fmt.Print(client.ReplaceDashboard(context.Background(), value0, value1, value2, value3, value4, value5, value6))
		fmt.Print("\n")
		break
	case "delete_dashboard":
		if flag.NArg() - 1 != 2 {
			fmt.Fprintln(os.Stderr, "DeleteDashboard requires 2 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		tmp1, err857 := (strconv.Atoi(flag.Arg(2)))
		if err857 != nil {
			Usage()
			return
		}
		argvalue1 := int32(tmp1)
		value1 := argvalue1
		fmt.Print(client.DeleteDashboard(context.Background(), value0, value1))
		fmt.Print("\n")
		break
	case "share_dashboards":
		if flag.NArg() - 1 != 4 {
			fmt.Fprintln(os.Stderr, "ShareDashboards requires 4 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		arg859 := flag.Arg(2)
		mbTrans860 := thrift.NewTMemoryBufferLen(len(arg859))
		defer mbTrans860.Close()
		_, err861 := mbTrans860.WriteString(arg859)
		if err861 != nil {
			Usage()
			return
		}
		factory862 := thrift.NewTJSONProtocolFactory()
		jsProt863 := factory862.GetProtocol(mbTrans860)
		containerStruct1 := heavy.NewHeavyShareDashboardsArgs()
		err864 := containerStruct1.ReadField2(context.Background(), jsProt863)
		if err864 != nil {
			Usage()
			return
		}
		argvalue1 := containerStruct1.DashboardIds
		value1 := argvalue1
		arg865 := flag.Arg(3)
		mbTrans866 := thrift.NewTMemoryBufferLen(len(arg865))
		defer mbTrans866.Close()
		_, err867 := mbTrans866.WriteString(arg865)
		if err867 != nil {
			Usage()
			return
		}
		factory868 := thrift.NewTJSONProtocolFactory()
		jsProt869 := factory868.GetProtocol(mbTrans866)
		containerStruct2 := heavy.NewHeavyShareDashboardsArgs()
		err870 := containerStruct2.ReadField3(context.Background(), jsProt869)
		if err870 != nil {
			Usage()
			return
		}
		argvalue2 := containerStruct2.Groups
		value2 := argvalue2
		arg871 := flag.Arg(4)
		mbTrans872 := thrift.NewTMemoryBufferLen(len(arg871))
		defer mbTrans872.Close()
		_, err873 := mbTrans872.WriteString(arg871)
		if err873 != nil {
			Usage()
			return
		}
		factory874 := thrift.NewTJSONProtocolFactory()
		jsProt875 := factory874.GetProtocol(mbTrans872)
		argvalue3 := heavy.NewTDashboardPermissions()
		err876 := argvalue3.Read(context.Background(), jsProt875)
		if err876 != nil {
			Usage()
			return
		}
		value3 := argvalue3
		fmt.Print(client.ShareDashboards(context.Background(), value0, value1, value2, value3))
		fmt.Print("\n")
		break
	case "delete_dashboards":
		if flag.NArg() - 1 != 2 {
			fmt.Fprintln(os.Stderr, "DeleteDashboards requires 2 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		arg878 := flag.Arg(2)
		mbTrans879 := thrift.NewTMemoryBufferLen(len(arg878))
		defer mbTrans879.Close()
		_, err880 := mbTrans879.WriteString(arg878)
		if err880 != nil {
			Usage()
			return
		}
		factory881 := thrift.NewTJSONProtocolFactory()
		jsProt882 := factory881.GetProtocol(mbTrans879)
		containerStruct1 := heavy.NewHeavyDeleteDashboardsArgs()
		err883 := containerStruct1.ReadField2(context.Background(), jsProt882)
		if err883 != nil {
			Usage()
			return
		}
		argvalue1 := containerStruct1.DashboardIds
		value1 := argvalue1
		fmt.Print(client.DeleteDashboards(context.Background(), value0, value1))
		fmt.Print("\n")
		break
	case "share_dashboard":
		if flag.NArg() - 1 != 6 {
			fmt.Fprintln(os.Stderr, "ShareDashboard requires 6 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		tmp1, err885 := (strconv.Atoi(flag.Arg(2)))
		if err885 != nil {
			Usage()
			return
		}
		argvalue1 := int32(tmp1)
		value1 := argvalue1
		arg886 := flag.Arg(3)
		mbTrans887 := thrift.NewTMemoryBufferLen(len(arg886))
		defer mbTrans887.Close()
		_, err888 := mbTrans887.WriteString(arg886)
		if err888 != nil {
			Usage()
			return
		}
		factory889 := thrift.NewTJSONProtocolFactory()
		jsProt890 := factory889.GetProtocol(mbTrans887)
		containerStruct2 := heavy.NewHeavyShareDashboardArgs()
		err891 := containerStruct2.ReadField3(context.Background(), jsProt890)
		if err891 != nil {
			Usage()
			return
		}
		argvalue2 := containerStruct2.Groups
		value2 := argvalue2
		arg892 := flag.Arg(4)
		mbTrans893 := thrift.NewTMemoryBufferLen(len(arg892))
		defer mbTrans893.Close()
		_, err894 := mbTrans893.WriteString(arg892)
		if err894 != nil {
			Usage()
			return
		}
		factory895 := thrift.NewTJSONProtocolFactory()
		jsProt896 := factory895.GetProtocol(mbTrans893)
		containerStruct3 := heavy.NewHeavyShareDashboardArgs()
		err897 := containerStruct3.ReadField4(context.Background(), jsProt896)
		if err897 != nil {
			Usage()
			return
		}
		argvalue3 := containerStruct3.Objects
		value3 := argvalue3
		arg898 := flag.Arg(5)
		mbTrans899 := thrift.NewTMemoryBufferLen(len(arg898))
		defer mbTrans899.Close()
		_, err900 := mbTrans899.WriteString(arg898)
		if err900 != nil {
			Usage()
			return
		}
		factory901 := thrift.NewTJSONProtocolFactory()
		jsProt902 := factory901.GetProtocol(mbTrans899)
		argvalue4 := heavy.NewTDashboardPermissions()
		err903 := argvalue4.Read(context.Background(), jsProt902)
		if err903 != nil {
			Usage()
			return
		}
		value4 := argvalue4
		argvalue5 := flag.Arg(6) == "true"
		value5 := argvalue5
		fmt.Print(client.ShareDashboard(context.Background(), value0, value1, value2, value3, value4, value5))
		fmt.Print("\n")
		break
	case "unshare_dashboard":
		if flag.NArg() - 1 != 5 {
			fmt.Fprintln(os.Stderr, "UnshareDashboard requires 5 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		tmp1, err906 := (strconv.Atoi(flag.Arg(2)))
		if err906 != nil {
			Usage()
			return
		}
		argvalue1 := int32(tmp1)
		value1 := argvalue1
		arg907 := flag.Arg(3)
		mbTrans908 := thrift.NewTMemoryBufferLen(len(arg907))
		defer mbTrans908.Close()
		_, err909 := mbTrans908.WriteString(arg907)
		if err909 != nil {
			Usage()
			return
		}
		factory910 := thrift.NewTJSONProtocolFactory()
		jsProt911 := factory910.GetProtocol(mbTrans908)
		containerStruct2 := heavy.NewHeavyUnshareDashboardArgs()
		err912 := containerStruct2.ReadField3(context.Background(), jsProt911)
		if err912 != nil {
			Usage()
			return
		}
		argvalue2 := containerStruct2.Groups
		value2 := argvalue2
		arg913 := flag.Arg(4)
		mbTrans914 := thrift.NewTMemoryBufferLen(len(arg913))
		defer mbTrans914.Close()
		_, err915 := mbTrans914.WriteString(arg913)
		if err915 != nil {
			Usage()
			return
		}
		factory916 := thrift.NewTJSONProtocolFactory()
		jsProt917 := factory916.GetProtocol(mbTrans914)
		containerStruct3 := heavy.NewHeavyUnshareDashboardArgs()
		err918 := containerStruct3.ReadField4(context.Background(), jsProt917)
		if err918 != nil {
			Usage()
			return
		}
		argvalue3 := containerStruct3.Objects
		value3 := argvalue3
		arg919 := flag.Arg(5)
		mbTrans920 := thrift.NewTMemoryBufferLen(len(arg919))
		defer mbTrans920.Close()
		_, err921 := mbTrans920.WriteString(arg919)
		if err921 != nil {
			Usage()
			return
		}
		factory922 := thrift.NewTJSONProtocolFactory()
		jsProt923 := factory922.GetProtocol(mbTrans920)
		argvalue4 := heavy.NewTDashboardPermissions()
		err924 := argvalue4.Read(context.Background(), jsProt923)
		if err924 != nil {
			Usage()
			return
		}
		value4 := argvalue4
		fmt.Print(client.UnshareDashboard(context.Background(), value0, value1, value2, value3, value4))
		fmt.Print("\n")
		break
	case "unshare_dashboards":
		if flag.NArg() - 1 != 4 {
			fmt.Fprintln(os.Stderr, "UnshareDashboards requires 4 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		arg926 := flag.Arg(2)
		mbTrans927 := thrift.NewTMemoryBufferLen(len(arg926))
		defer mbTrans927.Close()
		_, err928 := mbTrans927.WriteString(arg926)
		if err928 != nil {
			Usage()
			return
		}
		factory929 := thrift.NewTJSONProtocolFactory()
		jsProt930 := factory929.GetProtocol(mbTrans927)
		containerStruct1 := heavy.NewHeavyUnshareDashboardsArgs()
		err931 := containerStruct1.ReadField2(context.Background(), jsProt930)
		if err931 != nil {
			Usage()
			return
		}
		argvalue1 := containerStruct1.DashboardIds
		value1 := argvalue1
		arg932 := flag.Arg(3)
		mbTrans933 := thrift.NewTMemoryBufferLen(len(arg932))
		defer mbTrans933.Close()
		_, err934 := mbTrans933.WriteString(arg932)
		if err934 != nil {
			Usage()
			return
		}
		factory935 := thrift.NewTJSONProtocolFactory()
		jsProt936 := factory935.GetProtocol(mbTrans933)
		containerStruct2 := heavy.NewHeavyUnshareDashboardsArgs()
		err937 := containerStruct2.ReadField3(context.Background(), jsProt936)
		if err937 != nil {
			Usage()
			return
		}
		argvalue2 := containerStruct2.Groups
		value2 := argvalue2
		arg938 := flag.Arg(4)
		mbTrans939 := thrift.NewTMemoryBufferLen(len(arg938))
		defer mbTrans939.Close()
		_, err940 := mbTrans939.WriteString(arg938)
		if err940 != nil {
			Usage()
			return
		}
		factory941 := thrift.NewTJSONProtocolFactory()
		jsProt942 := factory941.GetProtocol(mbTrans939)
		argvalue3 := heavy.NewTDashboardPermissions()
		err943 := argvalue3.Read(context.Background(), jsProt942)
		if err943 != nil {
			Usage()
			return
		}
		value3 := argvalue3
		fmt.Print(client.UnshareDashboards(context.Background(), value0, value1, value2, value3))
		fmt.Print("\n")
		break
	case "get_dashboard_grantees":
		if flag.NArg() - 1 != 2 {
			fmt.Fprintln(os.Stderr, "GetDashboardGrantees requires 2 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		tmp1, err945 := (strconv.Atoi(flag.Arg(2)))
		if err945 != nil {
			Usage()
			return
		}
		argvalue1 := int32(tmp1)
		value1 := argvalue1
		fmt.Print(client.GetDashboardGrantees(context.Background(), value0, value1))
		fmt.Print("\n")
		break
	case "get_link_view":
		if flag.NArg() - 1 != 2 {
			fmt.Fprintln(os.Stderr, "GetLinkView requires 2 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		fmt.Print(client.GetLinkView(context.Background(), value0, value1))
		fmt.Print("\n")
		break
	case "create_link":
		if flag.NArg() - 1 != 3 {
			fmt.Fprintln(os.Stderr, "CreateLink requires 3 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		argvalue2 := flag.Arg(3)
		value2 := argvalue2
		fmt.Print(client.CreateLink(context.Background(), value0, value1, value2))
		fmt.Print("\n")
		break
	case "load_table_binary":
		if flag.NArg() - 1 != 4 {
			fmt.Fprintln(os.Stderr, "LoadTableBinary requires 4 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		arg953 := flag.Arg(3)
		mbTrans954 := thrift.NewTMemoryBufferLen(len(arg953))
		defer mbTrans954.Close()
		_, err955 := mbTrans954.WriteString(arg953)
		if err955 != nil {
			Usage()
			return
		}
		factory956 := thrift.NewTJSONProtocolFactory()
		jsProt957 := factory956.GetProtocol(mbTrans954)
		containerStruct2 := heavy.NewHeavyLoadTableBinaryArgs()
		err958 := containerStruct2.ReadField3(context.Background(), jsProt957)
		if err958 != nil {
			Usage()
			return
		}
		argvalue2 := containerStruct2.Rows
		value2 := argvalue2
		arg959 := flag.Arg(4)
		mbTrans960 := thrift.NewTMemoryBufferLen(len(arg959))
		defer mbTrans960.Close()
		_, err961 := mbTrans960.WriteString(arg959)
		if err961 != nil {
			Usage()
			return
		}
		factory962 := thrift.NewTJSONProtocolFactory()
		jsProt963 := factory962.GetProtocol(mbTrans960)
		containerStruct3 := heavy.NewHeavyLoadTableBinaryArgs()
		err964 := containerStruct3.ReadField4(context.Background(), jsProt963)
		if err964 != nil {
			Usage()
			return
		}
		argvalue3 := containerStruct3.ColumnNames
		value3 := argvalue3
		fmt.Print(client.LoadTableBinary(context.Background(), value0, value1, value2, value3))
		fmt.Print("\n")
		break
	case "load_table_binary_columnar":
		if flag.NArg() - 1 != 4 {
			fmt.Fprintln(os.Stderr, "LoadTableBinaryColumnar requires 4 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		arg967 := flag.Arg(3)
		mbTrans968 := thrift.NewTMemoryBufferLen(len(arg967))
		defer mbTrans968.Close()
		_, err969 := mbTrans968.WriteString(arg967)
		if err969 != nil {
			Usage()
			return
		}
		factory970 := thrift.NewTJSONProtocolFactory()
		jsProt971 := factory970.GetProtocol(mbTrans968)
		containerStruct2 := heavy.NewHeavyLoadTableBinaryColumnarArgs()
		err972 := containerStruct2.ReadField3(context.Background(), jsProt971)
		if err972 != nil {
			Usage()
			return
		}
		argvalue2 := containerStruct2.Cols
		value2 := argvalue2
		arg973 := flag.Arg(4)
		mbTrans974 := thrift.NewTMemoryBufferLen(len(arg973))
		defer mbTrans974.Close()
		_, err975 := mbTrans974.WriteString(arg973)
		if err975 != nil {
			Usage()
			return
		}
		factory976 := thrift.NewTJSONProtocolFactory()
		jsProt977 := factory976.GetProtocol(mbTrans974)
		containerStruct3 := heavy.NewHeavyLoadTableBinaryColumnarArgs()
		err978 := containerStruct3.ReadField4(context.Background(), jsProt977)
		if err978 != nil {
			Usage()
			return
		}
		argvalue3 := containerStruct3.ColumnNames
		value3 := argvalue3
		fmt.Print(client.LoadTableBinaryColumnar(context.Background(), value0, value1, value2, value3))
		fmt.Print("\n")
		break
	case "load_table_binary_arrow":
		if flag.NArg() - 1 != 4 {
			fmt.Fprintln(os.Stderr, "LoadTableBinaryArrow requires 4 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		argvalue2 := []byte(flag.Arg(3))
		value2 := argvalue2
		argvalue3 := flag.Arg(4) == "true"
		value3 := argvalue3
		fmt.Print(client.LoadTableBinaryArrow(context.Background(), value0, value1, value2, value3))
		fmt.Print("\n")
		break
	case "load_table":
		if flag.NArg() - 1 != 4 {
			fmt.Fprintln(os.Stderr, "LoadTable requires 4 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		arg985 := flag.Arg(3)
		mbTrans986 := thrift.NewTMemoryBufferLen(len(arg985))
		defer mbTrans986.Close()
		_, err987 := mbTrans986.WriteString(arg985)
		if err987 != nil {
			Usage()
			return
		}
		factory988 := thrift.NewTJSONProtocolFactory()
		jsProt989 := factory988.GetProtocol(mbTrans986)
		containerStruct2 := heavy.NewHeavyLoadTableArgs()
		err990 := containerStruct2.ReadField3(context.Background(), jsProt989)
		if err990 != nil {
			Usage()
			return
		}
		argvalue2 := containerStruct2.Rows
		value2 := argvalue2
		arg991 := flag.Arg(4)
		mbTrans992 := thrift.NewTMemoryBufferLen(len(arg991))
		defer mbTrans992.Close()
		_, err993 := mbTrans992.WriteString(arg991)
		if err993 != nil {
			Usage()
			return
		}
		factory994 := thrift.NewTJSONProtocolFactory()
		jsProt995 := factory994.GetProtocol(mbTrans992)
		containerStruct3 := heavy.NewHeavyLoadTableArgs()
		err996 := containerStruct3.ReadField4(context.Background(), jsProt995)
		if err996 != nil {
			Usage()
			return
		}
		argvalue3 := containerStruct3.ColumnNames
		value3 := argvalue3
		fmt.Print(client.LoadTable(context.Background(), value0, value1, value2, value3))
		fmt.Print("\n")
		break
	case "detect_column_types":
		if flag.NArg() - 1 != 3 {
			fmt.Fprintln(os.Stderr, "DetectColumnTypes requires 3 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		arg999 := flag.Arg(3)
		mbTrans1000 := thrift.NewTMemoryBufferLen(len(arg999))
		defer mbTrans1000.Close()
		_, err1001 := mbTrans1000.WriteString(arg999)
		if err1001 != nil {
			Usage()
			return
		}
		factory1002 := thrift.NewTJSONProtocolFactory()
		jsProt1003 := factory1002.GetProtocol(mbTrans1000)
		argvalue2 := heavy.NewTCopyParams()
		err1004 := argvalue2.Read(context.Background(), jsProt1003)
		if err1004 != nil {
			Usage()
			return
		}
		value2 := argvalue2
		fmt.Print(client.DetectColumnTypes(context.Background(), value0, value1, value2))
		fmt.Print("\n")
		break
	case "create_table":
		if flag.NArg() - 1 != 4 {
			fmt.Fprintln(os.Stderr, "CreateTable requires 4 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		arg1007 := flag.Arg(3)
		mbTrans1008 := thrift.NewTMemoryBufferLen(len(arg1007))
		defer mbTrans1008.Close()
		_, err1009 := mbTrans1008.WriteString(arg1007)
		if err1009 != nil {
			Usage()
			return
		}
		factory1010 := thrift.NewTJSONProtocolFactory()
		jsProt1011 := factory1010.GetProtocol(mbTrans1008)
		containerStruct2 := heavy.NewHeavyCreateTableArgs()
		err1012 := containerStruct2.ReadField3(context.Background(), jsProt1011)
		if err1012 != nil {
			Usage()
			return
		}
		argvalue2 := containerStruct2.RowDesc
		value2 := heavy.TRowDescriptor(argvalue2)
		arg1013 := flag.Arg(4)
		mbTrans1014 := thrift.NewTMemoryBufferLen(len(arg1013))
		defer mbTrans1014.Close()
		_, err1015 := mbTrans1014.WriteString(arg1013)
		if err1015 != nil {
			Usage()
			return
		}
		factory1016 := thrift.NewTJSONProtocolFactory()
		jsProt1017 := factory1016.GetProtocol(mbTrans1014)
		argvalue3 := heavy.NewTCreateParams()
		err1018 := argvalue3.Read(context.Background(), jsProt1017)
		if err1018 != nil {
			Usage()
			return
		}
		value3 := argvalue3
		fmt.Print(client.CreateTable(context.Background(), value0, value1, value2, value3))
		fmt.Print("\n")
		break
	case "import_table":
		if flag.NArg() - 1 != 4 {
			fmt.Fprintln(os.Stderr, "ImportTable requires 4 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		argvalue2 := flag.Arg(3)
		value2 := argvalue2
		arg1022 := flag.Arg(4)
		mbTrans1023 := thrift.NewTMemoryBufferLen(len(arg1022))
		defer mbTrans1023.Close()
		_, err1024 := mbTrans1023.WriteString(arg1022)
		if err1024 != nil {
			Usage()
			return
		}
		factory1025 := thrift.NewTJSONProtocolFactory()
		jsProt1026 := factory1025.GetProtocol(mbTrans1023)
		argvalue3 := heavy.NewTCopyParams()
		err1027 := argvalue3.Read(context.Background(), jsProt1026)
		if err1027 != nil {
			Usage()
			return
		}
		value3 := argvalue3
		fmt.Print(client.ImportTable(context.Background(), value0, value1, value2, value3))
		fmt.Print("\n")
		break
	case "import_geo_table":
		if flag.NArg() - 1 != 6 {
			fmt.Fprintln(os.Stderr, "ImportGeoTable requires 6 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		argvalue2 := flag.Arg(3)
		value2 := argvalue2
		arg1031 := flag.Arg(4)
		mbTrans1032 := thrift.NewTMemoryBufferLen(len(arg1031))
		defer mbTrans1032.Close()
		_, err1033 := mbTrans1032.WriteString(arg1031)
		if err1033 != nil {
			Usage()
			return
		}
		factory1034 := thrift.NewTJSONProtocolFactory()
		jsProt1035 := factory1034.GetProtocol(mbTrans1032)
		argvalue3 := heavy.NewTCopyParams()
		err1036 := argvalue3.Read(context.Background(), jsProt1035)
		if err1036 != nil {
			Usage()
			return
		}
		value3 := argvalue3
		arg1037 := flag.Arg(5)
		mbTrans1038 := thrift.NewTMemoryBufferLen(len(arg1037))
		defer mbTrans1038.Close()
		_, err1039 := mbTrans1038.WriteString(arg1037)
		if err1039 != nil {
			Usage()
			return
		}
		factory1040 := thrift.NewTJSONProtocolFactory()
		jsProt1041 := factory1040.GetProtocol(mbTrans1038)
		containerStruct4 := heavy.NewHeavyImportGeoTableArgs()
		err1042 := containerStruct4.ReadField5(context.Background(), jsProt1041)
		if err1042 != nil {
			Usage()
			return
		}
		argvalue4 := containerStruct4.RowDesc
		value4 := heavy.TRowDescriptor(argvalue4)
		arg1043 := flag.Arg(6)
		mbTrans1044 := thrift.NewTMemoryBufferLen(len(arg1043))
		defer mbTrans1044.Close()
		_, err1045 := mbTrans1044.WriteString(arg1043)
		if err1045 != nil {
			Usage()
			return
		}
		factory1046 := thrift.NewTJSONProtocolFactory()
		jsProt1047 := factory1046.GetProtocol(mbTrans1044)
		argvalue5 := heavy.NewTCreateParams()
		err1048 := argvalue5.Read(context.Background(), jsProt1047)
		if err1048 != nil {
			Usage()
			return
		}
		value5 := argvalue5
		fmt.Print(client.ImportGeoTable(context.Background(), value0, value1, value2, value3, value4, value5))
		fmt.Print("\n")
		break
	case "import_table_status":
		if flag.NArg() - 1 != 2 {
			fmt.Fprintln(os.Stderr, "ImportTableStatus requires 2 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		fmt.Print(client.ImportTableStatus(context.Background(), value0, value1))
		fmt.Print("\n")
		break
	case "get_first_geo_file_in_archive":
		if flag.NArg() - 1 != 3 {
			fmt.Fprintln(os.Stderr, "GetFirstGeoFileInArchive requires 3 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		arg1053 := flag.Arg(3)
		mbTrans1054 := thrift.NewTMemoryBufferLen(len(arg1053))
		defer mbTrans1054.Close()
		_, err1055 := mbTrans1054.WriteString(arg1053)
		if err1055 != nil {
			Usage()
			return
		}
		factory1056 := thrift.NewTJSONProtocolFactory()
		jsProt1057 := factory1056.GetProtocol(mbTrans1054)
		argvalue2 := heavy.NewTCopyParams()
		err1058 := argvalue2.Read(context.Background(), jsProt1057)
		if err1058 != nil {
			Usage()
			return
		}
		value2 := argvalue2
		fmt.Print(client.GetFirstGeoFileInArchive(context.Background(), value0, value1, value2))
		fmt.Print("\n")
		break
	case "get_all_files_in_archive":
		if flag.NArg() - 1 != 3 {
			fmt.Fprintln(os.Stderr, "GetAllFilesInArchive requires 3 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		arg1061 := flag.Arg(3)
		mbTrans1062 := thrift.NewTMemoryBufferLen(len(arg1061))
		defer mbTrans1062.Close()
		_, err1063 := mbTrans1062.WriteString(arg1061)
		if err1063 != nil {
			Usage()
			return
		}
		factory1064 := thrift.NewTJSONProtocolFactory()
		jsProt1065 := factory1064.GetProtocol(mbTrans1062)
		argvalue2 := heavy.NewTCopyParams()
		err1066 := argvalue2.Read(context.Background(), jsProt1065)
		if err1066 != nil {
			Usage()
			return
		}
		value2 := argvalue2
		fmt.Print(client.GetAllFilesInArchive(context.Background(), value0, value1, value2))
		fmt.Print("\n")
		break
	case "get_layers_in_geo_file":
		if flag.NArg() - 1 != 3 {
			fmt.Fprintln(os.Stderr, "GetLayersInGeoFile requires 3 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		arg1069 := flag.Arg(3)
		mbTrans1070 := thrift.NewTMemoryBufferLen(len(arg1069))
		defer mbTrans1070.Close()
		_, err1071 := mbTrans1070.WriteString(arg1069)
		if err1071 != nil {
			Usage()
			return
		}
		factory1072 := thrift.NewTJSONProtocolFactory()
		jsProt1073 := factory1072.GetProtocol(mbTrans1070)
		argvalue2 := heavy.NewTCopyParams()
		err1074 := argvalue2.Read(context.Background(), jsProt1073)
		if err1074 != nil {
			Usage()
			return
		}
		value2 := argvalue2
		fmt.Print(client.GetLayersInGeoFile(context.Background(), value0, value1, value2))
		fmt.Print("\n")
		break
	case "query_get_outer_fragment_count":
		if flag.NArg() - 1 != 2 {
			fmt.Fprintln(os.Stderr, "QueryGetOuterFragmentCount requires 2 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		fmt.Print(client.QueryGetOuterFragmentCount(context.Background(), value0, value1))
		fmt.Print("\n")
		break
	case "check_table_consistency":
		if flag.NArg() - 1 != 2 {
			fmt.Fprintln(os.Stderr, "CheckTableConsistency requires 2 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		tmp1, err1078 := (strconv.Atoi(flag.Arg(2)))
		if err1078 != nil {
			Usage()
			return
		}
		argvalue1 := int32(tmp1)
		value1 := argvalue1
		fmt.Print(client.CheckTableConsistency(context.Background(), value0, value1))
		fmt.Print("\n")
		break
	case "start_query":
		if flag.NArg() - 1 != 6 {
			fmt.Fprintln(os.Stderr, "StartQuery requires 6 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		argvalue1 := flag.Arg(2)
		value1 := heavy.TSessionId(argvalue1)
		argvalue2 := flag.Arg(3)
		value2 := argvalue2
		argvalue3 := flag.Arg(4)
		value3 := argvalue3
		argvalue4 := flag.Arg(5) == "true"
		value4 := argvalue4
		arg1084 := flag.Arg(6)
		mbTrans1085 := thrift.NewTMemoryBufferLen(len(arg1084))
		defer mbTrans1085.Close()
		_, err1086 := mbTrans1085.WriteString(arg1084)
		if err1086 != nil {
			Usage()
			return
		}
		factory1087 := thrift.NewTJSONProtocolFactory()
		jsProt1088 := factory1087.GetProtocol(mbTrans1085)
		containerStruct5 := heavy.NewHeavyStartQueryArgs()
		err1089 := containerStruct5.ReadField6(context.Background(), jsProt1088)
		if err1089 != nil {
			Usage()
			return
		}
		argvalue5 := containerStruct5.OuterFragmentIndices
		value5 := argvalue5
		fmt.Print(client.StartQuery(context.Background(), value0, value1, value2, value3, value4, value5))
		fmt.Print("\n")
		break
	case "execute_query_step":
		if flag.NArg() - 1 != 3 {
			fmt.Fprintln(os.Stderr, "ExecuteQueryStep requires 3 args")
			flag.Usage()
		}
		arg1090 := flag.Arg(1)
		mbTrans1091 := thrift.NewTMemoryBufferLen(len(arg1090))
		defer mbTrans1091.Close()
		_, err1092 := mbTrans1091.WriteString(arg1090)
		if err1092 != nil {
			Usage()
			return
		}
		factory1093 := thrift.NewTJSONProtocolFactory()
		jsProt1094 := factory1093.GetProtocol(mbTrans1091)
		argvalue0 := heavy.NewTPendingQuery()
		err1095 := argvalue0.Read(context.Background(), jsProt1094)
		if err1095 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		argvalue1, err1096 := (strconv.ParseInt(flag.Arg(2), 10, 64))
		if err1096 != nil {
			Usage()
			return
		}
		value1 := heavy.TSubqueryId(argvalue1)
		argvalue2 := flag.Arg(3)
		value2 := argvalue2
		fmt.Print(client.ExecuteQueryStep(context.Background(), value0, value1, value2))
		fmt.Print("\n")
		break
	case "broadcast_serialized_rows":
		if flag.NArg() - 1 != 5 {
			fmt.Fprintln(os.Stderr, "BroadcastSerializedRows requires 5 args")
			flag.Usage()
		}
		arg1098 := flag.Arg(1)
		mbTrans1099 := thrift.NewTMemoryBufferLen(len(arg1098))
		defer mbTrans1099.Close()
		_, err1100 := mbTrans1099.WriteString(arg1098)
		if err1100 != nil {
			Usage()
			return
		}
		factory1101 := thrift.NewTJSONProtocolFactory()
		jsProt1102 := factory1101.GetProtocol(mbTrans1099)
		argvalue0 := serialized_result_set.NewTSerializedRows()
		err1103 := argvalue0.Read(context.Background(), jsProt1102)
		if err1103 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		arg1104 := flag.Arg(2)
		mbTrans1105 := thrift.NewTMemoryBufferLen(len(arg1104))
		defer mbTrans1105.Close()
		_, err1106 := mbTrans1105.WriteString(arg1104)
		if err1106 != nil {
			Usage()
			return
		}
		factory1107 := thrift.NewTJSONProtocolFactory()
		jsProt1108 := factory1107.GetProtocol(mbTrans1105)
		containerStruct1 := heavy.NewHeavyBroadcastSerializedRowsArgs()
		err1109 := containerStruct1.ReadField2(context.Background(), jsProt1108)
		if err1109 != nil {
			Usage()
			return
		}
		argvalue1 := containerStruct1.RowDesc
		value1 := heavy.TRowDescriptor(argvalue1)
		argvalue2, err1110 := (strconv.ParseInt(flag.Arg(3), 10, 64))
		if err1110 != nil {
			Usage()
			return
		}
		value2 := heavy.TQueryId(argvalue2)
		argvalue3, err1111 := (strconv.ParseInt(flag.Arg(4), 10, 64))
		if err1111 != nil {
			Usage()
			return
		}
		value3 := heavy.TSubqueryId(argvalue3)
		argvalue4 := flag.Arg(5) == "true"
		value4 := argvalue4
		fmt.Print(client.BroadcastSerializedRows(context.Background(), value0, value1, value2, value3, value4))
		fmt.Print("\n")
		break
	case "start_render_query":
		if flag.NArg() - 1 != 4 {
			fmt.Fprintln(os.Stderr, "StartRenderQuery requires 4 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		argvalue1, err1114 := (strconv.ParseInt(flag.Arg(2), 10, 64))
		if err1114 != nil {
			Usage()
			return
		}
		value1 := argvalue1
		tmp2, err1115 := (strconv.Atoi(flag.Arg(3)))
		if err1115 != nil {
			Usage()
			return
		}
		argvalue2 := int16(tmp2)
		value2 := argvalue2
		argvalue3 := flag.Arg(4)
		value3 := argvalue3
		fmt.Print(client.StartRenderQuery(context.Background(), value0, value1, value2, value3))
		fmt.Print("\n")
		break
	case "execute_next_render_step":
		if flag.NArg() - 1 != 2 {
			fmt.Fprintln(os.Stderr, "ExecuteNextRenderStep requires 2 args")
			flag.Usage()
		}
		arg1117 := flag.Arg(1)
		mbTrans1118 := thrift.NewTMemoryBufferLen(len(arg1117))
		defer mbTrans1118.Close()
		_, err1119 := mbTrans1118.WriteString(arg1117)
		if err1119 != nil {
			Usage()
			return
		}
		factory1120 := thrift.NewTJSONProtocolFactory()
		jsProt1121 := factory1120.GetProtocol(mbTrans1118)
		argvalue0 := heavy.NewTPendingRenderQuery()
		err1122 := argvalue0.Read(context.Background(), jsProt1121)
		if err1122 != nil {
			Usage()
			return
		}
		value0 := argvalue0
		arg1123 := flag.Arg(2)
		mbTrans1124 := thrift.NewTMemoryBufferLen(len(arg1123))
		defer mbTrans1124.Close()
		_, err1125 := mbTrans1124.WriteString(arg1123)
		if err1125 != nil {
			Usage()
			return
		}
		factory1126 := thrift.NewTJSONProtocolFactory()
		jsProt1127 := factory1126.GetProtocol(mbTrans1124)
		containerStruct1 := heavy.NewHeavyExecuteNextRenderStepArgs()
		err1128 := containerStruct1.ReadField2(context.Background(), jsProt1127)
		if err1128 != nil {
			Usage()
			return
		}
		argvalue1 := containerStruct1.MergedData
		value1 := heavy.TRenderAggDataMap(argvalue1)
		fmt.Print(client.ExecuteNextRenderStep(context.Background(), value0, value1))
		fmt.Print("\n")
		break
	case "insert_data":
		if flag.NArg() - 1 != 2 {
			fmt.Fprintln(os.Stderr, "InsertData requires 2 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		arg1130 := flag.Arg(2)
		mbTrans1131 := thrift.NewTMemoryBufferLen(len(arg1130))
		defer mbTrans1131.Close()
		_, err1132 := mbTrans1131.WriteString(arg1130)
		if err1132 != nil {
			Usage()
			return
		}
		factory1133 := thrift.NewTJSONProtocolFactory()
		jsProt1134 := factory1133.GetProtocol(mbTrans1131)
		argvalue1 := heavy.NewTInsertData()
		err1135 := argvalue1.Read(context.Background(), jsProt1134)
		if err1135 != nil {
			Usage()
			return
		}
		value1 := argvalue1
		fmt.Print(client.InsertData(context.Background(), value0, value1))
		fmt.Print("\n")
		break
	case "insert_chunks":
		if flag.NArg() - 1 != 2 {
			fmt.Fprintln(os.Stderr, "InsertChunks requires 2 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		arg1137 := flag.Arg(2)
		mbTrans1138 := thrift.NewTMemoryBufferLen(len(arg1137))
		defer mbTrans1138.Close()
		_, err1139 := mbTrans1138.WriteString(arg1137)
		if err1139 != nil {
			Usage()
			return
		}
		factory1140 := thrift.NewTJSONProtocolFactory()
		jsProt1141 := factory1140.GetProtocol(mbTrans1138)
		argvalue1 := heavy.NewTInsertChunks()
		err1142 := argvalue1.Read(context.Background(), jsProt1141)
		if err1142 != nil {
			Usage()
			return
		}
		value1 := argvalue1
		fmt.Print(client.InsertChunks(context.Background(), value0, value1))
		fmt.Print("\n")
		break
	case "checkpoint":
		if flag.NArg() - 1 != 2 {
			fmt.Fprintln(os.Stderr, "Checkpoint requires 2 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		tmp1, err1144 := (strconv.Atoi(flag.Arg(2)))
		if err1144 != nil {
			Usage()
			return
		}
		argvalue1 := int32(tmp1)
		value1 := argvalue1
		fmt.Print(client.Checkpoint(context.Background(), value0, value1))
		fmt.Print("\n")
		break
	case "get_roles":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "GetRoles requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		fmt.Print(client.GetRoles(context.Background(), value0))
		fmt.Print("\n")
		break
	case "get_db_objects_for_grantee":
		if flag.NArg() - 1 != 2 {
			fmt.Fprintln(os.Stderr, "GetDbObjectsForGrantee requires 2 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		fmt.Print(client.GetDbObjectsForGrantee(context.Background(), value0, value1))
		fmt.Print("\n")
		break
	case "get_db_object_privs":
		if flag.NArg() - 1 != 3 {
			fmt.Fprintln(os.Stderr, "GetDbObjectPrivs requires 3 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		tmp2, err := (strconv.Atoi(flag.Arg(3)))
		if err != nil {
			Usage()
			return
		}
		argvalue2 := heavy.TDBObjectType(tmp2)
		value2 := argvalue2
		fmt.Print(client.GetDbObjectPrivs(context.Background(), value0, value1, value2))
		fmt.Print("\n")
		break
	case "get_all_roles_for_user":
		if flag.NArg() - 1 != 2 {
			fmt.Fprintln(os.Stderr, "GetAllRolesForUser requires 2 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		fmt.Print(client.GetAllRolesForUser(context.Background(), value0, value1))
		fmt.Print("\n")
		break
	case "get_all_effective_roles_for_user":
		if flag.NArg() - 1 != 2 {
			fmt.Fprintln(os.Stderr, "GetAllEffectiveRolesForUser requires 2 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		fmt.Print(client.GetAllEffectiveRolesForUser(context.Background(), value0, value1))
		fmt.Print("\n")
		break
	case "has_role":
		if flag.NArg() - 1 != 3 {
			fmt.Fprintln(os.Stderr, "HasRole requires 3 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		argvalue2 := flag.Arg(3)
		value2 := argvalue2
		fmt.Print(client.HasRole(context.Background(), value0, value1, value2))
		fmt.Print("\n")
		break
	case "has_object_privilege":
		if flag.NArg() - 1 != 5 {
			fmt.Fprintln(os.Stderr, "HasObjectPrivilege requires 5 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		argvalue2 := flag.Arg(3)
		value2 := argvalue2
		tmp3, err := (strconv.Atoi(flag.Arg(4)))
		if err != nil {
			Usage()
			return
		}
		argvalue3 := heavy.TDBObjectType(tmp3)
		value3 := argvalue3
		arg1160 := flag.Arg(5)
		mbTrans1161 := thrift.NewTMemoryBufferLen(len(arg1160))
		defer mbTrans1161.Close()
		_, err1162 := mbTrans1161.WriteString(arg1160)
		if err1162 != nil {
			Usage()
			return
		}
		factory1163 := thrift.NewTJSONProtocolFactory()
		jsProt1164 := factory1163.GetProtocol(mbTrans1161)
		argvalue4 := heavy.NewTDBObjectPermissions()
		err1165 := argvalue4.Read(context.Background(), jsProt1164)
		if err1165 != nil {
			Usage()
			return
		}
		value4 := argvalue4
		fmt.Print(client.HasObjectPrivilege(context.Background(), value0, value1, value2, value3, value4))
		fmt.Print("\n")
		break
	case "get_device_parameters":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "GetDeviceParameters requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		fmt.Print(client.GetDeviceParameters(context.Background(), value0))
		fmt.Print("\n")
		break
	case "register_runtime_extension_functions":
		if flag.NArg() - 1 != 4 {
			fmt.Fprintln(os.Stderr, "RegisterRuntimeExtensionFunctions requires 4 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		arg1168 := flag.Arg(2)
		mbTrans1169 := thrift.NewTMemoryBufferLen(len(arg1168))
		defer mbTrans1169.Close()
		_, err1170 := mbTrans1169.WriteString(arg1168)
		if err1170 != nil {
			Usage()
			return
		}
		factory1171 := thrift.NewTJSONProtocolFactory()
		jsProt1172 := factory1171.GetProtocol(mbTrans1169)
		containerStruct1 := heavy.NewHeavyRegisterRuntimeExtensionFunctionsArgs()
		err1173 := containerStruct1.ReadField2(context.Background(), jsProt1172)
		if err1173 != nil {
			Usage()
			return
		}
		argvalue1 := containerStruct1.Udfs
		value1 := argvalue1
		arg1174 := flag.Arg(3)
		mbTrans1175 := thrift.NewTMemoryBufferLen(len(arg1174))
		defer mbTrans1175.Close()
		_, err1176 := mbTrans1175.WriteString(arg1174)
		if err1176 != nil {
			Usage()
			return
		}
		factory1177 := thrift.NewTJSONProtocolFactory()
		jsProt1178 := factory1177.GetProtocol(mbTrans1175)
		containerStruct2 := heavy.NewHeavyRegisterRuntimeExtensionFunctionsArgs()
		err1179 := containerStruct2.ReadField3(context.Background(), jsProt1178)
		if err1179 != nil {
			Usage()
			return
		}
		argvalue2 := containerStruct2.Udtfs
		value2 := argvalue2
		arg1180 := flag.Arg(4)
		mbTrans1181 := thrift.NewTMemoryBufferLen(len(arg1180))
		defer mbTrans1181.Close()
		_, err1182 := mbTrans1181.WriteString(arg1180)
		if err1182 != nil {
			Usage()
			return
		}
		factory1183 := thrift.NewTJSONProtocolFactory()
		jsProt1184 := factory1183.GetProtocol(mbTrans1181)
		containerStruct3 := heavy.NewHeavyRegisterRuntimeExtensionFunctionsArgs()
		err1185 := containerStruct3.ReadField4(context.Background(), jsProt1184)
		if err1185 != nil {
			Usage()
			return
		}
		argvalue3 := containerStruct3.DeviceIrMap
		value3 := argvalue3
		fmt.Print(client.RegisterRuntimeExtensionFunctions(context.Background(), value0, value1, value2, value3))
		fmt.Print("\n")
		break
	case "get_table_function_names":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "GetTableFunctionNames requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		fmt.Print(client.GetTableFunctionNames(context.Background(), value0))
		fmt.Print("\n")
		break
	case "get_runtime_table_function_names":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "GetRuntimeTableFunctionNames requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		fmt.Print(client.GetRuntimeTableFunctionNames(context.Background(), value0))
		fmt.Print("\n")
		break
	case "get_table_function_details":
		if flag.NArg() - 1 != 2 {
			fmt.Fprintln(os.Stderr, "GetTableFunctionDetails requires 2 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		arg1189 := flag.Arg(2)
		mbTrans1190 := thrift.NewTMemoryBufferLen(len(arg1189))
		defer mbTrans1190.Close()
		_, err1191 := mbTrans1190.WriteString(arg1189)
		if err1191 != nil {
			Usage()
			return
		}
		factory1192 := thrift.NewTJSONProtocolFactory()
		jsProt1193 := factory1192.GetProtocol(mbTrans1190)
		containerStruct1 := heavy.NewHeavyGetTableFunctionDetailsArgs()
		err1194 := containerStruct1.ReadField2(context.Background(), jsProt1193)
		if err1194 != nil {
			Usage()
			return
		}
		argvalue1 := containerStruct1.UdtfNames
		value1 := argvalue1
		fmt.Print(client.GetTableFunctionDetails(context.Background(), value0, value1))
		fmt.Print("\n")
		break
	case "get_function_names":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "GetFunctionNames requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		fmt.Print(client.GetFunctionNames(context.Background(), value0))
		fmt.Print("\n")
		break
	case "get_runtime_function_names":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "GetRuntimeFunctionNames requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		fmt.Print(client.GetRuntimeFunctionNames(context.Background(), value0))
		fmt.Print("\n")
		break
	case "get_function_details":
		if flag.NArg() - 1 != 2 {
			fmt.Fprintln(os.Stderr, "GetFunctionDetails requires 2 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		arg1198 := flag.Arg(2)
		mbTrans1199 := thrift.NewTMemoryBufferLen(len(arg1198))
		defer mbTrans1199.Close()
		_, err1200 := mbTrans1199.WriteString(arg1198)
		if err1200 != nil {
			Usage()
			return
		}
		factory1201 := thrift.NewTJSONProtocolFactory()
		jsProt1202 := factory1201.GetProtocol(mbTrans1199)
		containerStruct1 := heavy.NewHeavyGetFunctionDetailsArgs()
		err1203 := containerStruct1.ReadField2(context.Background(), jsProt1202)
		if err1203 != nil {
			Usage()
			return
		}
		argvalue1 := containerStruct1.UdfNames
		value1 := argvalue1
		fmt.Print(client.GetFunctionDetails(context.Background(), value0, value1))
		fmt.Print("\n")
		break
	case "put_immerse_users_metadata":
		if flag.NArg() - 1 != 2 {
			fmt.Fprintln(os.Stderr, "PutImmerseUsersMetadata requires 2 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		arg1205 := flag.Arg(2)
		mbTrans1206 := thrift.NewTMemoryBufferLen(len(arg1205))
		defer mbTrans1206.Close()
		_, err1207 := mbTrans1206.WriteString(arg1205)
		if err1207 != nil {
			Usage()
			return
		}
		factory1208 := thrift.NewTJSONProtocolFactory()
		jsProt1209 := factory1208.GetProtocol(mbTrans1206)
		containerStruct1 := heavy.NewHeavyPutImmerseUsersMetadataArgs()
		err1210 := containerStruct1.ReadField2(context.Background(), jsProt1209)
		if err1210 != nil {
			Usage()
			return
		}
		argvalue1 := containerStruct1.ImmerseUserMetadataList
		value1 := argvalue1
		fmt.Print(client.PutImmerseUsersMetadata(context.Background(), value0, value1))
		fmt.Print("\n")
		break
	case "put_immerse_database_metadata":
		if flag.NArg() - 1 != 3 {
			fmt.Fprintln(os.Stderr, "PutImmerseDatabaseMetadata requires 3 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		argvalue1 := flag.Arg(2)
		value1 := argvalue1
		argvalue2 := flag.Arg(3)
		value2 := argvalue2
		fmt.Print(client.PutImmerseDatabaseMetadata(context.Background(), value0, value1, value2))
		fmt.Print("\n")
		break
	case "get_users_info":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "GetUsersInfo requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		fmt.Print(client.GetUsersInfo(context.Background(), value0))
		fmt.Print("\n")
		break
	case "get_databases":
		if flag.NArg() - 1 != 1 {
			fmt.Fprintln(os.Stderr, "GetDatabases requires 1 args")
			flag.Usage()
		}
		argvalue0 := flag.Arg(1)
		value0 := heavy.TSessionId(argvalue0)
		fmt.Print(client.GetDatabases(context.Background(), value0))
		fmt.Print("\n")
		break
	case "":
		Usage()
	default:
		fmt.Fprintln(os.Stderr, "Invalid function ", cmd)
	}
}
