// Code generated by Thrift Compiler (0.23.0). DO NOT EDIT.

package extension_functions

import (
	"bytes"
	"context"
	"database/sql/driver"
	"errors"
	"fmt"
	"iter"
	"log/slog"
	"time"
	thrift "github.com/apache/thrift/lib/go/thrift"
	"strings"
	"regexp"
)

// (needed to ensure safety because of naive import list construction.)
var _ = bytes.Equal
var _ = context.Background
var _ = errors.New
var _ = fmt.Printf
var _ = iter.Pull[int]
var _ = slog.Log
var _ = time.Now
var _ = thrift.ZERO
// (needed by validator.)
var _ = strings.Contains
var _ = regexp.MatchString

type TExtArgumentType int64

const (
	TExtArgumentType_Int8 TExtArgumentType = 0
	TExtArgumentType_Int16 TExtArgumentType = 1
	TExtArgumentType_Int32 TExtArgumentType = 2
	TExtArgumentType_Int64 TExtArgumentType = 3
	TExtArgumentType_Float TExtArgumentType = 4
	TExtArgumentType_Double TExtArgumentType = 5
	TExtArgumentType_Void TExtArgumentType = 6
	TExtArgumentType_PInt8 TExtArgumentType = 7
	TExtArgumentType_PInt16 TExtArgumentType = 8
	TExtArgumentType_PInt32 TExtArgumentType = 9
	TExtArgumentType_PInt64 TExtArgumentType = 10
	TExtArgumentType_PFloat TExtArgumentType = 11
	TExtArgumentType_PDouble TExtArgumentType = 12
	TExtArgumentType_PBool TExtArgumentType = 13
	TExtArgumentType_Bool TExtArgumentType = 14
	TExtArgumentType_ArrayInt8 TExtArgumentType = 15
	TExtArgumentType_ArrayInt16 TExtArgumentType = 16
	TExtArgumentType_ArrayInt32 TExtArgumentType = 17
	TExtArgumentType_ArrayInt64 TExtArgumentType = 18
	TExtArgumentType_ArrayFloat TExtArgumentType = 19
	TExtArgumentType_ArrayDouble TExtArgumentType = 20
	TExtArgumentType_ArrayBool TExtArgumentType = 21
	TExtArgumentType_GeoPoint TExtArgumentType = 22
	TExtArgumentType_GeoLineString TExtArgumentType = 23
	TExtArgumentType_Cursor TExtArgumentType = 24
	TExtArgumentType_GeoPolygon TExtArgumentType = 25
	TExtArgumentType_GeoMultiPolygon TExtArgumentType = 26
	TExtArgumentType_ColumnInt8 TExtArgumentType = 27
	TExtArgumentType_ColumnInt16 TExtArgumentType = 28
	TExtArgumentType_ColumnInt32 TExtArgumentType = 29
	TExtArgumentType_ColumnInt64 TExtArgumentType = 30
	TExtArgumentType_ColumnFloat TExtArgumentType = 31
	TExtArgumentType_ColumnDouble TExtArgumentType = 32
	TExtArgumentType_ColumnBool TExtArgumentType = 33
	TExtArgumentType_TextEncodingNone TExtArgumentType = 34
	TExtArgumentType_TextEncodingDict TExtArgumentType = 35
	TExtArgumentType_ColumnListInt8 TExtArgumentType = 36
	TExtArgumentType_ColumnListInt16 TExtArgumentType = 37
	TExtArgumentType_ColumnListInt32 TExtArgumentType = 38
	TExtArgumentType_ColumnListInt64 TExtArgumentType = 39
	TExtArgumentType_ColumnListFloat TExtArgumentType = 40
	TExtArgumentType_ColumnListDouble TExtArgumentType = 41
	TExtArgumentType_ColumnListBool TExtArgumentType = 42
	TExtArgumentType_ColumnTextEncodingDict TExtArgumentType = 43
	TExtArgumentType_ColumnListTextEncodingDict TExtArgumentType = 44
	TExtArgumentType_ColumnTimestamp TExtArgumentType = 45
	TExtArgumentType_Timestamp TExtArgumentType = 46
	TExtArgumentType_ColumnArrayInt8 TExtArgumentType = 47
	TExtArgumentType_ColumnArrayInt16 TExtArgumentType = 48
	TExtArgumentType_ColumnArrayInt32 TExtArgumentType = 49
	TExtArgumentType_ColumnArrayInt64 TExtArgumentType = 50
	TExtArgumentType_ColumnArrayFloat TExtArgumentType = 51
	TExtArgumentType_ColumnArrayDouble TExtArgumentType = 52
	TExtArgumentType_ColumnArrayBool TExtArgumentType = 53
	TExtArgumentType_ColumnListArrayInt8 TExtArgumentType = 54
	TExtArgumentType_ColumnListArrayInt16 TExtArgumentType = 55
	TExtArgumentType_ColumnListArrayInt32 TExtArgumentType = 56
	TExtArgumentType_ColumnListArrayInt64 TExtArgumentType = 57
	TExtArgumentType_ColumnListArrayFloat TExtArgumentType = 58
	TExtArgumentType_ColumnListArrayDouble TExtArgumentType = 59
	TExtArgumentType_ColumnListArrayBool TExtArgumentType = 60
	TExtArgumentType_GeoMultiLineString TExtArgumentType = 61
	TExtArgumentType_ArrayTextEncodingNone TExtArgumentType = 62
	TExtArgumentType_ColumnTextEncodingNone TExtArgumentType = 63
	TExtArgumentType_ColumnListTextEncodingNone TExtArgumentType = 64
	TExtArgumentType_ColumnArrayTextEncodingNone TExtArgumentType = 65
	TExtArgumentType_ColumnListArrayTextEncodingNone TExtArgumentType = 66
	TExtArgumentType_ArrayTextEncodingDict TExtArgumentType = 67
	TExtArgumentType_ColumnArrayTextEncodingDict TExtArgumentType = 68
	TExtArgumentType_ColumnListArrayTextEncodingDict TExtArgumentType = 69
	TExtArgumentType_GeoMultiPoint TExtArgumentType = 70
	TExtArgumentType_DayTimeInterval TExtArgumentType = 71
	TExtArgumentType_YearMonthTimeInterval TExtArgumentType = 72
	TExtArgumentType_ColumnGeoPoint TExtArgumentType = 73
	TExtArgumentType_ColumnGeoLineString TExtArgumentType = 74
	TExtArgumentType_ColumnGeoPolygon TExtArgumentType = 75
	TExtArgumentType_ColumnGeoMultiPoint TExtArgumentType = 76
	TExtArgumentType_ColumnGeoMultiLineString TExtArgumentType = 77
	TExtArgumentType_ColumnGeoMultiPolygon TExtArgumentType = 78
	TExtArgumentType_ColumnListGeoPoint TExtArgumentType = 79
	TExtArgumentType_ColumnListGeoLineString TExtArgumentType = 80
	TExtArgumentType_ColumnListGeoPolygon TExtArgumentType = 81
	TExtArgumentType_ColumnListGeoMultiPoint TExtArgumentType = 82
	TExtArgumentType_ColumnListGeoMultiLineString TExtArgumentType = 83
	TExtArgumentType_ColumnListGeoMultiPolygon TExtArgumentType = 84
)

var knownTExtArgumentTypeValues = []TExtArgumentType{
	TExtArgumentType_Int8,
	TExtArgumentType_Int16,
	TExtArgumentType_Int32,
	TExtArgumentType_Int64,
	TExtArgumentType_Float,
	TExtArgumentType_Double,
	TExtArgumentType_Void,
	TExtArgumentType_PInt8,
	TExtArgumentType_PInt16,
	TExtArgumentType_PInt32,
	TExtArgumentType_PInt64,
	TExtArgumentType_PFloat,
	TExtArgumentType_PDouble,
	TExtArgumentType_PBool,
	TExtArgumentType_Bool,
	TExtArgumentType_ArrayInt8,
	TExtArgumentType_ArrayInt16,
	TExtArgumentType_ArrayInt32,
	TExtArgumentType_ArrayInt64,
	TExtArgumentType_ArrayFloat,
	TExtArgumentType_ArrayDouble,
	TExtArgumentType_ArrayBool,
	TExtArgumentType_GeoPoint,
	TExtArgumentType_GeoLineString,
	TExtArgumentType_Cursor,
	TExtArgumentType_GeoPolygon,
	TExtArgumentType_GeoMultiPolygon,
	TExtArgumentType_ColumnInt8,
	TExtArgumentType_ColumnInt16,
	TExtArgumentType_ColumnInt32,
	TExtArgumentType_ColumnInt64,
	TExtArgumentType_ColumnFloat,
	TExtArgumentType_ColumnDouble,
	TExtArgumentType_ColumnBool,
	TExtArgumentType_TextEncodingNone,
	TExtArgumentType_TextEncodingDict,
	TExtArgumentType_ColumnListInt8,
	TExtArgumentType_ColumnListInt16,
	TExtArgumentType_ColumnListInt32,
	TExtArgumentType_ColumnListInt64,
	TExtArgumentType_ColumnListFloat,
	TExtArgumentType_ColumnListDouble,
	TExtArgumentType_ColumnListBool,
	TExtArgumentType_ColumnTextEncodingDict,
	TExtArgumentType_ColumnListTextEncodingDict,
	TExtArgumentType_ColumnTimestamp,
	TExtArgumentType_Timestamp,
	TExtArgumentType_ColumnArrayInt8,
	TExtArgumentType_ColumnArrayInt16,
	TExtArgumentType_ColumnArrayInt32,
	TExtArgumentType_ColumnArrayInt64,
	TExtArgumentType_ColumnArrayFloat,
	TExtArgumentType_ColumnArrayDouble,
	TExtArgumentType_ColumnArrayBool,
	TExtArgumentType_ColumnListArrayInt8,
	TExtArgumentType_ColumnListArrayInt16,
	TExtArgumentType_ColumnListArrayInt32,
	TExtArgumentType_ColumnListArrayInt64,
	TExtArgumentType_ColumnListArrayFloat,
	TExtArgumentType_ColumnListArrayDouble,
	TExtArgumentType_ColumnListArrayBool,
	TExtArgumentType_GeoMultiLineString,
	TExtArgumentType_ArrayTextEncodingNone,
	TExtArgumentType_ColumnTextEncodingNone,
	TExtArgumentType_ColumnListTextEncodingNone,
	TExtArgumentType_ColumnArrayTextEncodingNone,
	TExtArgumentType_ColumnListArrayTextEncodingNone,
	TExtArgumentType_ArrayTextEncodingDict,
	TExtArgumentType_ColumnArrayTextEncodingDict,
	TExtArgumentType_ColumnListArrayTextEncodingDict,
	TExtArgumentType_GeoMultiPoint,
	TExtArgumentType_DayTimeInterval,
	TExtArgumentType_YearMonthTimeInterval,
	TExtArgumentType_ColumnGeoPoint,
	TExtArgumentType_ColumnGeoLineString,
	TExtArgumentType_ColumnGeoPolygon,
	TExtArgumentType_ColumnGeoMultiPoint,
	TExtArgumentType_ColumnGeoMultiLineString,
	TExtArgumentType_ColumnGeoMultiPolygon,
	TExtArgumentType_ColumnListGeoPoint,
	TExtArgumentType_ColumnListGeoLineString,
	TExtArgumentType_ColumnListGeoPolygon,
	TExtArgumentType_ColumnListGeoMultiPoint,
	TExtArgumentType_ColumnListGeoMultiLineString,
	TExtArgumentType_ColumnListGeoMultiPolygon,
}

func TExtArgumentTypeValues() iter.Seq[TExtArgumentType] {
	return func(yield func(TExtArgumentType) bool) {
		for _, v := range knownTExtArgumentTypeValues {
			if !yield(v) {
				return
			}
		}
	}
}

func (p TExtArgumentType) String() string {
	switch p {
	case TExtArgumentType_Int8: return "Int8"
	case TExtArgumentType_Int16: return "Int16"
	case TExtArgumentType_Int32: return "Int32"
	case TExtArgumentType_Int64: return "Int64"
	case TExtArgumentType_Float: return "Float"
	case TExtArgumentType_Double: return "Double"
	case TExtArgumentType_Void: return "Void"
	case TExtArgumentType_PInt8: return "PInt8"
	case TExtArgumentType_PInt16: return "PInt16"
	case TExtArgumentType_PInt32: return "PInt32"
	case TExtArgumentType_PInt64: return "PInt64"
	case TExtArgumentType_PFloat: return "PFloat"
	case TExtArgumentType_PDouble: return "PDouble"
	case TExtArgumentType_PBool: return "PBool"
	case TExtArgumentType_Bool: return "Bool"
	case TExtArgumentType_ArrayInt8: return "ArrayInt8"
	case TExtArgumentType_ArrayInt16: return "ArrayInt16"
	case TExtArgumentType_ArrayInt32: return "ArrayInt32"
	case TExtArgumentType_ArrayInt64: return "ArrayInt64"
	case TExtArgumentType_ArrayFloat: return "ArrayFloat"
	case TExtArgumentType_ArrayDouble: return "ArrayDouble"
	case TExtArgumentType_ArrayBool: return "ArrayBool"
	case TExtArgumentType_GeoPoint: return "GeoPoint"
	case TExtArgumentType_GeoLineString: return "GeoLineString"
	case TExtArgumentType_Cursor: return "Cursor"
	case TExtArgumentType_GeoPolygon: return "GeoPolygon"
	case TExtArgumentType_GeoMultiPolygon: return "GeoMultiPolygon"
	case TExtArgumentType_ColumnInt8: return "ColumnInt8"
	case TExtArgumentType_ColumnInt16: return "ColumnInt16"
	case TExtArgumentType_ColumnInt32: return "ColumnInt32"
	case TExtArgumentType_ColumnInt64: return "ColumnInt64"
	case TExtArgumentType_ColumnFloat: return "ColumnFloat"
	case TExtArgumentType_ColumnDouble: return "ColumnDouble"
	case TExtArgumentType_ColumnBool: return "ColumnBool"
	case TExtArgumentType_TextEncodingNone: return "TextEncodingNone"
	case TExtArgumentType_TextEncodingDict: return "TextEncodingDict"
	case TExtArgumentType_ColumnListInt8: return "ColumnListInt8"
	case TExtArgumentType_ColumnListInt16: return "ColumnListInt16"
	case TExtArgumentType_ColumnListInt32: return "ColumnListInt32"
	case TExtArgumentType_ColumnListInt64: return "ColumnListInt64"
	case TExtArgumentType_ColumnListFloat: return "ColumnListFloat"
	case TExtArgumentType_ColumnListDouble: return "ColumnListDouble"
	case TExtArgumentType_ColumnListBool: return "ColumnListBool"
	case TExtArgumentType_ColumnTextEncodingDict: return "ColumnTextEncodingDict"
	case TExtArgumentType_ColumnListTextEncodingDict: return "ColumnListTextEncodingDict"
	case TExtArgumentType_ColumnTimestamp: return "ColumnTimestamp"
	case TExtArgumentType_Timestamp: return "Timestamp"
	case TExtArgumentType_ColumnArrayInt8: return "ColumnArrayInt8"
	case TExtArgumentType_ColumnArrayInt16: return "ColumnArrayInt16"
	case TExtArgumentType_ColumnArrayInt32: return "ColumnArrayInt32"
	case TExtArgumentType_ColumnArrayInt64: return "ColumnArrayInt64"
	case TExtArgumentType_ColumnArrayFloat: return "ColumnArrayFloat"
	case TExtArgumentType_ColumnArrayDouble: return "ColumnArrayDouble"
	case TExtArgumentType_ColumnArrayBool: return "ColumnArrayBool"
	case TExtArgumentType_ColumnListArrayInt8: return "ColumnListArrayInt8"
	case TExtArgumentType_ColumnListArrayInt16: return "ColumnListArrayInt16"
	case TExtArgumentType_ColumnListArrayInt32: return "ColumnListArrayInt32"
	case TExtArgumentType_ColumnListArrayInt64: return "ColumnListArrayInt64"
	case TExtArgumentType_ColumnListArrayFloat: return "ColumnListArrayFloat"
	case TExtArgumentType_ColumnListArrayDouble: return "ColumnListArrayDouble"
	case TExtArgumentType_ColumnListArrayBool: return "ColumnListArrayBool"
	case TExtArgumentType_GeoMultiLineString: return "GeoMultiLineString"
	case TExtArgumentType_ArrayTextEncodingNone: return "ArrayTextEncodingNone"
	case TExtArgumentType_ColumnTextEncodingNone: return "ColumnTextEncodingNone"
	case TExtArgumentType_ColumnListTextEncodingNone: return "ColumnListTextEncodingNone"
	case TExtArgumentType_ColumnArrayTextEncodingNone: return "ColumnArrayTextEncodingNone"
	case TExtArgumentType_ColumnListArrayTextEncodingNone: return "ColumnListArrayTextEncodingNone"
	case TExtArgumentType_ArrayTextEncodingDict: return "ArrayTextEncodingDict"
	case TExtArgumentType_ColumnArrayTextEncodingDict: return "ColumnArrayTextEncodingDict"
	case TExtArgumentType_ColumnListArrayTextEncodingDict: return "ColumnListArrayTextEncodingDict"
	case TExtArgumentType_GeoMultiPoint: return "GeoMultiPoint"
	case TExtArgumentType_DayTimeInterval: return "DayTimeInterval"
	case TExtArgumentType_YearMonthTimeInterval: return "YearMonthTimeInterval"
	case TExtArgumentType_ColumnGeoPoint: return "ColumnGeoPoint"
	case TExtArgumentType_ColumnGeoLineString: return "ColumnGeoLineString"
	case TExtArgumentType_ColumnGeoPolygon: return "ColumnGeoPolygon"
	case TExtArgumentType_ColumnGeoMultiPoint: return "ColumnGeoMultiPoint"
	case TExtArgumentType_ColumnGeoMultiLineString: return "ColumnGeoMultiLineString"
	case TExtArgumentType_ColumnGeoMultiPolygon: return "ColumnGeoMultiPolygon"
	case TExtArgumentType_ColumnListGeoPoint: return "ColumnListGeoPoint"
	case TExtArgumentType_ColumnListGeoLineString: return "ColumnListGeoLineString"
	case TExtArgumentType_ColumnListGeoPolygon: return "ColumnListGeoPolygon"
	case TExtArgumentType_ColumnListGeoMultiPoint: return "ColumnListGeoMultiPoint"
	case TExtArgumentType_ColumnListGeoMultiLineString: return "ColumnListGeoMultiLineString"
	case TExtArgumentType_ColumnListGeoMultiPolygon: return "ColumnListGeoMultiPolygon"
	}
	return "<UNSET>"
}

func TExtArgumentTypeFromString(s string) (TExtArgumentType, error) {
	switch s {
	case "Int8": return TExtArgumentType_Int8, nil
	case "Int16": return TExtArgumentType_Int16, nil
	case "Int32": return TExtArgumentType_Int32, nil
	case "Int64": return TExtArgumentType_Int64, nil
	case "Float": return TExtArgumentType_Float, nil
	case "Double": return TExtArgumentType_Double, nil
	case "Void": return TExtArgumentType_Void, nil
	case "PInt8": return TExtArgumentType_PInt8, nil
	case "PInt16": return TExtArgumentType_PInt16, nil
	case "PInt32": return TExtArgumentType_PInt32, nil
	case "PInt64": return TExtArgumentType_PInt64, nil
	case "PFloat": return TExtArgumentType_PFloat, nil
	case "PDouble": return TExtArgumentType_PDouble, nil
	case "PBool": return TExtArgumentType_PBool, nil
	case "Bool": return TExtArgumentType_Bool, nil
	case "ArrayInt8": return TExtArgumentType_ArrayInt8, nil
	case "ArrayInt16": return TExtArgumentType_ArrayInt16, nil
	case "ArrayInt32": return TExtArgumentType_ArrayInt32, nil
	case "ArrayInt64": return TExtArgumentType_ArrayInt64, nil
	case "ArrayFloat": return TExtArgumentType_ArrayFloat, nil
	case "ArrayDouble": return TExtArgumentType_ArrayDouble, nil
	case "ArrayBool": return TExtArgumentType_ArrayBool, nil
	case "GeoPoint": return TExtArgumentType_GeoPoint, nil
	case "GeoLineString": return TExtArgumentType_GeoLineString, nil
	case "Cursor": return TExtArgumentType_Cursor, nil
	case "GeoPolygon": return TExtArgumentType_GeoPolygon, nil
	case "GeoMultiPolygon": return TExtArgumentType_GeoMultiPolygon, nil
	case "ColumnInt8": return TExtArgumentType_ColumnInt8, nil
	case "ColumnInt16": return TExtArgumentType_ColumnInt16, nil
	case "ColumnInt32": return TExtArgumentType_ColumnInt32, nil
	case "ColumnInt64": return TExtArgumentType_ColumnInt64, nil
	case "ColumnFloat": return TExtArgumentType_ColumnFloat, nil
	case "ColumnDouble": return TExtArgumentType_ColumnDouble, nil
	case "ColumnBool": return TExtArgumentType_ColumnBool, nil
	case "TextEncodingNone": return TExtArgumentType_TextEncodingNone, nil
	case "TextEncodingDict": return TExtArgumentType_TextEncodingDict, nil
	case "ColumnListInt8": return TExtArgumentType_ColumnListInt8, nil
	case "ColumnListInt16": return TExtArgumentType_ColumnListInt16, nil
	case "ColumnListInt32": return TExtArgumentType_ColumnListInt32, nil
	case "ColumnListInt64": return TExtArgumentType_ColumnListInt64, nil
	case "ColumnListFloat": return TExtArgumentType_ColumnListFloat, nil
	case "ColumnListDouble": return TExtArgumentType_ColumnListDouble, nil
	case "ColumnListBool": return TExtArgumentType_ColumnListBool, nil
	case "ColumnTextEncodingDict": return TExtArgumentType_ColumnTextEncodingDict, nil
	case "ColumnListTextEncodingDict": return TExtArgumentType_ColumnListTextEncodingDict, nil
	case "ColumnTimestamp": return TExtArgumentType_ColumnTimestamp, nil
	case "Timestamp": return TExtArgumentType_Timestamp, nil
	case "ColumnArrayInt8": return TExtArgumentType_ColumnArrayInt8, nil
	case "ColumnArrayInt16": return TExtArgumentType_ColumnArrayInt16, nil
	case "ColumnArrayInt32": return TExtArgumentType_ColumnArrayInt32, nil
	case "ColumnArrayInt64": return TExtArgumentType_ColumnArrayInt64, nil
	case "ColumnArrayFloat": return TExtArgumentType_ColumnArrayFloat, nil
	case "ColumnArrayDouble": return TExtArgumentType_ColumnArrayDouble, nil
	case "ColumnArrayBool": return TExtArgumentType_ColumnArrayBool, nil
	case "ColumnListArrayInt8": return TExtArgumentType_ColumnListArrayInt8, nil
	case "ColumnListArrayInt16": return TExtArgumentType_ColumnListArrayInt16, nil
	case "ColumnListArrayInt32": return TExtArgumentType_ColumnListArrayInt32, nil
	case "ColumnListArrayInt64": return TExtArgumentType_ColumnListArrayInt64, nil
	case "ColumnListArrayFloat": return TExtArgumentType_ColumnListArrayFloat, nil
	case "ColumnListArrayDouble": return TExtArgumentType_ColumnListArrayDouble, nil
	case "ColumnListArrayBool": return TExtArgumentType_ColumnListArrayBool, nil
	case "GeoMultiLineString": return TExtArgumentType_GeoMultiLineString, nil
	case "ArrayTextEncodingNone": return TExtArgumentType_ArrayTextEncodingNone, nil
	case "ColumnTextEncodingNone": return TExtArgumentType_ColumnTextEncodingNone, nil
	case "ColumnListTextEncodingNone": return TExtArgumentType_ColumnListTextEncodingNone, nil
	case "ColumnArrayTextEncodingNone": return TExtArgumentType_ColumnArrayTextEncodingNone, nil
	case "ColumnListArrayTextEncodingNone": return TExtArgumentType_ColumnListArrayTextEncodingNone, nil
	case "ArrayTextEncodingDict": return TExtArgumentType_ArrayTextEncodingDict, nil
	case "ColumnArrayTextEncodingDict": return TExtArgumentType_ColumnArrayTextEncodingDict, nil
	case "ColumnListArrayTextEncodingDict": return TExtArgumentType_ColumnListArrayTextEncodingDict, nil
	case "GeoMultiPoint": return TExtArgumentType_GeoMultiPoint, nil
	case "DayTimeInterval": return TExtArgumentType_DayTimeInterval, nil
	case "YearMonthTimeInterval": return TExtArgumentType_YearMonthTimeInterval, nil
	case "ColumnGeoPoint": return TExtArgumentType_ColumnGeoPoint, nil
	case "ColumnGeoLineString": return TExtArgumentType_ColumnGeoLineString, nil
	case "ColumnGeoPolygon": return TExtArgumentType_ColumnGeoPolygon, nil
	case "ColumnGeoMultiPoint": return TExtArgumentType_ColumnGeoMultiPoint, nil
	case "ColumnGeoMultiLineString": return TExtArgumentType_ColumnGeoMultiLineString, nil
	case "ColumnGeoMultiPolygon": return TExtArgumentType_ColumnGeoMultiPolygon, nil
	case "ColumnListGeoPoint": return TExtArgumentType_ColumnListGeoPoint, nil
	case "ColumnListGeoLineString": return TExtArgumentType_ColumnListGeoLineString, nil
	case "ColumnListGeoPolygon": return TExtArgumentType_ColumnListGeoPolygon, nil
	case "ColumnListGeoMultiPoint": return TExtArgumentType_ColumnListGeoMultiPoint, nil
	case "ColumnListGeoMultiLineString": return TExtArgumentType_ColumnListGeoMultiLineString, nil
	case "ColumnListGeoMultiPolygon": return TExtArgumentType_ColumnListGeoMultiPolygon, nil
	}
	return TExtArgumentType(0), fmt.Errorf("not a valid TExtArgumentType string")
}


func TExtArgumentTypePtr(v TExtArgumentType) *TExtArgumentType { return &v }

func (p TExtArgumentType) MarshalText() ([]byte, error) {
	return []byte(p.String()), nil
}

func (p *TExtArgumentType) UnmarshalText(text []byte) error {
	q, err := TExtArgumentTypeFromString(string(text))
	if err != nil {
		return err
	}
	*p = q
	return nil
}

func (p *TExtArgumentType) Scan(value interface{}) error {
	v, ok := value.(int64)
	if !ok {
		return errors.New("Scan value is not int64")
	}
	*p = TExtArgumentType(v)
	return nil
}

func (p *TExtArgumentType) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type TOutputBufferSizeType int64

const (
	TOutputBufferSizeType_kConstant TOutputBufferSizeType = 0
	TOutputBufferSizeType_kUserSpecifiedConstantParameter TOutputBufferSizeType = 1
	TOutputBufferSizeType_kUserSpecifiedRowMultiplier TOutputBufferSizeType = 2
	TOutputBufferSizeType_kTableFunctionSpecifiedParameter TOutputBufferSizeType = 3
	TOutputBufferSizeType_kPreFlightParameter TOutputBufferSizeType = 4
)

var knownTOutputBufferSizeTypeValues = []TOutputBufferSizeType{
	TOutputBufferSizeType_kConstant,
	TOutputBufferSizeType_kUserSpecifiedConstantParameter,
	TOutputBufferSizeType_kUserSpecifiedRowMultiplier,
	TOutputBufferSizeType_kTableFunctionSpecifiedParameter,
	TOutputBufferSizeType_kPreFlightParameter,
}

func TOutputBufferSizeTypeValues() iter.Seq[TOutputBufferSizeType] {
	return func(yield func(TOutputBufferSizeType) bool) {
		for _, v := range knownTOutputBufferSizeTypeValues {
			if !yield(v) {
				return
			}
		}
	}
}

func (p TOutputBufferSizeType) String() string {
	switch p {
	case TOutputBufferSizeType_kConstant: return "kConstant"
	case TOutputBufferSizeType_kUserSpecifiedConstantParameter: return "kUserSpecifiedConstantParameter"
	case TOutputBufferSizeType_kUserSpecifiedRowMultiplier: return "kUserSpecifiedRowMultiplier"
	case TOutputBufferSizeType_kTableFunctionSpecifiedParameter: return "kTableFunctionSpecifiedParameter"
	case TOutputBufferSizeType_kPreFlightParameter: return "kPreFlightParameter"
	}
	return "<UNSET>"
}

func TOutputBufferSizeTypeFromString(s string) (TOutputBufferSizeType, error) {
	switch s {
	case "kConstant": return TOutputBufferSizeType_kConstant, nil
	case "kUserSpecifiedConstantParameter": return TOutputBufferSizeType_kUserSpecifiedConstantParameter, nil
	case "kUserSpecifiedRowMultiplier": return TOutputBufferSizeType_kUserSpecifiedRowMultiplier, nil
	case "kTableFunctionSpecifiedParameter": return TOutputBufferSizeType_kTableFunctionSpecifiedParameter, nil
	case "kPreFlightParameter": return TOutputBufferSizeType_kPreFlightParameter, nil
	}
	return TOutputBufferSizeType(0), fmt.Errorf("not a valid TOutputBufferSizeType string")
}


func TOutputBufferSizeTypePtr(v TOutputBufferSizeType) *TOutputBufferSizeType { return &v }

func (p TOutputBufferSizeType) MarshalText() ([]byte, error) {
	return []byte(p.String()), nil
}

func (p *TOutputBufferSizeType) UnmarshalText(text []byte) error {
	q, err := TOutputBufferSizeTypeFromString(string(text))
	if err != nil {
		return err
	}
	*p = q
	return nil
}

func (p *TOutputBufferSizeType) Scan(value interface{}) error {
	v, ok := value.(int64)
	if !ok {
		return errors.New("Scan value is not int64")
	}
	*p = TOutputBufferSizeType(v)
	return nil
}

func (p *TOutputBufferSizeType) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

// Attributes:
//  - Name
//  - ArgTypes
//  - RetType
//  - Annotations
// 
type TUserDefinedFunction struct {
	Name string `thrift:"name,1" db:"name" json:"name"`
	ArgTypes []TExtArgumentType `thrift:"argTypes,2" db:"argTypes" json:"argTypes"`
	RetType TExtArgumentType `thrift:"retType,3" db:"retType" json:"retType"`
	Annotations []map[string]string `thrift:"annotations,4" db:"annotations" json:"annotations"`
}

func NewTUserDefinedFunction() *TUserDefinedFunction {
	return &TUserDefinedFunction{}
}



func (p *TUserDefinedFunction) GetName() string {
	return p.Name
}



func (p *TUserDefinedFunction) GetArgTypes() []TExtArgumentType {
	return p.ArgTypes
}



func (p *TUserDefinedFunction) GetRetType() TExtArgumentType {
	return p.RetType
}



func (p *TUserDefinedFunction) GetAnnotations() []map[string]string {
	return p.Annotations
}

func (p *TUserDefinedFunction) Read(ctx context.Context, iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}


	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRING {
				if err := p.ReadField1(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 2:
			if fieldTypeId == thrift.LIST {
				if err := p.ReadField2(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 3:
			if fieldTypeId == thrift.I32 {
				if err := p.ReadField3(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 4:
			if fieldTypeId == thrift.LIST {
				if err := p.ReadField4(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(ctx, fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *TUserDefinedFunction) ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(ctx); err != nil {
		return thrift.PrependError("error reading field 1: ", err)
	} else {
		p.Name = v
	}
	return nil
}

func (p *TUserDefinedFunction) ReadField2(ctx context.Context, iprot thrift.TProtocol) error {
	_, size, err := iprot.ReadListBegin(ctx)
	if err != nil {
		return thrift.PrependError("error reading list begin: ", err)
	}
	tSlice := make([]TExtArgumentType, 0, size)
	p.ArgTypes = tSlice
	for i := 0; i < size; i++ {
		var _elem0 TExtArgumentType
		if v, err := iprot.ReadI32(ctx); err != nil {
			return thrift.PrependError("error reading field 0: ", err)
		} else {
			temp := TExtArgumentType(v)
			_elem0 = temp
		}
		p.ArgTypes = append(p.ArgTypes, _elem0)
	}
	if err := iprot.ReadListEnd(ctx); err != nil {
		return thrift.PrependError("error reading list end: ", err)
	}
	return nil
}

func (p *TUserDefinedFunction) ReadField3(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(ctx); err != nil {
		return thrift.PrependError("error reading field 3: ", err)
	} else {
		temp := TExtArgumentType(v)
		p.RetType = temp
	}
	return nil
}

func (p *TUserDefinedFunction) ReadField4(ctx context.Context, iprot thrift.TProtocol) error {
	_, size, err := iprot.ReadListBegin(ctx)
	if err != nil {
		return thrift.PrependError("error reading list begin: ", err)
	}
	tSlice := make([]map[string]string, 0, size)
	p.Annotations = tSlice
	for i := 0; i < size; i++ {
		_, _, size, err := iprot.ReadMapBegin(ctx)
		if err != nil {
			return thrift.PrependError("error reading map begin: ", err)
		}
		tMap := make(map[string]string, size)
		_elem1 := tMap
		for i := 0; i < size; i++ {
			var _key2 string
			if v, err := iprot.ReadString(ctx); err != nil {
				return thrift.PrependError("error reading field 0: ", err)
			} else {
				_key2 = v
			}
			var _val3 string
			if v, err := iprot.ReadString(ctx); err != nil {
				return thrift.PrependError("error reading field 0: ", err)
			} else {
				_val3 = v
			}
			_elem1[_key2] = _val3
		}
		if err := iprot.ReadMapEnd(ctx); err != nil {
			return thrift.PrependError("error reading map end: ", err)
		}
		p.Annotations = append(p.Annotations, _elem1)
	}
	if err := iprot.ReadListEnd(ctx); err != nil {
		return thrift.PrependError("error reading list end: ", err)
	}
	return nil
}

func (p *TUserDefinedFunction) Write(ctx context.Context, oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin(ctx, "TUserDefinedFunction"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField1(ctx, oprot); err != nil { return err }
		if err := p.writeField2(ctx, oprot); err != nil { return err }
		if err := p.writeField3(ctx, oprot); err != nil { return err }
		if err := p.writeField4(ctx, oprot); err != nil { return err }
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *TUserDefinedFunction) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "name", thrift.STRING, 1); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:name: ", p), err)
	}
	if err := oprot.WriteString(ctx, string(p.Name)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.name (1) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 1:name: ", p), err)
	}
	return err
}

func (p *TUserDefinedFunction) writeField2(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "argTypes", thrift.LIST, 2); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:argTypes: ", p), err)
	}
	if err := oprot.WriteListBegin(ctx, thrift.I32, len(p.ArgTypes)); err != nil {
		return thrift.PrependError("error writing list begin: ", err)
	}
	for _, v := range p.ArgTypes {
		if err := oprot.WriteI32(ctx, int32(v)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T. (0) field write error: ", p), err)
		}
	}
	if err := oprot.WriteListEnd(ctx); err != nil {
		return thrift.PrependError("error writing list end: ", err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 2:argTypes: ", p), err)
	}
	return err
}

func (p *TUserDefinedFunction) writeField3(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "retType", thrift.I32, 3); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 3:retType: ", p), err)
	}
	if err := oprot.WriteI32(ctx, int32(p.RetType)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.retType (3) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 3:retType: ", p), err)
	}
	return err
}

func (p *TUserDefinedFunction) writeField4(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "annotations", thrift.LIST, 4); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 4:annotations: ", p), err)
	}
	if err := oprot.WriteListBegin(ctx, thrift.MAP, len(p.Annotations)); err != nil {
		return thrift.PrependError("error writing list begin: ", err)
	}
	for _, v := range p.Annotations {
		if err := oprot.WriteMapBegin(ctx, thrift.STRING, thrift.STRING, len(v)); err != nil {
			return thrift.PrependError("error writing map begin: ", err)
		}
		for k, v := range v {
			if err := oprot.WriteString(ctx, string(k)); err != nil {
				return thrift.PrependError(fmt.Sprintf("%T. (0) field write error: ", p), err)
			}
			if err := oprot.WriteString(ctx, string(v)); err != nil {
				return thrift.PrependError(fmt.Sprintf("%T. (0) field write error: ", p), err)
			}
		}
		if err := oprot.WriteMapEnd(ctx); err != nil {
			return thrift.PrependError("error writing map end: ", err)
		}
	}
	if err := oprot.WriteListEnd(ctx); err != nil {
		return thrift.PrependError("error writing list end: ", err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 4:annotations: ", p), err)
	}
	return err
}

func (p *TUserDefinedFunction) Equals(other *TUserDefinedFunction) bool {
	if p == other {
		return true
	} else if p == nil || other == nil {
		return false
	}
	if p.Name != other.Name { return false }
	if len(p.ArgTypes) != len(other.ArgTypes) { return false }
	for i, _tgt := range p.ArgTypes {
		_src4 := other.ArgTypes[i]
		if _tgt != _src4 { return false }
	}
	if p.RetType != other.RetType { return false }
	if len(p.Annotations) != len(other.Annotations) { return false }
	for i, _tgt := range p.Annotations {
		_src5 := other.Annotations[i]
		if len(_tgt) != len(_src5) { return false }
		for k, _tgt := range _tgt {
			_src6 := _src5[k]
			if _tgt != _src6 { return false }
		}
	}
	return true
}

func (p *TUserDefinedFunction) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TUserDefinedFunction(%+v)", *p)
}

func (p *TUserDefinedFunction) LogValue() slog.Value {
	if p == nil {
		return slog.AnyValue(nil)
	}
	v := thrift.SlogTStructWrapper{
		Type: "*extension_functions.TUserDefinedFunction",
		Value: p,
	}
	return slog.AnyValue(v)
}

var _ slog.LogValuer = (*TUserDefinedFunction)(nil)

func (p *TUserDefinedFunction) Validate() error {
	return nil
}

// Attributes:
//  - Name
//  - SizerType
//  - SizerArgPos
//  - InputArgTypes
//  - OutputArgTypes
//  - SqlArgTypes
//  - Annotations
// 
type TUserDefinedTableFunction struct {
	Name string `thrift:"name,1" db:"name" json:"name"`
	SizerType TOutputBufferSizeType `thrift:"sizerType,2" db:"sizerType" json:"sizerType"`
	SizerArgPos int32 `thrift:"sizerArgPos,3" db:"sizerArgPos" json:"sizerArgPos"`
	InputArgTypes []TExtArgumentType `thrift:"inputArgTypes,4" db:"inputArgTypes" json:"inputArgTypes"`
	OutputArgTypes []TExtArgumentType `thrift:"outputArgTypes,5" db:"outputArgTypes" json:"outputArgTypes"`
	SqlArgTypes []TExtArgumentType `thrift:"sqlArgTypes,6" db:"sqlArgTypes" json:"sqlArgTypes"`
	Annotations []map[string]string `thrift:"annotations,7" db:"annotations" json:"annotations"`
}

func NewTUserDefinedTableFunction() *TUserDefinedTableFunction {
	return &TUserDefinedTableFunction{}
}



func (p *TUserDefinedTableFunction) GetName() string {
	return p.Name
}



func (p *TUserDefinedTableFunction) GetSizerType() TOutputBufferSizeType {
	return p.SizerType
}



func (p *TUserDefinedTableFunction) GetSizerArgPos() int32 {
	return p.SizerArgPos
}



func (p *TUserDefinedTableFunction) GetInputArgTypes() []TExtArgumentType {
	return p.InputArgTypes
}



func (p *TUserDefinedTableFunction) GetOutputArgTypes() []TExtArgumentType {
	return p.OutputArgTypes
}



func (p *TUserDefinedTableFunction) GetSqlArgTypes() []TExtArgumentType {
	return p.SqlArgTypes
}



func (p *TUserDefinedTableFunction) GetAnnotations() []map[string]string {
	return p.Annotations
}

func (p *TUserDefinedTableFunction) Read(ctx context.Context, iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}


	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if fieldTypeId == thrift.STRING {
				if err := p.ReadField1(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 2:
			if fieldTypeId == thrift.I32 {
				if err := p.ReadField2(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 3:
			if fieldTypeId == thrift.I32 {
				if err := p.ReadField3(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 4:
			if fieldTypeId == thrift.LIST {
				if err := p.ReadField4(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 5:
			if fieldTypeId == thrift.LIST {
				if err := p.ReadField5(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 6:
			if fieldTypeId == thrift.LIST {
				if err := p.ReadField6(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 7:
			if fieldTypeId == thrift.LIST {
				if err := p.ReadField7(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(ctx, fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *TUserDefinedTableFunction) ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadString(ctx); err != nil {
		return thrift.PrependError("error reading field 1: ", err)
	} else {
		p.Name = v
	}
	return nil
}

func (p *TUserDefinedTableFunction) ReadField2(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(ctx); err != nil {
		return thrift.PrependError("error reading field 2: ", err)
	} else {
		temp := TOutputBufferSizeType(v)
		p.SizerType = temp
	}
	return nil
}

func (p *TUserDefinedTableFunction) ReadField3(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(ctx); err != nil {
		return thrift.PrependError("error reading field 3: ", err)
	} else {
		p.SizerArgPos = v
	}
	return nil
}

func (p *TUserDefinedTableFunction) ReadField4(ctx context.Context, iprot thrift.TProtocol) error {
	_, size, err := iprot.ReadListBegin(ctx)
	if err != nil {
		return thrift.PrependError("error reading list begin: ", err)
	}
	tSlice := make([]TExtArgumentType, 0, size)
	p.InputArgTypes = tSlice
	for i := 0; i < size; i++ {
		var _elem7 TExtArgumentType
		if v, err := iprot.ReadI32(ctx); err != nil {
			return thrift.PrependError("error reading field 0: ", err)
		} else {
			temp := TExtArgumentType(v)
			_elem7 = temp
		}
		p.InputArgTypes = append(p.InputArgTypes, _elem7)
	}
	if err := iprot.ReadListEnd(ctx); err != nil {
		return thrift.PrependError("error reading list end: ", err)
	}
	return nil
}

func (p *TUserDefinedTableFunction) ReadField5(ctx context.Context, iprot thrift.TProtocol) error {
	_, size, err := iprot.ReadListBegin(ctx)
	if err != nil {
		return thrift.PrependError("error reading list begin: ", err)
	}
	tSlice := make([]TExtArgumentType, 0, size)
	p.OutputArgTypes = tSlice
	for i := 0; i < size; i++ {
		var _elem8 TExtArgumentType
		if v, err := iprot.ReadI32(ctx); err != nil {
			return thrift.PrependError("error reading field 0: ", err)
		} else {
			temp := TExtArgumentType(v)
			_elem8 = temp
		}
		p.OutputArgTypes = append(p.OutputArgTypes, _elem8)
	}
	if err := iprot.ReadListEnd(ctx); err != nil {
		return thrift.PrependError("error reading list end: ", err)
	}
	return nil
}

func (p *TUserDefinedTableFunction) ReadField6(ctx context.Context, iprot thrift.TProtocol) error {
	_, size, err := iprot.ReadListBegin(ctx)
	if err != nil {
		return thrift.PrependError("error reading list begin: ", err)
	}
	tSlice := make([]TExtArgumentType, 0, size)
	p.SqlArgTypes = tSlice
	for i := 0; i < size; i++ {
		var _elem9 TExtArgumentType
		if v, err := iprot.ReadI32(ctx); err != nil {
			return thrift.PrependError("error reading field 0: ", err)
		} else {
			temp := TExtArgumentType(v)
			_elem9 = temp
		}
		p.SqlArgTypes = append(p.SqlArgTypes, _elem9)
	}
	if err := iprot.ReadListEnd(ctx); err != nil {
		return thrift.PrependError("error reading list end: ", err)
	}
	return nil
}

func (p *TUserDefinedTableFunction) ReadField7(ctx context.Context, iprot thrift.TProtocol) error {
	_, size, err := iprot.ReadListBegin(ctx)
	if err != nil {
		return thrift.PrependError("error reading list begin: ", err)
	}
	tSlice := make([]map[string]string, 0, size)
	p.Annotations = tSlice
	for i := 0; i < size; i++ {
		_, _, size, err := iprot.ReadMapBegin(ctx)
		if err != nil {
			return thrift.PrependError("error reading map begin: ", err)
		}
		tMap := make(map[string]string, size)
		_elem10 := tMap
		for i := 0; i < size; i++ {
			var _key11 string
			if v, err := iprot.ReadString(ctx); err != nil {
				return thrift.PrependError("error reading field 0: ", err)
			} else {
				_key11 = v
			}
			var _val12 string
			if v, err := iprot.ReadString(ctx); err != nil {
				return thrift.PrependError("error reading field 0: ", err)
			} else {
				_val12 = v
			}
			_elem10[_key11] = _val12
		}
		if err := iprot.ReadMapEnd(ctx); err != nil {
			return thrift.PrependError("error reading map end: ", err)
		}
		p.Annotations = append(p.Annotations, _elem10)
	}
	if err := iprot.ReadListEnd(ctx); err != nil {
		return thrift.PrependError("error reading list end: ", err)
	}
	return nil
}

func (p *TUserDefinedTableFunction) Write(ctx context.Context, oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin(ctx, "TUserDefinedTableFunction"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField1(ctx, oprot); err != nil { return err }
		if err := p.writeField2(ctx, oprot); err != nil { return err }
		if err := p.writeField3(ctx, oprot); err != nil { return err }
		if err := p.writeField4(ctx, oprot); err != nil { return err }
		if err := p.writeField5(ctx, oprot); err != nil { return err }
		if err := p.writeField6(ctx, oprot); err != nil { return err }
		if err := p.writeField7(ctx, oprot); err != nil { return err }
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *TUserDefinedTableFunction) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "name", thrift.STRING, 1); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:name: ", p), err)
	}
	if err := oprot.WriteString(ctx, string(p.Name)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.name (1) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 1:name: ", p), err)
	}
	return err
}

func (p *TUserDefinedTableFunction) writeField2(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "sizerType", thrift.I32, 2); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:sizerType: ", p), err)
	}
	if err := oprot.WriteI32(ctx, int32(p.SizerType)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.sizerType (2) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 2:sizerType: ", p), err)
	}
	return err
}

func (p *TUserDefinedTableFunction) writeField3(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "sizerArgPos", thrift.I32, 3); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 3:sizerArgPos: ", p), err)
	}
	if err := oprot.WriteI32(ctx, int32(p.SizerArgPos)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.sizerArgPos (3) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 3:sizerArgPos: ", p), err)
	}
	return err
}

func (p *TUserDefinedTableFunction) writeField4(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "inputArgTypes", thrift.LIST, 4); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 4:inputArgTypes: ", p), err)
	}
	if err := oprot.WriteListBegin(ctx, thrift.I32, len(p.InputArgTypes)); err != nil {
		return thrift.PrependError("error writing list begin: ", err)
	}
	for _, v := range p.InputArgTypes {
		if err := oprot.WriteI32(ctx, int32(v)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T. (0) field write error: ", p), err)
		}
	}
	if err := oprot.WriteListEnd(ctx); err != nil {
		return thrift.PrependError("error writing list end: ", err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 4:inputArgTypes: ", p), err)
	}
	return err
}

func (p *TUserDefinedTableFunction) writeField5(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "outputArgTypes", thrift.LIST, 5); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 5:outputArgTypes: ", p), err)
	}
	if err := oprot.WriteListBegin(ctx, thrift.I32, len(p.OutputArgTypes)); err != nil {
		return thrift.PrependError("error writing list begin: ", err)
	}
	for _, v := range p.OutputArgTypes {
		if err := oprot.WriteI32(ctx, int32(v)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T. (0) field write error: ", p), err)
		}
	}
	if err := oprot.WriteListEnd(ctx); err != nil {
		return thrift.PrependError("error writing list end: ", err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 5:outputArgTypes: ", p), err)
	}
	return err
}

func (p *TUserDefinedTableFunction) writeField6(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "sqlArgTypes", thrift.LIST, 6); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 6:sqlArgTypes: ", p), err)
	}
	if err := oprot.WriteListBegin(ctx, thrift.I32, len(p.SqlArgTypes)); err != nil {
		return thrift.PrependError("error writing list begin: ", err)
	}
	for _, v := range p.SqlArgTypes {
		if err := oprot.WriteI32(ctx, int32(v)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T. (0) field write error: ", p), err)
		}
	}
	if err := oprot.WriteListEnd(ctx); err != nil {
		return thrift.PrependError("error writing list end: ", err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 6:sqlArgTypes: ", p), err)
	}
	return err
}

func (p *TUserDefinedTableFunction) writeField7(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "annotations", thrift.LIST, 7); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 7:annotations: ", p), err)
	}
	if err := oprot.WriteListBegin(ctx, thrift.MAP, len(p.Annotations)); err != nil {
		return thrift.PrependError("error writing list begin: ", err)
	}
	for _, v := range p.Annotations {
		if err := oprot.WriteMapBegin(ctx, thrift.STRING, thrift.STRING, len(v)); err != nil {
			return thrift.PrependError("error writing map begin: ", err)
		}
		for k, v := range v {
			if err := oprot.WriteString(ctx, string(k)); err != nil {
				return thrift.PrependError(fmt.Sprintf("%T. (0) field write error: ", p), err)
			}
			if err := oprot.WriteString(ctx, string(v)); err != nil {
				return thrift.PrependError(fmt.Sprintf("%T. (0) field write error: ", p), err)
			}
		}
		if err := oprot.WriteMapEnd(ctx); err != nil {
			return thrift.PrependError("error writing map end: ", err)
		}
	}
	if err := oprot.WriteListEnd(ctx); err != nil {
		return thrift.PrependError("error writing list end: ", err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 7:annotations: ", p), err)
	}
	return err
}

func (p *TUserDefinedTableFunction) Equals(other *TUserDefinedTableFunction) bool {
	if p == other {
		return true
	} else if p == nil || other == nil {
		return false
	}
	if p.Name != other.Name { return false }
	if p.SizerType != other.SizerType { return false }
	if p.SizerArgPos != other.SizerArgPos { return false }
	if len(p.InputArgTypes) != len(other.InputArgTypes) { return false }
	for i, _tgt := range p.InputArgTypes {
		_src13 := other.InputArgTypes[i]
		if _tgt != _src13 { return false }
	}
	if len(p.OutputArgTypes) != len(other.OutputArgTypes) { return false }
	for i, _tgt := range p.OutputArgTypes {
		_src14 := other.OutputArgTypes[i]
		if _tgt != _src14 { return false }
	}
	if len(p.SqlArgTypes) != len(other.SqlArgTypes) { return false }
	for i, _tgt := range p.SqlArgTypes {
		_src15 := other.SqlArgTypes[i]
		if _tgt != _src15 { return false }
	}
	if len(p.Annotations) != len(other.Annotations) { return false }
	for i, _tgt := range p.Annotations {
		_src16 := other.Annotations[i]
		if len(_tgt) != len(_src16) { return false }
		for k, _tgt := range _tgt {
			_src17 := _src16[k]
			if _tgt != _src17 { return false }
		}
	}
	return true
}

func (p *TUserDefinedTableFunction) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TUserDefinedTableFunction(%+v)", *p)
}

func (p *TUserDefinedTableFunction) LogValue() slog.Value {
	if p == nil {
		return slog.AnyValue(nil)
	}
	v := thrift.SlogTStructWrapper{
		Type: "*extension_functions.TUserDefinedTableFunction",
		Value: p,
	}
	return slog.AnyValue(v)
}

var _ slog.LogValuer = (*TUserDefinedTableFunction)(nil)

func (p *TUserDefinedTableFunction) Validate() error {
	return nil
}

