# port = 6274
# http-port = 6278
# null-div-by-zero = true
cpu-only = true

[web]
enable-cert-verification=true
# port = 6273
# frontend = "/opt/heavyai/frontend"
# servers-json = "/var/lib/heavyai/servers.json"
# enable-https = true
