// Code generated by Thrift Compiler (0.23.0). DO NOT EDIT.

package heavy

import (
	"bytes"
	"context"
	"errors"
	"fmt"
	"iter"
	"log/slog"
	"time"
	thrift "github.com/apache/thrift/lib/go/thrift"
	"strings"
	"regexp"
	"github.com/heavyai/webserver/internal/db_thrift_client/common"
	"github.com/heavyai/webserver/internal/db_thrift_client/completion_hints"
	"github.com/heavyai/webserver/internal/db_thrift_client/serialized_result_set"
	"github.com/heavyai/webserver/internal/db_thrift_client/extension_functions"

)

// (needed to ensure safety because of naive import list construction.)
var _ = bytes.Equal
var _ = context.Background
var _ = errors.New
var _ = fmt.Printf
var _ = iter.Pull[int]
var _ = slog.Log
var _ = time.Now
var _ = thrift.ZERO
// (needed by validator.)
var _ = strings.Contains
var _ = regexp.MatchString

var _ = common.GoUnusedProtection__
var _ = completion_hints.GoUnusedProtection__
var _ = serialized_result_set.GoUnusedProtection__
var _ = extension_functions.GoUnusedProtection__

func init() {
}

