// Code generated by Thrift Compiler (0.23.0). DO NOT EDIT.

package common

import (
	"bytes"
	"context"
	"database/sql/driver"
	"errors"
	"fmt"
	"iter"
	"log/slog"
	"time"
	thrift "github.com/apache/thrift/lib/go/thrift"
	"strings"
	"regexp"
)

// (needed to ensure safety because of naive import list construction.)
var _ = bytes.Equal
var _ = context.Background
var _ = errors.New
var _ = fmt.Printf
var _ = iter.Pull[int]
var _ = slog.Log
var _ = time.Now
var _ = thrift.ZERO
// (needed by validator.)
var _ = strings.Contains
var _ = regexp.MatchString

type TDeviceType int64

const (
	TDeviceType_CPU TDeviceType = 0
	TDeviceType_GPU TDeviceType = 1
)

var knownTDeviceTypeValues = []TDeviceType{
	TDeviceType_CPU,
	TDeviceType_GPU,
}

func TDeviceTypeValues() iter.Seq[TDeviceType] {
	return func(yield func(TDeviceType) bool) {
		for _, v := range knownTDeviceTypeValues {
			if !yield(v) {
				return
			}
		}
	}
}

func (p TDeviceType) String() string {
	switch p {
	case TDeviceType_CPU: return "CPU"
	case TDeviceType_GPU: return "GPU"
	}
	return "<UNSET>"
}

func TDeviceTypeFromString(s string) (TDeviceType, error) {
	switch s {
	case "CPU": return TDeviceType_CPU, nil
	case "GPU": return TDeviceType_GPU, nil
	}
	return TDeviceType(0), fmt.Errorf("not a valid TDeviceType string")
}


func TDeviceTypePtr(v TDeviceType) *TDeviceType { return &v }

func (p TDeviceType) MarshalText() ([]byte, error) {
	return []byte(p.String()), nil
}

func (p *TDeviceType) UnmarshalText(text []byte) error {
	q, err := TDeviceTypeFromString(string(text))
	if err != nil {
		return err
	}
	*p = q
	return nil
}

func (p *TDeviceType) Scan(value interface{}) error {
	v, ok := value.(int64)
	if !ok {
		return errors.New("Scan value is not int64")
	}
	*p = TDeviceType(v)
	return nil
}

func (p *TDeviceType) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type TDatumType int64

const (
	TDatumType_SMALLINT TDatumType = 0
	TDatumType_INT TDatumType = 1
	TDatumType_BIGINT TDatumType = 2
	TDatumType_FLOAT TDatumType = 3
	TDatumType_DECIMAL TDatumType = 4
	TDatumType_DOUBLE TDatumType = 5
	TDatumType_STR TDatumType = 6
	TDatumType_TIME TDatumType = 7
	TDatumType_TIMESTAMP TDatumType = 8
	TDatumType_DATE TDatumType = 9
	TDatumType_BOOL TDatumType = 10
	TDatumType_INTERVAL_DAY_TIME TDatumType = 11
	TDatumType_INTERVAL_YEAR_MONTH TDatumType = 12
	TDatumType_POINT TDatumType = 13
	TDatumType_LINESTRING TDatumType = 14
	TDatumType_POLYGON TDatumType = 15
	TDatumType_MULTIPOLYGON TDatumType = 16
	TDatumType_TINYINT TDatumType = 17
	TDatumType_GEOMETRY TDatumType = 18
	TDatumType_GEOGRAPHY TDatumType = 19
	TDatumType_MULTILINESTRING TDatumType = 20
	TDatumType_MULTIPOINT TDatumType = 21
)

var knownTDatumTypeValues = []TDatumType{
	TDatumType_SMALLINT,
	TDatumType_INT,
	TDatumType_BIGINT,
	TDatumType_FLOAT,
	TDatumType_DECIMAL,
	TDatumType_DOUBLE,
	TDatumType_STR,
	TDatumType_TIME,
	TDatumType_TIMESTAMP,
	TDatumType_DATE,
	TDatumType_BOOL,
	TDatumType_INTERVAL_DAY_TIME,
	TDatumType_INTERVAL_YEAR_MONTH,
	TDatumType_POINT,
	TDatumType_LINESTRING,
	TDatumType_POLYGON,
	TDatumType_MULTIPOLYGON,
	TDatumType_TINYINT,
	TDatumType_GEOMETRY,
	TDatumType_GEOGRAPHY,
	TDatumType_MULTILINESTRING,
	TDatumType_MULTIPOINT,
}

func TDatumTypeValues() iter.Seq[TDatumType] {
	return func(yield func(TDatumType) bool) {
		for _, v := range knownTDatumTypeValues {
			if !yield(v) {
				return
			}
		}
	}
}

func (p TDatumType) String() string {
	switch p {
	case TDatumType_SMALLINT: return "SMALLINT"
	case TDatumType_INT: return "INT"
	case TDatumType_BIGINT: return "BIGINT"
	case TDatumType_FLOAT: return "FLOAT"
	case TDatumType_DECIMAL: return "DECIMAL"
	case TDatumType_DOUBLE: return "DOUBLE"
	case TDatumType_STR: return "STR"
	case TDatumType_TIME: return "TIME"
	case TDatumType_TIMESTAMP: return "TIMESTAMP"
	case TDatumType_DATE: return "DATE"
	case TDatumType_BOOL: return "BOOL"
	case TDatumType_INTERVAL_DAY_TIME: return "INTERVAL_DAY_TIME"
	case TDatumType_INTERVAL_YEAR_MONTH: return "INTERVAL_YEAR_MONTH"
	case TDatumType_POINT: return "POINT"
	case TDatumType_LINESTRING: return "LINESTRING"
	case TDatumType_POLYGON: return "POLYGON"
	case TDatumType_MULTIPOLYGON: return "MULTIPOLYGON"
	case TDatumType_TINYINT: return "TINYINT"
	case TDatumType_GEOMETRY: return "GEOMETRY"
	case TDatumType_GEOGRAPHY: return "GEOGRAPHY"
	case TDatumType_MULTILINESTRING: return "MULTILINESTRING"
	case TDatumType_MULTIPOINT: return "MULTIPOINT"
	}
	return "<UNSET>"
}

func TDatumTypeFromString(s string) (TDatumType, error) {
	switch s {
	case "SMALLINT": return TDatumType_SMALLINT, nil
	case "INT": return TDatumType_INT, nil
	case "BIGINT": return TDatumType_BIGINT, nil
	case "FLOAT": return TDatumType_FLOAT, nil
	case "DECIMAL": return TDatumType_DECIMAL, nil
	case "DOUBLE": return TDatumType_DOUBLE, nil
	case "STR": return TDatumType_STR, nil
	case "TIME": return TDatumType_TIME, nil
	case "TIMESTAMP": return TDatumType_TIMESTAMP, nil
	case "DATE": return TDatumType_DATE, nil
	case "BOOL": return TDatumType_BOOL, nil
	case "INTERVAL_DAY_TIME": return TDatumType_INTERVAL_DAY_TIME, nil
	case "INTERVAL_YEAR_MONTH": return TDatumType_INTERVAL_YEAR_MONTH, nil
	case "POINT": return TDatumType_POINT, nil
	case "LINESTRING": return TDatumType_LINESTRING, nil
	case "POLYGON": return TDatumType_POLYGON, nil
	case "MULTIPOLYGON": return TDatumType_MULTIPOLYGON, nil
	case "TINYINT": return TDatumType_TINYINT, nil
	case "GEOMETRY": return TDatumType_GEOMETRY, nil
	case "GEOGRAPHY": return TDatumType_GEOGRAPHY, nil
	case "MULTILINESTRING": return TDatumType_MULTILINESTRING, nil
	case "MULTIPOINT": return TDatumType_MULTIPOINT, nil
	}
	return TDatumType(0), fmt.Errorf("not a valid TDatumType string")
}


func TDatumTypePtr(v TDatumType) *TDatumType { return &v }

func (p TDatumType) MarshalText() ([]byte, error) {
	return []byte(p.String()), nil
}

func (p *TDatumType) UnmarshalText(text []byte) error {
	q, err := TDatumTypeFromString(string(text))
	if err != nil {
		return err
	}
	*p = q
	return nil
}

func (p *TDatumType) Scan(value interface{}) error {
	v, ok := value.(int64)
	if !ok {
		return errors.New("Scan value is not int64")
	}
	*p = TDatumType(v)
	return nil
}

func (p *TDatumType) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

type TEncodingType int64

const (
	TEncodingType_NONE TEncodingType = 0
	TEncodingType_FIXED TEncodingType = 1
	TEncodingType_RL TEncodingType = 2
	TEncodingType_DIFF TEncodingType = 3
	TEncodingType_DICT TEncodingType = 4
	TEncodingType_SPARSE TEncodingType = 5
	TEncodingType_GEOINT TEncodingType = 6
	TEncodingType_DATE_IN_DAYS TEncodingType = 7
	TEncodingType_ARRAY TEncodingType = 8
	TEncodingType_ARRAY_DICT TEncodingType = 9
)

var knownTEncodingTypeValues = []TEncodingType{
	TEncodingType_NONE,
	TEncodingType_FIXED,
	TEncodingType_RL,
	TEncodingType_DIFF,
	TEncodingType_DICT,
	TEncodingType_SPARSE,
	TEncodingType_GEOINT,
	TEncodingType_DATE_IN_DAYS,
	TEncodingType_ARRAY,
	TEncodingType_ARRAY_DICT,
}

func TEncodingTypeValues() iter.Seq[TEncodingType] {
	return func(yield func(TEncodingType) bool) {
		for _, v := range knownTEncodingTypeValues {
			if !yield(v) {
				return
			}
		}
	}
}

func (p TEncodingType) String() string {
	switch p {
	case TEncodingType_NONE: return "NONE"
	case TEncodingType_FIXED: return "FIXED"
	case TEncodingType_RL: return "RL"
	case TEncodingType_DIFF: return "DIFF"
	case TEncodingType_DICT: return "DICT"
	case TEncodingType_SPARSE: return "SPARSE"
	case TEncodingType_GEOINT: return "GEOINT"
	case TEncodingType_DATE_IN_DAYS: return "DATE_IN_DAYS"
	case TEncodingType_ARRAY: return "ARRAY"
	case TEncodingType_ARRAY_DICT: return "ARRAY_DICT"
	}
	return "<UNSET>"
}

func TEncodingTypeFromString(s string) (TEncodingType, error) {
	switch s {
	case "NONE": return TEncodingType_NONE, nil
	case "FIXED": return TEncodingType_FIXED, nil
	case "RL": return TEncodingType_RL, nil
	case "DIFF": return TEncodingType_DIFF, nil
	case "DICT": return TEncodingType_DICT, nil
	case "SPARSE": return TEncodingType_SPARSE, nil
	case "GEOINT": return TEncodingType_GEOINT, nil
	case "DATE_IN_DAYS": return TEncodingType_DATE_IN_DAYS, nil
	case "ARRAY": return TEncodingType_ARRAY, nil
	case "ARRAY_DICT": return TEncodingType_ARRAY_DICT, nil
	}
	return TEncodingType(0), fmt.Errorf("not a valid TEncodingType string")
}


func TEncodingTypePtr(v TEncodingType) *TEncodingType { return &v }

func (p TEncodingType) MarshalText() ([]byte, error) {
	return []byte(p.String()), nil
}

func (p *TEncodingType) UnmarshalText(text []byte) error {
	q, err := TEncodingTypeFromString(string(text))
	if err != nil {
		return err
	}
	*p = q
	return nil
}

func (p *TEncodingType) Scan(value interface{}) error {
	v, ok := value.(int64)
	if !ok {
		return errors.New("Scan value is not int64")
	}
	*p = TEncodingType(v)
	return nil
}

func (p *TEncodingType) Value() (driver.Value, error) {
	if p == nil {
		return nil, nil
	}
	return int64(*p), nil
}

// Attributes:
//  - DbID
//  - DictID
// 
type TStringDictKey struct {
	DbID int32 `thrift:"db_id,1" db:"db_id" json:"db_id"`
	DictID int32 `thrift:"dict_id,2" db:"dict_id" json:"dict_id"`
}

func NewTStringDictKey() *TStringDictKey {
	return &TStringDictKey{}
}



func (p *TStringDictKey) GetDbID() int32 {
	return p.DbID
}



func (p *TStringDictKey) GetDictID() int32 {
	return p.DictID
}

func (p *TStringDictKey) Read(ctx context.Context, iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}


	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if fieldTypeId == thrift.I32 {
				if err := p.ReadField1(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 2:
			if fieldTypeId == thrift.I32 {
				if err := p.ReadField2(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(ctx, fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *TStringDictKey) ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(ctx); err != nil {
		return thrift.PrependError("error reading field 1: ", err)
	} else {
		p.DbID = v
	}
	return nil
}

func (p *TStringDictKey) ReadField2(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(ctx); err != nil {
		return thrift.PrependError("error reading field 2: ", err)
	} else {
		p.DictID = v
	}
	return nil
}

func (p *TStringDictKey) Write(ctx context.Context, oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin(ctx, "TStringDictKey"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField1(ctx, oprot); err != nil { return err }
		if err := p.writeField2(ctx, oprot); err != nil { return err }
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *TStringDictKey) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "db_id", thrift.I32, 1); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:db_id: ", p), err)
	}
	if err := oprot.WriteI32(ctx, int32(p.DbID)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.db_id (1) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 1:db_id: ", p), err)
	}
	return err
}

func (p *TStringDictKey) writeField2(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "dict_id", thrift.I32, 2); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:dict_id: ", p), err)
	}
	if err := oprot.WriteI32(ctx, int32(p.DictID)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.dict_id (2) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 2:dict_id: ", p), err)
	}
	return err
}

func (p *TStringDictKey) Equals(other *TStringDictKey) bool {
	if p == other {
		return true
	} else if p == nil || other == nil {
		return false
	}
	if p.DbID != other.DbID { return false }
	if p.DictID != other.DictID { return false }
	return true
}

func (p *TStringDictKey) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TStringDictKey(%+v)", *p)
}

func (p *TStringDictKey) LogValue() slog.Value {
	if p == nil {
		return slog.AnyValue(nil)
	}
	v := thrift.SlogTStructWrapper{
		Type: "*common.TStringDictKey",
		Value: p,
	}
	return slog.AnyValue(v)
}

var _ slog.LogValuer = (*TStringDictKey)(nil)

func (p *TStringDictKey) Validate() error {
	return nil
}

// Attributes:
//  - Type
//  - Encoding
//  - Nullable
//  - IsArray
//  - Precision
//  - Scale
//  - CompParam
//  - Size
//  - DictKey
// 
type TTypeInfo struct {
	Type TDatumType `thrift:"type,1" db:"type" json:"type"`
	Nullable bool `thrift:"nullable,2" db:"nullable" json:"nullable"`
	IsArray bool `thrift:"is_array,3" db:"is_array" json:"is_array"`
	Encoding TEncodingType `thrift:"encoding,4" db:"encoding" json:"encoding"`
	Precision int32 `thrift:"precision,5" db:"precision" json:"precision"`
	Scale int32 `thrift:"scale,6" db:"scale" json:"scale"`
	CompParam int32 `thrift:"comp_param,7" db:"comp_param" json:"comp_param"`
	Size int32 `thrift:"size,8" db:"size" json:"size"`
	DictKey *TStringDictKey `thrift:"dict_key,9" db:"dict_key" json:"dict_key,omitempty"`
}

func NewTTypeInfo() *TTypeInfo {
	return &TTypeInfo{
		Size: -1,
	}
}



func (p *TTypeInfo) GetType() TDatumType {
	return p.Type
}



func (p *TTypeInfo) GetEncoding() TEncodingType {
	return p.Encoding
}



func (p *TTypeInfo) GetNullable() bool {
	return p.Nullable
}



func (p *TTypeInfo) GetIsArray() bool {
	return p.IsArray
}



func (p *TTypeInfo) GetPrecision() int32 {
	return p.Precision
}



func (p *TTypeInfo) GetScale() int32 {
	return p.Scale
}



func (p *TTypeInfo) GetCompParam() int32 {
	return p.CompParam
}

var TTypeInfo_Size_DEFAULT int32 = -1


func (p *TTypeInfo) GetSize() int32 {
	return p.Size
}

var TTypeInfo_DictKey_DEFAULT *TStringDictKey

func (p *TTypeInfo) GetDictKey() *TStringDictKey {
	if !p.IsSetDictKey() {
		return TTypeInfo_DictKey_DEFAULT
	}
	return p.DictKey
}

func (p *TTypeInfo) IsSetSize() bool {
	return p.Size != TTypeInfo_Size_DEFAULT
}

func (p *TTypeInfo) IsSetDictKey() bool {
	return p.DictKey != nil
}

func (p *TTypeInfo) Read(ctx context.Context, iprot thrift.TProtocol) error {
	if _, err := iprot.ReadStructBegin(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read error: ", p), err)
	}


	for {
		_, fieldTypeId, fieldId, err := iprot.ReadFieldBegin(ctx)
		if err != nil {
			return thrift.PrependError(fmt.Sprintf("%T field %d read error: ", p, fieldId), err)
		}
		if fieldTypeId == thrift.STOP {
			break
		}
		switch fieldId {
		case 1:
			if fieldTypeId == thrift.I32 {
				if err := p.ReadField1(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 4:
			if fieldTypeId == thrift.I32 {
				if err := p.ReadField4(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 2:
			if fieldTypeId == thrift.BOOL {
				if err := p.ReadField2(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 3:
			if fieldTypeId == thrift.BOOL {
				if err := p.ReadField3(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 5:
			if fieldTypeId == thrift.I32 {
				if err := p.ReadField5(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 6:
			if fieldTypeId == thrift.I32 {
				if err := p.ReadField6(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 7:
			if fieldTypeId == thrift.I32 {
				if err := p.ReadField7(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 8:
			if fieldTypeId == thrift.I32 {
				if err := p.ReadField8(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		case 9:
			if fieldTypeId == thrift.STRUCT {
				if err := p.ReadField9(ctx, iprot); err != nil {
					return err
				}
			} else {
				if err := iprot.Skip(ctx, fieldTypeId); err != nil {
					return err
				}
			}
		default:
			if err := iprot.Skip(ctx, fieldTypeId); err != nil {
				return err
			}
		}
		if err := iprot.ReadFieldEnd(ctx); err != nil {
			return err
		}
	}
	if err := iprot.ReadStructEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T read struct end error: ", p), err)
	}
	return nil
}

func (p *TTypeInfo) ReadField1(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(ctx); err != nil {
		return thrift.PrependError("error reading field 1: ", err)
	} else {
		temp := TDatumType(v)
		p.Type = temp
	}
	return nil
}

func (p *TTypeInfo) ReadField4(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(ctx); err != nil {
		return thrift.PrependError("error reading field 4: ", err)
	} else {
		temp := TEncodingType(v)
		p.Encoding = temp
	}
	return nil
}

func (p *TTypeInfo) ReadField2(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadBool(ctx); err != nil {
		return thrift.PrependError("error reading field 2: ", err)
	} else {
		p.Nullable = v
	}
	return nil
}

func (p *TTypeInfo) ReadField3(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadBool(ctx); err != nil {
		return thrift.PrependError("error reading field 3: ", err)
	} else {
		p.IsArray = v
	}
	return nil
}

func (p *TTypeInfo) ReadField5(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(ctx); err != nil {
		return thrift.PrependError("error reading field 5: ", err)
	} else {
		p.Precision = v
	}
	return nil
}

func (p *TTypeInfo) ReadField6(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(ctx); err != nil {
		return thrift.PrependError("error reading field 6: ", err)
	} else {
		p.Scale = v
	}
	return nil
}

func (p *TTypeInfo) ReadField7(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(ctx); err != nil {
		return thrift.PrependError("error reading field 7: ", err)
	} else {
		p.CompParam = v
	}
	return nil
}

func (p *TTypeInfo) ReadField8(ctx context.Context, iprot thrift.TProtocol) error {
	if v, err := iprot.ReadI32(ctx); err != nil {
		return thrift.PrependError("error reading field 8: ", err)
	} else {
		p.Size = v
	}
	return nil
}

func (p *TTypeInfo) ReadField9(ctx context.Context, iprot thrift.TProtocol) error {
	p.DictKey = &TStringDictKey{}
	if err := p.DictKey.Read(ctx, iprot); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T error reading struct: ", p.DictKey), err)
	}
	return nil
}

func (p *TTypeInfo) Write(ctx context.Context, oprot thrift.TProtocol) error {
	if err := oprot.WriteStructBegin(ctx, "TTypeInfo"); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write struct begin error: ", p), err)
	}
	if p != nil {
		if err := p.writeField1(ctx, oprot); err != nil { return err }
		if err := p.writeField2(ctx, oprot); err != nil { return err }
		if err := p.writeField3(ctx, oprot); err != nil { return err }
		if err := p.writeField4(ctx, oprot); err != nil { return err }
		if err := p.writeField5(ctx, oprot); err != nil { return err }
		if err := p.writeField6(ctx, oprot); err != nil { return err }
		if err := p.writeField7(ctx, oprot); err != nil { return err }
		if err := p.writeField8(ctx, oprot); err != nil { return err }
		if err := p.writeField9(ctx, oprot); err != nil { return err }
	}
	if err := oprot.WriteFieldStop(ctx); err != nil {
		return thrift.PrependError("write field stop error: ", err)
	}
	if err := oprot.WriteStructEnd(ctx); err != nil {
		return thrift.PrependError("write struct stop error: ", err)
	}
	return nil
}

func (p *TTypeInfo) writeField1(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "type", thrift.I32, 1); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 1:type: ", p), err)
	}
	if err := oprot.WriteI32(ctx, int32(p.Type)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.type (1) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 1:type: ", p), err)
	}
	return err
}

func (p *TTypeInfo) writeField2(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "nullable", thrift.BOOL, 2); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 2:nullable: ", p), err)
	}
	if err := oprot.WriteBool(ctx, bool(p.Nullable)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.nullable (2) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 2:nullable: ", p), err)
	}
	return err
}

func (p *TTypeInfo) writeField3(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "is_array", thrift.BOOL, 3); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 3:is_array: ", p), err)
	}
	if err := oprot.WriteBool(ctx, bool(p.IsArray)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.is_array (3) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 3:is_array: ", p), err)
	}
	return err
}

func (p *TTypeInfo) writeField4(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "encoding", thrift.I32, 4); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 4:encoding: ", p), err)
	}
	if err := oprot.WriteI32(ctx, int32(p.Encoding)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.encoding (4) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 4:encoding: ", p), err)
	}
	return err
}

func (p *TTypeInfo) writeField5(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "precision", thrift.I32, 5); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 5:precision: ", p), err)
	}
	if err := oprot.WriteI32(ctx, int32(p.Precision)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.precision (5) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 5:precision: ", p), err)
	}
	return err
}

func (p *TTypeInfo) writeField6(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "scale", thrift.I32, 6); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 6:scale: ", p), err)
	}
	if err := oprot.WriteI32(ctx, int32(p.Scale)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.scale (6) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 6:scale: ", p), err)
	}
	return err
}

func (p *TTypeInfo) writeField7(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if err := oprot.WriteFieldBegin(ctx, "comp_param", thrift.I32, 7); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field begin error 7:comp_param: ", p), err)
	}
	if err := oprot.WriteI32(ctx, int32(p.CompParam)); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T.comp_param (7) field write error: ", p), err)
	}
	if err := oprot.WriteFieldEnd(ctx); err != nil {
		return thrift.PrependError(fmt.Sprintf("%T write field end error 7:comp_param: ", p), err)
	}
	return err
}

func (p *TTypeInfo) writeField8(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if p.IsSetSize() {
		if err := oprot.WriteFieldBegin(ctx, "size", thrift.I32, 8); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 8:size: ", p), err)
		}
		if err := oprot.WriteI32(ctx, int32(p.Size)); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T.size (8) field write error: ", p), err)
		}
		if err := oprot.WriteFieldEnd(ctx); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 8:size: ", p), err)
		}
	}
	return err
}

func (p *TTypeInfo) writeField9(ctx context.Context, oprot thrift.TProtocol) (err error) {
	if p.IsSetDictKey() {
		if err := oprot.WriteFieldBegin(ctx, "dict_key", thrift.STRUCT, 9); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field begin error 9:dict_key: ", p), err)
		}
		if err := p.DictKey.Write(ctx, oprot); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T error writing struct: ", p.DictKey), err)
		}
		if err := oprot.WriteFieldEnd(ctx); err != nil {
			return thrift.PrependError(fmt.Sprintf("%T write field end error 9:dict_key: ", p), err)
		}
	}
	return err
}

func (p *TTypeInfo) Equals(other *TTypeInfo) bool {
	if p == other {
		return true
	} else if p == nil || other == nil {
		return false
	}
	if p.Type != other.Type { return false }
	if p.Nullable != other.Nullable { return false }
	if p.IsArray != other.IsArray { return false }
	if p.Encoding != other.Encoding { return false }
	if p.Precision != other.Precision { return false }
	if p.Scale != other.Scale { return false }
	if p.CompParam != other.CompParam { return false }
	if p.Size != other.Size { return false }
	if !p.DictKey.Equals(other.DictKey) { return false }
	return true
}

func (p *TTypeInfo) String() string {
	if p == nil {
		return "<nil>"
	}
	return fmt.Sprintf("TTypeInfo(%+v)", *p)
}

func (p *TTypeInfo) LogValue() slog.Value {
	if p == nil {
		return slog.AnyValue(nil)
	}
	v := thrift.SlogTStructWrapper{
		Type: "*common.TTypeInfo",
		Value: p,
	}
	return slog.AnyValue(v)
}

var _ slog.LogValuer = (*TTypeInfo)(nil)

func (p *TTypeInfo) Validate() error {
	return nil
}

